SET TERM ^ ;

ALTER PROCEDURE AAA_BAJA_EGRESADOS (XCARRE VARCHAR(6) CHARACTER SET NONE)
RETURNS (COD_ALU VARCHAR(11) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE)
AS 
declare variable CODMAT varchar(2);
declare variable MAT_EQUI varchar(2);
declare variable SW INTEGER;
begin
  FOR SELECT A.COD_ALU, A.CARRE
  FROM ALUMNOS A
  WHERE A.BAJA='N' AND (A.CARRE=:XCARRE OR :XCARRE IS NULL )
  INTO :COD_ALU, :CARRE
  DO
  BEGIN
    SW=0;
    FOR SELECT M.CODMATERI, trim(M.EQUIVALE)
    FROM MATERIAS M
    WHERE M.CODCARRE=:CARRE AND M.ESTADO<>'B' AND :SW=0
    ORDER BY M.CUATRIM
    INTO :CODMAT, :MAT_EQUI
    DO BEGIN

          IF ( NOT EXISTS(SELECT 1 FROM ANALITIC C
                          WHERE C.CARRE=:CARRE AND C.COD_ALU=:COD_ALU AND C.COD_MAT=:CODMAT)) THEN BEGIN
             IF ( NOT EXISTS(SELECT 1 FROM ANALITIC C
                             WHERE C.CARRE=:CARRE AND C.COD_ALU=:COD_ALU AND C.COD_MAT=:MAT_EQUI)) THEN BEGIN
                SW=1;
             END
          END
    END
    if (SW=0) then BEGIN
       -- SUSPEND;
       UPDATE ALUMNOS A SET BAJA='S' WHERE COD_ALU=:COD_ALU AND CARRE=:CARRE;
    END
  END

end ^

SET TERM ; ^
