SET TERM ^ ;

ALTER PROCEDURE ESCRIBE_MONEDA (NUMERO INTEGER,
IMPORTE NUMERIC(12, 2))
RETURNS (CODIGO INTEGER,
TEXTO VARCHAR(100) CHARACTER SET NONE)
AS 
declare variable LARGO integer;
declare variable IMPTEXTO char(12);
declare variable ANTES varchar(9);
declare variable CONY varchar(3);
declare variable POSIC2 varchar(14);
declare variable POSIC1 varchar(11);
declare variable POSIC0 varchar(7);
declare variable VUELTA smallint;
declare variable TERMINA char(1);
declare variable COTIZA double precision;
begin
-- Modificado por Maria Elena 18/02/2014 TK 65907
CODIGO=NUMERO;
IMPTEXTO=LPAD(IMPORTE,12,' ');
LARGO=1;
VUELTA=0;
TEXTO='';

WHILE (LARGO<10) DO
BEGIN
  TERMINA='N';
  CONY=' Y';
  VUELTA=VUELTA+1;
  ANTES='';
  POSIC2='';
  POSIC1='';
  POSIC0='';

  IF (LARGO=7 OR LARGO=4 OR LARGO=1) THEN BEGIN
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='0' OR SUBSTRING(IMPTEXTO FROM LARGO FOR 1)=' ') THEN POSIC2='';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='1') THEN POSIC2=' CIENTO';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='1' AND SUBSTRING(IMPTEXTO FROM LARGO+1 FOR 1)='0' AND SUBSTRING(IMPTEXTO FROM LARGO+2 FOR 1)='0') THEN
    POSIC2=' CIEN';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='2') THEN POSIC2=' DOSCIENTOS';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='3') THEN POSIC2=' TRESCIENTOS';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='4') THEN POSIC2=' CUATROCIENTOS';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='5') THEN POSIC2=' QUINIENTOS';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='6') THEN POSIC2=' SEISCIENTOS';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='7') THEN POSIC2=' SETECIENTOS';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='8') THEN POSIC2=' OCHOCIENTOS';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='9') THEN POSIC2=' NOVECIENTOS';
    LARGO=LARGO+1;
  END

  IF (LARGO=8 OR LARGO=5 OR LARGO=2) THEN BEGIN
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='0' OR SUBSTRING(IMPTEXTO FROM LARGO FOR 1)=' ') THEN BEGIN
      POSIC1='';
      CONY='';
    END
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='2') THEN BEGIN
      POSIC1=' VEINTI';
      CONY='';
    END
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='3') THEN POSIC1=' TREINTA';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='4') THEN POSIC1=' CUARENTA';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='5') THEN POSIC1=' CINCUENTA';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='6') THEN POSIC1=' SESENTA';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='7') THEN POSIC1=' SETENTA';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='8') THEN POSIC1=' OCHENTA';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='9') THEN POSIC1=' NOVENTA';

    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 2)='10') THEN BEGIN
      POSIC1=' DIEZ';
      TERMINA='S';
      CONY='';
    END
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 2)='11') THEN BEGIN
      POSIC1=' ONCE';
      TERMINA='S';
      CONY='';
    END
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 2)='12') THEN BEGIN
      POSIC1=' DOCE';
      TERMINA='S';
      CONY='';
    END
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 2)='13') THEN BEGIN
      POSIC1=' TRECE';
      TERMINA='S';
      CONY='';
    END
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 2)='14') THEN BEGIN
      POSIC1=' CATORCE';
      TERMINA='S';
      CONY='';
    END
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 2)='15') THEN BEGIN
      POSIC1=' QUINCE';
      TERMINA='S';
      CONY='';
    END
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 2)='16') THEN BEGIN
      POSIC1=' DIECISEIS';
      TERMINA='S';
      CONY='';
    END
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 2)='17') THEN BEGIN
      POSIC1=' DIECISIETE';
      TERMINA='S';
      CONY='';
    END
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 2)='18') THEN BEGIN
      POSIC1=' DIECIOCHO';
      TERMINA='S';
      CONY='';
    END
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 2)='19') THEN BEGIN
      POSIC1=' DIECINUEVE';
      TERMINA='S';
      CONY='';
    END
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 2)='20') THEN BEGIN
      POSIC1=' VEINTE';
      CONY='';
      TERMINA='S';
    END

    LARGO=LARGO+1;
  END
/*------------------*/

  IF ((LARGO=9 OR LARGO=6 OR LARGO=3) AND TERMINA='N') THEN BEGIN
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='0' OR SUBSTRING(IMPTEXTO FROM LARGO FOR 1)=' ') THEN BEGIN
      POSIC0='';
      CONY='';
    END
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='1') THEN POSIC0=' UNO';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='1' AND LARGO=3) THEN POSIC0=' UN';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='1' AND LARGO=6) THEN POSIC0=' UN';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='2') THEN POSIC0=' DOS';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='3') THEN POSIC0=' TRES';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='4') THEN POSIC0=' CUATRO';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='5') THEN POSIC0=' CINCO';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='6') THEN POSIC0=' SEIS';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='7') THEN POSIC0=' SIETE';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='8') THEN POSIC0=' OCHO';
    IF (SUBSTRING(IMPTEXTO FROM LARGO FOR 1)='9') THEN POSIC0=' NUEVE';
  END
  LARGO=LARGO+1;


  IF ((VUELTA=1) AND (POSIC1<>'' OR POSIC2<>'')) THEN ANTES=' MILLONES';
  ELSE
    IF ((VUELTA=1) AND (POSIC0<>'')) THEN ANTES=' MILLON';

  IF ((VUELTA=2) AND (POSIC1<>'' OR POSIC2<>'' OR POSIC0<>'')) THEN ANTES=' MIL';

  IF (POSIC1=' VEINTI') THEN POSIC0=TRIM(POSIC0);
  TEXTO=TEXTO||POSIC2||POSIC1||CONY||POSIC0||ANTES;

END
TEXTO=TEXTO||' con '||SUBSTRING(IMPTEXTO FROM 11 FOR 2)||'/100';
SUSPEND;
end ^

SET TERM ; ^
