SET TERM ^ ;

ALTER PROCEDURE INFORME_PLANI_QR6 (INICAM DATE,
DESDE DATE,
HASTA DATE,
TIPO CHAR(1) CHARACTER SET NONE)
RETURNS (DESCRI VARCHAR(100) CHARACTER SET NONE,
CANTID1 VARCHAR(25) CHARACTER SET NONE,
CANTID2 VARCHAR(25) CHARACTER SET NONE,
NEGRITA CHAR(1) CHARACTER SET NONE)
AS 
declare variable codigo varchar(3);
declare variable codcon varchar(2);
declare variable titu varchar(15);
begin
 IF (TIPO='T') THEN BEGIN
      CODCON='01';
      TITU='LLAMADOS ';
  END
  ELSE IF (TIPO='M') THEN BEGIN
      CODCON='03';
      TITU='MAILS ';
  END
  ELSE IF (TIPO='C') THEN BEGIN
      CODCON='05';
      TITU='CHAT ';
  END

DESCRI='MEDIOS';
CANTID1='DEL PERIODO';
CANTID2='ACUMULADO';
NEGRITA='S';
SUSPEND;
NEGRITA='N';
FOR SELECT M.DESCRI, M.CODIGO
FROM TBL_MED M
ORDER BY ORDEN
INTO :DESCRI, :CODIGO
DO BEGIN
     CANTID1=NULL;
     CANTID2=NULL;

     SELECT COUNT(*)
     FROM INFORMES I
     LEFT OUTER JOIN INF_CAR IC ON IC.INDICE=I.INDICE
     WHERE I.FECHA BETWEEN :DESDE AND :HASTA AND I.TIPCON =:CODCON AND I.TIPMED=:CODIGO
     INTO :CANTID1;

     SELECT COUNT(*)
     FROM INFORMES I
     LEFT OUTER JOIN INF_CAR IC ON IC.INDICE=I.INDICE
     WHERE I.FECHA BETWEEN :INICAM AND :HASTA AND I.TIPCON=:CODCON AND I.TIPMED=:CODIGO
     INTO :CANTID2;

     IF (COALESCE(CANTID1, '0')<>'0' OR COALESCE(CANTID2, '0')<>'0') THEN
        SUSPEND;
END

CANTID1=NULL;
CANTID2=NULL;
DESCRI='TOTALES';

SELECT COUNT(*)
FROM INFORMES I
LEFT OUTER JOIN INF_CAR IC ON IC.INDICE=I.INDICE
WHERE I.FECHA BETWEEN :DESDE AND :HASTA AND I.TIPCON=:CODCON
INTO :CANTID1;

SELECT COUNT(*)
FROM INFORMES I
LEFT OUTER JOIN INF_CAR IC ON IC.INDICE=I.INDICE
WHERE I.FECHA BETWEEN :INICAM AND :HASTA AND I.TIPCON=:CODCON
INTO :CANTID2;

SUSPEND;
end ^

SET TERM ; ^
