SET TERM ^ ;

ALTER PROCEDURE INFORME_PLANI_QR4 (INICAM DATE,
DESDE DATE,
HASTA DATE,
TIPO CHAR(1) CHARACTER SET NONE)
RETURNS (DESCRI VARCHAR(100) CHARACTER SET NONE,
CANTID VARCHAR(25) CHARACTER SET NONE,
NEGRITA CHAR(1) CHARACTER SET NONE)
AS 
declare variable codigo char(2);
declare variable titu varchar(15);
begin
  IF (TIPO='T') THEN BEGIN
      CODIGO='01';
      TITU='LLAMADOS ';
  END
  ELSE IF (TIPO='M') THEN BEGIN
      CODIGO='03';
      TITU='MAILS ';
  END
  ELSE IF (TIPO='C') THEN BEGIN
      CODIGO='05';
      TITU='CHAT ';
  END

  DESCRI='TOTALES';
  SUSPEND;

  SELECT COUNT(*)
  FROM INFORMES I
  LEFT OUTER JOIN INF_CAR IC ON IC.INDICE=I.INDICE
  WHERE I.FECHA BETWEEN :DESDE AND :HASTA AND I.TIPCON=:CODIGO
  INTO :CANTID;
  DESCRI=TITU||' DEL PERIODO';
  SUSPEND;

  CANTID=NULL;
  SELECT COUNT(*)
  FROM INFORMES I
  LEFT OUTER JOIN INF_CAR IC ON IC.INDICE=I.INDICE
  WHERE I.FECHA BETWEEN :INICAM AND :HASTA AND I.TIPCON=:CODIGO
  INTO :CANTID;
  DESCRI=TITU||' ACUMULADOS';
  SUSPEND;
end ^

SET TERM ; ^
