SET TERM ^ ;

ALTER PROCEDURE INFORME_PLANI_QR3 (INICAM DATE,
DESDE DATE,
HASTA DATE)
RETURNS (DESCRI VARCHAR(100) CHARACTER SET NONE,
CANTID1 VARCHAR(25) CHARACTER SET NONE,
CANTID2 VARCHAR(25) CHARACTER SET NONE,
NEGRITA CHAR(1) CHARACTER SET NONE)
AS 
DECLARE VARIABLE CODIGO VARCHAR(3);
begin
DESCRI='MEDIOS';
CANTID1='DEL PERIODO';
CANTID2='ACUMULADO';
NEGRITA='S';
SUSPEND;
NEGRITA='N';
FOR SELECT M.DESCRI, M.CODIGO
FROM TBL_MED M
ORDER BY ORDEN
INTO :DESCRI, :CODIGO
DO BEGIN
     CANTID1=NULL;
     CANTID2=NULL;

     SELECT COUNT(*)
     FROM INFORMES I
     LEFT OUTER JOIN INF_CAR IC ON IC.INDICE=I.INDICE
     WHERE I.FECHA BETWEEN :DESDE AND :HASTA AND I.TIPCON='02' AND I.TIPMED=:CODIGO
     INTO :CANTID1;

     SELECT COUNT(*)
     FROM INFORMES I
     LEFT OUTER JOIN INF_CAR IC ON IC.INDICE=I.INDICE
     WHERE I.FECHA BETWEEN :INICAM AND :HASTA AND I.TIPCON='02' AND I.TIPMED=:CODIGO
     INTO :CANTID2;

     IF (COALESCE(CANTID1, '0')<>'0' OR COALESCE(CANTID2, '0')<>'0') THEN
        SUSPEND;
END

CANTID1=NULL;
CANTID2=NULL;
DESCRI='TOTALES';

SELECT COUNT(*)
FROM INFORMES I
LEFT OUTER JOIN INF_CAR IC ON IC.INDICE=I.INDICE
WHERE I.FECHA BETWEEN :DESDE AND :HASTA AND I.TIPCON='02'
INTO :CANTID1;

SELECT COUNT(*)
FROM INFORMES I
LEFT OUTER JOIN INF_CAR IC ON IC.INDICE=I.INDICE
WHERE I.FECHA BETWEEN :INICAM AND :HASTA AND I.TIPCON='02'
INTO :CANTID2;

SUSPEND;
end ^

SET TERM ; ^
