SET TERM ^ ;

ALTER PROCEDURE INFORME_PLANI_QR2 (INICAM DATE,
DESDE DATE,
HASTA DATE)
RETURNS (DESCRI VARCHAR(100) CHARACTER SET NONE,
CANTID1 VARCHAR(25) CHARACTER SET NONE,
CANTID2 VARCHAR(25) CHARACTER SET NONE,
CANTID3 VARCHAR(25) CHARACTER SET NONE,
CANTID4 VARCHAR(25) CHARACTER SET NONE,
NEGRITA CHAR(1) CHARACTER SET NONE)
AS 
declare variable carre varchar(6);
begin
DESCRI='CARRERAS';
CANTID1='DEL PERIODO';
CANTID2='ACUMULADO';
CANTID3='INSCRIPTOS DEL PERIODO';
CANTID4='INSCRIPTOS ACUMULADOS';
NEGRITA='S';
SUSPEND;
NEGRITA='N';
FOR SELECT C.DESCORT, C.CARRE
  FROM CARRERA C
  WHERE DESACT='N'
  ORDER BY ORDENINF
  INTO :DESCRI, :CARRE
  DO BEGIN
     CANTID1=NULL;
     CANTID2=NULL;
     CANTID3=NULL;
     CANTID4=NULL;

     SELECT COUNT(*)
     FROM INFORMES I
     LEFT OUTER JOIN INF_CAR IC ON IC.INDICE=I.INDICE
     WHERE I.FECHA BETWEEN :DESDE AND :HASTA AND I.TIPCON='02' AND IC.CARRE=:CARRE
     INTO :CANTID1;

     SELECT COUNT(*)
     FROM INFORMES I
     LEFT OUTER JOIN INF_CAR IC ON IC.INDICE=I.INDICE
     WHERE I.FECHA BETWEEN :INICAM AND :HASTA AND I.TIPCON='02' AND IC.CARRE=:CARRE
     INTO :CANTID2;

     SELECT COUNT(*)
     FROM INF_ADMI I
     WHERE I.FECHA BETWEEN :DESDE AND :HASTA AND I.CARRE=:CARRE
     INTO :CANTID3;

     SELECT COUNT(*)
     FROM INF_ADMI I
     WHERE I.FECHA BETWEEN :INICAM AND :HASTA AND I.CARRE=:CARRE
     INTO :CANTID4;

     SUSPEND;
  END

CANTID1=NULL;
CANTID2=NULL;
CANTID3=NULL;
CANTID4=NULL;
DESCRI='TOTALES';
SELECT COUNT(*)
FROM INFORMES I
LEFT OUTER JOIN INF_CAR IC ON IC.INDICE=I.INDICE
WHERE I.FECHA BETWEEN :DESDE AND :HASTA AND I.TIPCON='02'
INTO :CANTID1;

SELECT COUNT(*)
FROM INFORMES I
LEFT OUTER JOIN INF_CAR IC ON IC.INDICE=I.INDICE
WHERE I.FECHA BETWEEN :INICAM AND :HASTA AND I.TIPCON='02'
INTO :CANTID2;

SELECT COUNT(*)
FROM INF_ADMI I
WHERE I.FECHA BETWEEN :DESDE AND :HASTA
INTO :CANTID3;

SELECT COUNT(*)
FROM INF_ADMI I
WHERE I.FECHA BETWEEN :INICAM AND :HASTA
INTO :CANTID4;

SUSPEND;
end ^

SET TERM ; ^
