SET TERM ^ ;

ALTER PROCEDURE INFORME_PLANI_QR1 (INICAM DATE,
DESDE DATE,
HASTA DATE)
RETURNS (DESCRI VARCHAR(100) CHARACTER SET NONE,
CANTID VARCHAR(15) CHARACTER SET NONE,
NEGRITA CHAR(1) CHARACTER SET NONE)
AS 
begin
  --exception e_custom_err 'i '||inicam||' d '||desde||' h '||hasta;
  SELECT COUNT(*)
  FROM INFORMES I
  LEFT OUTER JOIN INF_CAR IC ON IC.INDICE=I.INDICE
  WHERE I.FECHA BETWEEN :DESDE AND :HASTA AND I.TIPCON='02'
  INTO :CANTID;
  DESCRI='INFORMADOS DEL PERIODO';
  SUSPEND;

  CANTID=NULL;
  SELECT COUNT(*)
  FROM INFORMES I
  LEFT OUTER JOIN INF_CAR IC ON IC.INDICE=I.INDICE
  WHERE I.FECHA BETWEEN :INICAM AND :HASTA AND I.TIPCON='02'
  INTO :CANTID;
  DESCRI='INFORMADOS ACUMULADOS';
  SUSPEND;
  CANTID=NULL;
  SELECT COUNT(*)
  FROM INF_ADMI I
  WHERE I.FECHA BETWEEN :DESDE AND :HASTA
  INTO :CANTID;
  DESCRI='INSCRIPTOS DEL PERIODO';
  SUSPEND;
  CANTID=NULL;
  SELECT COUNT(*)
  FROM INF_ADMI I
  WHERE I.FECHA BETWEEN :INICAM AND :HASTA
  INTO :CANTID;
  DESCRI='INSCRIPTOS ACUMULADOS';
  SUSPEND;
end ^

SET TERM ; ^
