SET TERM ^ ;

ALTER PROCEDURE INFORME_INSC_QR1 (DESDE DATE,
HASTA DATE,
TIPO VARCHAR(2) CHARACTER SET NONE)
RETURNS (DESCRI VARCHAR(30) CHARACTER SET NONE)
AS 
begin
  FOR SELECT DISTINCT M.DESCRI
  FROM INFORMES I
  LEFT OUTER JOIN TBL_MED M ON I.TIPMED=M.CODIGO
  WHERE I.FECHA BETWEEN :DESDE AND :HASTA AND (I.ESTADO=:TIPO OR :TIPO='')
  INTO :DESCRI
  DO
    SUSPEND;
end ^

SET TERM ; ^
