SET TERM ^ ;

ALTER PROCEDURE INFORME_IMP_VALIDA (CARRE VARCHAR(6) CHARACTER SET NONE,
NOMBRE VARCHAR(60) CHARACTER SET NONE,
APELLIDO VARCHAR(60) CHARACTER SET NONE)
RETURNS (ERRMSG VARCHAR(80) CHARACTER SET NONE)
AS 
DECLARE VARIABLE INDICE INTEGER;
begin
  INDICE=NULL;
  ERRMSG='';
  SELECT A.INDICE
  FROM INF_ADMI A
  WHERE A.CARRE=:CARRE AND A.APELLIDO=UPPER(:APELLIDO) AND A.NOMBRE=UPPER(:NOMBRE)
  ROWS 1 TO 1
  INTO :INDICE;
  if (INDICE IS NOT NULL) then
     ERRMSG=APELLIDO||' ya fue importado antes';
  suspend;
end ^

SET TERM ; ^
