SET TERM ^ ;

ALTER PROCEDURE INFORME_ASOCIAR (INDICE INTEGER,
INDINSC INTEGER,
CARRE VARCHAR(6) CHARACTER SET NONE)
RETURNS (ERRCOD SMALLINT,
ERRMSG VARCHAR(300) CHARACTER SET NONE)
AS 
declare variable indant integer;
BEGIN
 ERRCOD=0;
 ERRMSG='Asociado';
 IF (COALESCE(INDINSC,'')='') THEN BEGIN
    ERRCOD=2;
    ERRMSG='Debe seleccionar un alumno inscripto';
    SUSPEND;
    EXIT;
 END
 IF (COALESCE(CARRE,'')='') THEN BEGIN
    ERRCOD=2;
    ERRMSG='El alumno seleccionado no posee carrera';
    SUSPEND;
    EXIT;
 END

 SELECT I.INDINSC
 FROM INFORMES I
 WHERE I.INDICE=:INDICE
 INTO :INDANT;

 UPDATE INF_ADMI I SET I.ESTADO='03' WHERE I.INDICE=:INDANT;

 IF (INDANT=INDINSC) THEN BEGIN
   /*--ASUMO QUE SI EL INDICE ANTERIOR (INDANT) DE ADMINISTRACION ES IGUAL QUE EL NUEVO
      (EL QUE VIENE POR PARAMETRO) ESTA QUERIENDO DESASOCIAR
   */
   UPDATE INFORMES I SET I.INDINSC=NULL, I.CARRE=NULL, I.ESTADO='01' WHERE I.INDICE=:INDICE;
   ERRCOD=1;
   ERRMSG='Desea quitar la asociacion?';
 END
 ELSE BEGIN
    UPDATE INFORMES I SET I.INDINSC=:INDINSC, I.CARRE=:CARRE, I.ESTADO='02' WHERE I.INDICE=:INDICE;
    UPDATE INF_ADMI I SET I.ESTADO='04' WHERE I.INDICE=:INDINSC;
 END
 SUSPEND;
END ^

SET TERM ; ^
