SET TERM ^ ;

ALTER PROCEDURE INFORME_POS_ASOC (FINDICE INTEGER,
DESDE DATE,
HASTA DATE)
RETURNS (NOMBRE VARCHAR(40) CHARACTER SET NONE,
APELLIDO VARCHAR(40) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE,
INDINSC INTEGER,
MARCA CHAR(1) CHARACTER SET NONE)
AS 
declare variable iapelli varchar(50);
declare variable inombre varchar(50);
declare variable itipdoc varchar(50);
declare variable inumdoc varchar(50);
declare variable ifecha date;
declare variable iindinsc integer;
declare variable icarre varchar(6);
declare variable lcarreras varchar(50);
declare variable query blob sub_type 1 segment size 80;
declare variable condicion blob sub_type 1 segment size 80;
declare variable x integer;
declare variable valor varchar(50);
begin
  SELECT UPPER(TRIM(I.APELLIDO)), UPPER(TRIM(I.NOMBRE)), UPPER(TRIM(I.TIPDOC)), I.NUMDOC,
         I.FECHA, I.INDINSC, I.CARRE
  FROM INFORMES I
  WHERE I.INDICE=:FINDICE
  INTO :IAPELLI, :INOMBRE, :ITIPDOC, :INUMDOC, :IFECHA, :IINDINSC, :ICARRE;

  SELECT TRIM(A.NOMBRE), TRIM(A.APELLIDO), A.CARRE, A.INDICE
  FROM INF_ADMI A
  WHERE A.INDICE=:IINDINSC
  INTO :NOMBRE, :APELLIDO, :CARRE, :INDINSC;

  IF (NOMBRE IS NOT NULL) THEN BEGIN
     IF (ICARRE=CARRE AND IINDINSC=INDINSC) THEN
        MARCA='S';
     ELSE
        MARCA='N';
     SUSPEND;
  END

  SELECT LIST(I.CARRE,''',''')
  FROM INF_CAR I
  WHERE I.INDICE=:FINDICE
  INTO :LCARRERAS;

  IF (LCARRERAS IS NULL) THEN
     EXIT;
  LCARRERAS=''''||LCARRERAS||'''';
  IF (LCARRERAS CONTAINING 'ADM') THEN
    LCARRERAS=LCARRERAS||',''TAE''';
  NOMBRE=NULL;
  APELLIDO=NULL;
  CARRE=NULL;
  INDINSC=NULL;

  QUERY= 'SELECT TRIM(A.NOMBRE), TRIM(A.APELLIDO), A.CARRE, A.INDICE
          FROM INF_ADMI A
          WHERE A.CARRE IN ('||:LCARRERAS||') AND
                A.ESTADO=''03'' AND A.fecha BETWEEN '''||DESDE||''' AND '''||HASTA||''' AND
               ( UPPER(TRIM(A.APELLIDO))='''||:IAPELLI||''' OR
                 UPPER(TRIM(A.APELLIDO)) CONTAINING '''||:IAPELLI||'''';
  X=1;
  CONDICION='';
  IF (IAPELLI CONTAINING ' ') THEN
     FOR SELECT FVALOR
     FROM YYY_SEGU_EXTRAEOPC(:IAPELLI, ' ')
     INTO :VALOR
     DO
       CONDICION=CONDICION||' OR UPPER(TRIM(A.APELLIDO)) CONTAINING '''||:VALOR||'''';

  WHILE (X<=(CHAR_LENGTH(IAPELLI)/2)) DO BEGIN
     CONDICION=CONDICION||' OR UPPER(TRIM(A.APELLIDO)) CONTAINING '''||SUBSTRING(:IAPELLI FROM 1 FOR (CHAR_LENGTH(:IAPELLI)-X))||'''';
     X=X+1;
  END
  CONDICION=CONDICION||')';
  QUERY=QUERY||CONDICION;
  BEGIN
  FOR EXECUTE STATEMENT QUERY
  INTO :NOMBRE, :APELLIDO, :CARRE, :INDINSC
  DO BEGIN
    IF (ICARRE=CARRE AND IINDINSC=INDINSC) THEN
        MARCA='S';
     ELSE
        MARCA='N';
    SUSPEND;
 /* WHEN ANY DO
    EXCEPTION E_CUSTOM_ERR QUERY;*/
  END
  END
end ^

SET TERM ; ^
