SET TERM ^ ;

ALTER PROCEDURE INFORME_INSC_QR2 (DESDE DATE,
HASTA DATE,
OPC VARCHAR(2) CHARACTER SET NONE)
RETURNS (CARRE VARCHAR(6) CHARACTER SET NONE,
TIPO VARCHAR(20) CHARACTER SET NONE,
MEDIO VARCHAR(30) CHARACTER SET NONE,
CANT INTEGER)
AS 
begin
  FOR SELECT UPPER(X.CARRE), M.DESCRI, C.DESCRI, COUNT(*)
  FROM INFORMES I
  LEFT OUTER JOIN TBL_MED M ON I.TIPMED=M.CODIGO
  LEFT OUTER JOIN TBL_CON C ON I.TIPCON=C.CODIGO
  LEFT OUTER JOIN INF_CAR X ON X.INDICE=I.INDICE
  WHERE I.FECHA BETWEEN :DESDE AND :HASTA AND (I.ESTADO=:OPC  OR :OPC='')
  GROUP BY 1,2,3
  INTO :CARRE, :MEDIO, :TIPO, :CANT
  DO
    SUSPEND;

end ^

SET TERM ; ^
