SET TERM ^ ;

ALTER PROCEDURE INFORME_PLANI_QR5 (INICAM DATE,
DESDE DATE,
HASTA DATE,
TIPO CHAR(1) CHARACTER SET NONE)
RETURNS (DESCRI VARCHAR(100) CHARACTER SET NONE,
CANTID1 VARCHAR(25) CHARACTER SET NONE,
CANTID2 VARCHAR(25) CHARACTER SET NONE,
NEGRITA CHAR(1) CHARACTER SET NONE)
AS 
declare variable carre varchar(6);
declare variable codigo char(2);
declare variable titu varchar(15);
begin
   IF (TIPO='T') THEN BEGIN
      CODIGO='01';
      TITU='LLAMADOS ';
  END
  ELSE IF (TIPO='M') THEN BEGIN
      CODIGO='03';
      TITU='MAILS ';
  END
  ELSE IF (TIPO='C') THEN BEGIN
      CODIGO='05';
      TITU='CHAT ';
  END
  DESCRI='CARRERAS';
  CANTID1='DEL PERIODO';
  CANTID2='ACUMULADO';
  NEGRITA='S';
  SUSPEND;
  NEGRITA='N';
  FOR SELECT C.DESCORT, C.CARRE
  FROM CARRERA C
  WHERE DESACT='N'
  ORDER BY ORDENINF
  INTO :DESCRI, :CARRE
  DO BEGIN
     CANTID1=NULL;
     CANTID2=NULL;

     SELECT COUNT(*)
     FROM INFORMES I
     LEFT OUTER JOIN INF_CAR IC ON IC.INDICE=I.INDICE
     WHERE I.FECHA BETWEEN :DESDE AND :HASTA AND I.TIPCON=:CODIGO AND IC.CARRE=:CARRE
     INTO :CANTID1;

     SELECT COUNT(*)
     FROM INFORMES I
     LEFT OUTER JOIN INF_CAR IC ON IC.INDICE=I.INDICE
     WHERE I.FECHA BETWEEN :INICAM AND :HASTA AND I.TIPCON=:CODIGO AND IC.CARRE=:CARRE
     INTO :CANTID2;

     SUSPEND;
  END

CANTID1=NULL;
CANTID2=NULL;
DESCRI='TOTALES';

SELECT COUNT(*)
FROM INFORMES I
LEFT OUTER JOIN INF_CAR IC ON IC.INDICE=I.INDICE
WHERE I.FECHA BETWEEN :DESDE AND :HASTA AND I.TIPCON=:CODIGO
INTO :CANTID1;

SELECT COUNT(*)
FROM INFORMES I
LEFT OUTER JOIN INF_CAR IC ON IC.INDICE=I.INDICE
WHERE I.FECHA BETWEEN :INICAM AND :HASTA AND I.TIPCON=:CODIGO
INTO :CANTID2;

SUSPEND;
end ^

SET TERM ; ^
