SET TERM ^ ;

ALTER PROCEDURE WEB_MENSAJES (CODALU VARCHAR(11) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE)
RETURNS (FMENSAJE VARCHAR(3000) CHARACTER SET NONE)
AS 
BEGIN
    FMENSAJE='PRUEBA';
    SUSPEND;
END ^

SET TERM ; ^
