SET TERM ^ ;

ALTER PROCEDURE WEB_LOGIN (USUARIO VARCHAR(30) CHARACTER SET NONE,
CLAVE VARCHAR(30) CHARACTER SET NONE,
TIPO INTEGER)
RETURNS (FERRCOD INTEGER,
FERRMSG VARCHAR(100) CHARACTER SET NONE,
COD_ALU VARCHAR(13) CHARACTER SET NONE,
NOMBRE VARCHAR(80) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE,
NOMCARRE VARCHAR(100) CHARACTER SET NONE,
BOTONES VARCHAR(50) CHARACTER SET NONE)
AS 
begin /*$$IBE$$ 

  --1 ALUMNO 0 PADRE
  FERRCOD=0;
  FERRMSG='';
  BOTONES='';
  IF (TIPO=1) THEN BEGIN
     SELECT FIRST 1 COD_ALU, TRIM(A.APELLIDO)||', '||TRIM(A.NOM_APE), CARRE
     FROM ALUMNOS A
     WHERE A.FUSUWEB=:USUARIO AND A.FCLAWEB=:CLAVE AND A.BAJA='N'
     INTO :COD_ALU, :NOMBRE, :CARRE;
     IF (COD_ALU IS NULL) THEN BEGIN
        FERRCOD=2;
        FERRMSG='USARIO O CLAVE INCORECTOS';
     END
     ELSE BEGIN
       SELECT C.DESCARRE FROM CARRERA C WHERE C.CARRE=:CARRE INTO :NOMCARRE;
       IF (CARRE IN ('333','650')) THEN BEGIN
          BOTONES='BTNINASISTENCIAS;BTNSANCIONES';
       END
     END
  END
  SUSPEND;
 $$IBE$$*/ EXIT;
end ^

SET TERM ; ^
