SET TERM ^ ;

ALTER PROCEDURE WEB_INASISTENCIAS (CODALU VARCHAR(13) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE)
RETURNS (FFECHA DATE,
FDESCRI VARCHAR(40) CHARACTER SET NONE,
FCANTID NUMERIC(5, 2),
FJUSTIF VARCHAR(2) CHARACTER SET NONE)
AS 
DECLARE VARIABLE FDDEPRI DATE;
begin
  SELECT FDDEPRI
  FROM TBL_TRIM
  WHERE FANIO=EXTRACT(YEAR FROM CURRENT_DATE)
  INTO :FDDEPRI;

  FOR SELECT F.FECHA,
             T.FDESCRI, F.CANFAL, IIF(T.FJUSTIF='S','SI','NO')
      FROM FALTAS F
      LEFT OUTER JOIN TBL_FALTAS T ON F.CODFAL=T.FCODIGO
      WHERE F.CARRERA=:CARRE AND F.CODALU=:CODALU AND F.FECHA BETWEEN :FDDEPRI AND CURRENT_DATE
            AND F.CANFAL>0
      order by 1
  INTO :FFECHA, :FDESCRI, :FCANTID, :FJUSTIF
  DO
     SUSPEND;
end ^

SET TERM ; ^
