SET TERM ^ ;

ALTER PROCEDURE WEB_INASISTENCIAS_TOTALES (CODALU VARCHAR(13) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE)
RETURNS (FTOTINA NUMERIC(5, 2),
FTOTJUS NUMERIC(5, 2),
FTOTINJ NUMERIC(5, 2))
AS 
declare variable fddepri date;
BEGIN
  SELECT FDDEPRI
  FROM TBL_TRIM
  WHERE FANIO=EXTRACT(YEAR FROM CURRENT_DATE)
  INTO :FDDEPRI;

  SELECT SUM(F.CANFAL)
  FROM FALTAS F
  LEFT OUTER JOIN TBL_FALTAS T ON F.CODFAL=T.FCODIGO
  WHERE F.CARRERA=:CARRE AND F.CODALU=:CODALU AND  F.FECHA BETWEEN :FDDEPRI AND CURRENT_DATE AND T.FJUSTIF='S'
  INTO :FTOTJUS;

  SELECT SUM(F.CANFAL)
  FROM FALTAS F
  LEFT OUTER JOIN TBL_FALTAS T ON F.CODFAL=T.FCODIGO
  WHERE F.CARRERA=:CARRE AND F.CODALU=:CODALU AND  F.FECHA BETWEEN :FDDEPRI AND CURRENT_DATE AND T.FJUSTIF='N'
  INTO :FTOTINJ;

  FTOTJUS=COALESCE(FTOTJUS,0);
  FTOTINJ=COALESCE(FTOTINJ,0);
  FTOTINA=FTOTJUS+FTOTINJ;
  SUSPEND;
END ^

SET TERM ; ^
