SET TERM ^ ;

ALTER PROCEDURE WEB_PERMISOSEXAMEN (CODALU VARCHAR(11) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE)
RETURNS (CODMAT CHAR(2) CHARACTER SET NONE,
DESCRI VARCHAR(50) CHARACTER SET NONE,
CONDICION VARCHAR(15) CHARACTER SET NONE,
MESA INTEGER,
HORA VARCHAR(10) CHARACTER SET NONE,
FECHA DATE,
NOMBRE VARCHAR(60) CHARACTER SET NONE,
VENCIM DATE,
APELLIDO VARCHAR(60) CHARACTER SET NONE,
DESCRI1 VARCHAR(60) CHARACTER SET NONE,
DESCRI2 VARCHAR(60) CHARACTER SET NONE,
CARDES1 VARCHAR(60) CHARACTER SET NONE,
CARDES2 VARCHAR(60) CHARACTER SET NONE,
DNI VARCHAR(10) CHARACTER SET NONE)
AS 
begin
suspend;
end ^

SET TERM ; ^
