SET TERM ^ ;

ALTER PROCEDURE WEB_MATERIAS_ALUMNO (CODALU VARCHAR(11) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE)
RETURNS (FCODMAT VARCHAR(2) CHARACTER SET NONE,
FDESCRI VARCHAR(100) CHARACTER SET NONE,
FCONDIC VARCHAR(20) CHARACTER SET NONE,
FCUTUCO INTEGER,
FNOTA NUMERIC(5, 2),
FFECHA DATE,
FFINAL CHAR(1) CHARACTER SET NONE)
AS 
begin
  FOR SELECT CODMAT, DESCRIPCI, CONDICION, NOTA, FECHA,
         CUTUCO
  FROM XXX_CONSTANCIA_TERCIARIA(:CODALU, :CARRE)
  INTO :FCODMAT, :FDESCRI,  :FCONDIC, :FNOTA, :FFECHA, :FCUTUCO
  DO BEGIN
      FFINAL='N';
      --if (FCONDIC='CURSANDO') then FCONDIC='REGULAR';
      if (CARRE NOT IN ('BAC','333','650') AND FCONDIC IN ('REGULAR')) then
         FFINAL='S';
      if (CARRE IN ('BAC','333','650') AND FCONDIC IN ('LIBRES','PREVIA','MARZO','DICIEMBRE','P/EQUIVALE')) then
         FFINAL='S';
      SUSPEND;
  END
end ^

SET TERM ; ^
