SET TERM ^ ;

ALTER PROCEDURE WEB_SANCIONES (CODALU VARCHAR(11) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE)
RETURNS (FHTML VARCHAR(3000) CHARACTER SET NONE)
AS 
BEGIN
fHTML='';
SUSPEND;
END ^

SET TERM ; ^
