SET TERM ^ ;

ALTER PROCEDURE XXX_IMPRIME_PASE (CODALU VARCHAR(11) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE)
RETURNS (FERRCOD INTEGER,
FERRMSG VARCHAR(100) CHARACTER SET NONE)
AS 
DECLARE VARIABLE CODMAT VARCHAR(2);
DECLARE VARIABLE EQUIVALE VARCHAR(2);
DECLARE VARIABLE SW INTEGER;
DECLARE VARIABLE ANUAL CHAR(1);
DECLARE VARIABLE DESCRIPCI VARCHAR(60);
DECLARE VARIABLE CODMAT2 VARCHAR(2);
DECLARE VARIABLE ESTADO CHAR(1);
begin
  FERRCOD=0;
  FERRMSG='';
  FOR SELECT CODMATERI, EQUIVALE, M.ANUAL, TRIM(M.DESCRIPCI), COALESCE(M.ESTADO,'Y')
      FROM MATERIAS M
      WHERE CODCARRE=:CARRE
      ORDER BY CUATRIM, CODMATERI
      INTO :CODMAT, :EQUIVALE, :ANUAL, :DESCRIPCI, :ESTADO
      DO BEGIN
         SW=0;
         IF (NOT EXISTS(SELECT 1 FROM ANALITIC A WHERE A.COD_ALU=:CODALU AND A.CARRE=:CARRE AND A.COD_MAT=:CODMAT)) THEN
            SW=1;
         IF (ANUAL='S' AND SW=1) THEN BEGIN
            CODMAT2='';
            SELECT CODMATERI FROM MATERIAS WHERE CODCARRE=:CARRE AND TRIM(DESCRIPCI)=:DESCRIPCI AND CODMATERI<>:CODMAT INTO :CODMAT2;
            SW=0;
            IF (NOT EXISTS(SELECT 1 FROM ANALITIC A WHERE A.COD_ALU=:CODALU AND A.CARRE=:CARRE AND A.COD_MAT=:CODMAT2)) THEN
               SW=1;
         END
         IF (COALESCE(EQUIVALE,'')<>'' AND SW=1) THEN BEGIN
               SW=0;
               IF (NOT EXISTS(SELECT 1 FROM ANALITIC A WHERE A.COD_ALU=:CODALU AND A.CARRE=:CARRE AND A.COD_MAT=:EQUIVALE)) THEN
                   SW=1;
         END
         IF (ESTADO='B' AND SW=1) THEN -- si la  materia es baja y nunca la curso no la tengo que tener en cuenta
             SW=0;
         IF (SW=1) THEN BEGIN
              FERRCOD=2;
              FERRMSG='No se puede imprimir, al alumnos le faltan aprobar materias';
              BREAK;
         END
      END
 if (FERRCOD=2) then BEGIN
    FERRCOD=0;
    FERRMSG='';
 END
 ELSE if (FERRCOD<>2) then BEGIN
    FERRCOD=2;
    FERRMSG='No se puede imprimir el pase porque el alunno aprobo todas las materias';
 END
 SUSPEND;
end ^

SET TERM ; ^
