SET TERM ^ ;

ALTER PROCEDURE XXX_ADM_IMP_CUOTA_ENCA RETURNS (INSTITUTO VARCHAR(200) CHARACTER SET NONE,
LINEA VARCHAR(200) CHARACTER SET NONE,
DIRECCION VARCHAR(200) CHARACTER SET NONE,
LOCALI VARCHAR(200) CHARACTER SET NONE,
CUIT VARCHAR(200) CHARACTER SET NONE,
IVA VARCHAR(200) CHARACTER SET NONE,
INICIO VARCHAR(200) CHARACTER SET NONE)
AS 
begin

INSTITUTO='INST. ESTUDIOS SUPERIORES DE BUENOS AIRES';
LINEA='Incorporado a la Ensenanza Oficial A-781';
DIRECCION='Jose E. Uriburu 1045 (C1114AAF)';
LOCALI='Capital Federal - Buenos Aires';
CUIT='CUIT: 30-59230883-0';
IVA='IVA E INGRESOS BRUTOS EXENTO';
INICIO='Inicio de Actividades 07/07/1982';


SUSPEND;
end ^

SET TERM ; ^
