SET TERM ^ ;

ALTER PROCEDURE XXX_FALTAS_COMISION (CARRE VARCHAR(6) CHARACTER SET NONE,
CUTUCO VARCHAR(3) CHARACTER SET NONE,
FECHA DATE,
CUAANIO VARCHAR(3) CHARACTER SET NONE,
CODMAT CHAR(2) CHARACTER SET NONE)
RETURNS (CODALU VARCHAR(11) CHARACTER SET NONE,
NOMBRE VARCHAR(80) CHARACTER SET NONE,
CANANT FLOAT,
CODFAL VARCHAR(2) CHARACTER SET NONE,
CANTID FLOAT)
AS 
declare variable DDE date;
declare variable HTA date;
declare variable FDDEPRI date;
declare variable FHTAPRI date;
declare variable FDDESEG date;
declare variable FHTASEG date;
declare variable FDDETER date;
declare variable FHTATER date;
begin
  IF (FECHA IS NOT NULL) THEN BEGIN
     DDE='01/01/'||EXTRACT(YEAR FROM FECHA);
     HTA='12/31/'||EXTRACT(YEAR FROM FECHA);
  END
  ELSE BEGIN
    IF (CARRE IN ('650','333')) THEN BEGIN
       SELECT FDDEPRI, FHTATER
       FROM TBL_TRIM
       WHERE FANIO='20'||SUBSTRING(:CUAANIO FROM 2)
       INTO :DDE, :HTA;
    END
    ELSE BEGIN
       SELECT FDDEPRI, FHTAPRI, FDDESEG, FHTASEG
       FROM TBL_CUAT
       WHERE FANIO='20'||SUBSTRING(:CUAANIO FROM 2)
       INTO :FDDEPRI, :FHTAPRI, :FDDESEG, :FHTASEG;

       IF (SUBSTRING(CUAANIO FROM 1 FOR 1)='1') THEN BEGIN
         DDE=FDDEPRI;
         HTA=FHTAPRI;
       END
       ELSE BEGIN
         DDE=FDDESEG;
         HTA=FHTASEG;
       END
    END
  END
  CODFAL='PR'; --POR DEFECTO ES PRESENTE
  IF (CARRE IN ('333','650') ) THEN BEGIN
      FOR
      SELECT DISTINCT A.COD_ALU, TRIM(A.APELLIDO)||', '||TRIM(A.NOM_APE)
      FROM CURSADA C
      LEFT OUTER JOIN ALUMNOS A ON A.COD_ALU=C.COD_ALU AND A.CARRE=C.CARRE
      WHERE C.CARRE=:CARRE AND C.CUTUCO=:CUTUCO AND C.CUA_ANIO=:CUAANIO AND A.BAJA='N'
      ORDER BY A.APELLIDO
      INTO :CODALU, :NOMBRE
      DO BEGIN
         CANANT=0;
         SELECT SUM(CANFAL)
         FROM FALTAS F
         WHERE F.CARRERA=:CARRE AND F.CODALU=:CODALU AND F.CUTUCO=:CUTUCO AND F.FECHA BETWEEN :DDE AND COALESCE(:FECHA-1,:HTA) AND F.COD_MAT IS NULL
         INTO :CANANT;
         CODFAL=NULL;
         CANTID=NULL;
         SELECT F.CODFAL, F.CANFAL
         FROM FALTAS F
         WHERE F.CARRERA=:CARRE AND F.CODALU=:CODALU AND F.CUTUCO=:CUTUCO AND F.FECHA=:FECHA AND F.COD_MAT IS NULL
         INTO :CODFAL, :CANTID;
         CODFAL=COALESCE(CODFAL,'PR');
         CANANT=COALESCE(CANANT,0);

         SUSPEND;
      END
      when any do 
        suspend;
        --exception e_custom_err carre||'-'||cutuco||'-'||cuaanio;
  END
  ELSE BEGIN
    FOR
      SELECT DISTINCT A.COD_ALU, TRIM(A.APELLIDO)||', '||TRIM(A.NOM_APE)
      FROM CURSADA C
      LEFT OUTER JOIN ALUMNOS A ON A.COD_ALU=C.COD_ALU AND A.CARRE=C.CARRE
      WHERE C.CARRE=:CARRE AND C.CUTUCO=:CUTUCO AND C.CUA_ANIO=:CUAANIO AND A.BAJA='N' AND C.COD_MAT=:CODMAT
      ORDER BY A.APELLIDO
      INTO :CODALU, :NOMBRE
      DO BEGIN
         CANANT=0;
         SELECT SUM(CANFAL)
         FROM FALTAS F
         WHERE F.CARRERA=:CARRE AND F.CODALU=:CODALU AND F.CUTUCO=:CUTUCO AND F.FECHA BETWEEN :DDE AND COALESCE(:FECHA-1,:HTA) AND F.COD_MAT=:CODMAT
         INTO :CANANT;
         CODFAL=NULL;
         CANTID=NULL;
         SELECT F.CODFAL, F.CANFAL
         FROM FALTAS F
         WHERE F.CARRERA=:CARRE AND F.CODALU=:CODALU AND F.CUTUCO=:CUTUCO AND F.FECHA=:FECHA AND F.COD_MAT=:CODMAT
         INTO :CODFAL, :CANTID;
         CODFAL=COALESCE(CODFAL,'PR');
         CANANT=COALESCE(CANANT,0);
         SUSPEND;
      END
  END
end ^

SET TERM ; ^
