SET TERM ^ ;

ALTER PROCEDURE XXX_MUEVE_ALUMNO (CARDDE VARCHAR(6) CHARACTER SET NONE,
CARHTA VARCHAR(6) CHARACTER SET NONE,
COD_ALU VARCHAR(11) CHARACTER SET NONE,
CODUSU INTEGER)
RETURNS (FERRCOD INTEGER,
FERRMSG VARCHAR(300) CHARACTER SET NONE)
AS 
DECLARE VARIABLE NOMBRE VARCHAR(100);
begin
  SELECT TRIM(A.APELLIDO)||', '||TRIM(A.NOM_APE)
  FROM ALUMNOS A
  WHERE A.COD_ALU=:COD_ALU AND A.CARRE=:CARDDE
  INTO :NOMBRE;

  FERRCOD=1;
  FERRMSG='El Alumno '||NOMBRE||' fue movido a la carrera '||CARHTA||', Confirma?';

  IF (EXISTS(SELECT 1 FROM ALUMNOS A WHERE A.COD_ALU=:COD_ALU AND A.CARRE=:CARHTA AND A.BAJA='N')) THEN BEGIN
     FERRCOD=2;
     FERRMSG='El alumno ya existe en Altas de la carrera: '||CARHTA;
     SUSPEND;
     EXIT;
  END
  ELSE IF (EXISTS(SELECT 1 FROM ALUMNOS A WHERE A.COD_ALU=:COD_ALU AND A.CARRE=:CARHTA AND A.BAJA='S')) THEN BEGIN
     FERRCOD=2;
     FERRMSG='El alumno ya existe en Bajas de la carrera: '||CARHTA;
     SUSPEND;
     EXIT;
  END
  ELSE IF (EXISTS(SELECT 1 FROM CURSADA A WHERE A.COD_ALU=:COD_ALU AND A.CARRE=:CARDDE)) THEN BEGIN
     FERRCOD=2;
     FERRMSG='El alumno tiene materias cargadas. No se puede mover al alumno';
     SUSPEND;
     EXIT;
  END
  ELSE IF (EXISTS(SELECT 1 FROM ANALITIC A WHERE A.COD_ALU=:COD_ALU AND A.CARRE=:CARDDE)) THEN BEGIN
     FERRCOD=2;
     FERRMSG='El alumno tiene materias cargadas en el Analitico. No se puede mover al alumno';
     SUSPEND;
     EXIT;
  END
  UPDATE ALUMNOS SET CARRE=:CARHTA WHERE COD_ALU=:COD_ALU AND CARRE=:CARDDE;

  SUSPEND;
end ^

SET TERM ; ^
