SET TERM ^ ;

ALTER PROCEDURE XXX_OBSERV_PANTA (INDICE INTEGER)
RETURNS (DATOS VARCHAR(1000) CHARACTER SET NONE,
COD_ALU VARCHAR(11) CHARACTER SET NONE,
FMENSAJE VARCHAR(200) CHARACTER SET NONE,
FCOLOR INTEGER,
OBSERV VARCHAR(8000) CHARACTER SET NONE,
XINDICE INTEGER)
AS 
declare variable ctt char(1);
declare variable ca char(1);
declare variable dni char(1);
declare variable fech_ctt date;
declare variable foto char(1);
declare variable aptfis char(1);
declare variable aptfec date;
declare variable dde_pri date;
declare variable hta_ter date;
declare variable cant integer;
declare variable faltas integer;
declare variable codigo varchar(11);
declare variable carre varchar(6);
begin
  FMENSAJE='';
  FCOLOR=0;  --BLANCO

  XINDICE=INDICE;
  SELECT FIRST 1 S.CTT, S.CA,  S.DNI, S.FECH_CTT, S.FFOTO, S.FAPTFIS, S.FAPTFEC,
         S.observ, S.COD_ALU, S.CARRE
  FROM ALUMNOS S
  WHERE S.INDICE=:INDICE
  INTO :CTT, :CA, :DNI, :FECH_CTT, :foto, :APTFIS, :APTFEC, :OBSERV, :CODIGO, :CARRE;

  DATOS='';
  IF (COALESCE(CTT,'')='' AND COALESCE(CA,'')='') THEN BEGIN
     DATOS=DATOS||'**DEBE CERTIFICADO ANALITICO'||ASCII_CHAR(13)||ASCII_CHAR(10)||'**NO POSEE CONSTANCIA DE TITULO EN TRAMITE.'||ASCII_CHAR(13)||ASCII_CHAR(10);
     FMENSAJE=FMENSAJE||'Certificado Analitico'||ASCII_CHAR(13)||ASCII_CHAR(10);
  END
  IF (COALESCE(CTT,'')<>'' AND COALESCE(CA,'')='' AND COALESCE(FECH_CTT+90,CURRENT_DATE)<CURRENT_DATE) THEN BEGIN
     DATOS=DATOS||'**TIENE CONSTANCIA DE TITULO EN TRAMITE PERO VENCIDA'||ASCII_CHAR(13)||ASCII_CHAR(10);
     FMENSAJE=FMENSAJE||'Contancia de titulo vencida'||ASCII_CHAR(13)||ASCII_CHAR(10);
  END
  IF (COALESCE(CTT,'')<>'' AND COALESCE(CA,'')='' AND (FECH_CTT+90)>=CURRENT_DATE) THEN BEGIN
     DATOS=DATOS||'**Tiene constancia de titulo en tramite vence el '||
                   EXTRACT(DAY FROM (FECH_CTT+90))||'/'||EXTRACT(MONTH FROM (FECH_CTT+90))||'/'||EXTRACT(YEAR FROM (FECH_CTT+90))||
                   ASCII_CHAR(13)||ASCII_CHAR(10);
  END
  IF (COALESCE(DNI,'')='') THEN BEGIN
     DATOS=DATOS||'**FALTA FOTOCOPIA DE DNI'||ASCII_CHAR(13)||ASCII_CHAR(10);
     FMENSAJE=FMENSAJE||'Fotocopia DNI'||ASCII_CHAR(13)||ASCII_CHAR(10);
  END
  IF (COALESCE(FOTO,'')='') THEN BEGIN
     DATOS=DATOS||'**FALTA FOGRAFIA 4X4'||ASCII_CHAR(13)||ASCII_CHAR(10);
     FMENSAJE=FMENSAJE||'Foto 4x4'||ASCII_CHAR(13)||ASCII_CHAR(10);
  END
  IF (COALESCE(OBSERV,'')<>'' AND (COALESCE(UPPER(OBSERV),'') NOT CONTAINING 'PADRE' AND COALESCE(UPPER(OBSERV),'') NOT CONTAINING 'MADRE')) THEN BEGIN
     FMENSAJE=FMENSAJE||'Tiene observaciones cargadas'||ASCII_CHAR(13)||ASCII_CHAR(10);
  END
  if (CARRE IN ('333','650')) then BEGIN
     IF (COALESCE(APTFIS,'N')='N') THEN BEGIN
        DATOS=DATOS||'**FALTA APTO FISICO'||ASCII_CHAR(13)||ASCII_CHAR(10);
        FMENSAJE=FMENSAJE||'Apto Fisico'||ASCII_CHAR(13)||ASCII_CHAR(10);
     END
     ELSE IF (COALESCE(APTFEC,CURRENT_DATE)+360<=CURRENT_DATE) THEN BEGIN
        DATOS=DATOS||'**EL APTO FISICO ESTA VENCIDO'||ASCII_CHAR(13)||ASCII_CHAR(10);
        FMENSAJE=FMENSAJE||'Apto Fisico vencido'||ASCII_CHAR(13)||ASCII_CHAR(10);
     END
  END
  IF (FMENSAJE<>'') THEN BEGIN
     FMENSAJE='El alumno debe '||ASCII_CHAR(13)||ASCII_CHAR(10)||FMENSAJE;
     FCOLOR=49376;
  END

  IF (CARRE IN ('333','650')) THEN BEGIN
    SELECT FDDEPRI, FHTATER
    FROM TBL_TRIM
    WHERE FANIO=EXTRACT(YEAR FROM CURRENT_DATE)
    INTO :DDE_PRI, :HTA_TER;

    SELECT COUNT(*)
    FROM ACTAS_DISC A
    WHERE A.COD_ALU=:CODIGO AND A.CARRE=:CARRE AND A.FECHA BETWEEN :DDE_PRI AND :HTA_TER
    INTO :CANT;

    SELECT SUM(CANFAL)
    FROM FALTAS F
    WHERE F.CARRERA=:CARRE AND F.CODALU=:CODIGO AND F.FECHA BETWEEN :DDE_PRI AND :HTA_TER
    INTO :FALTAS;

    IF (FALTAS>=14) THEN BEGIN
       DATOS=DATOS||'**El Alumno tiene mas de '||FALTAS||' faltas '||ASCII_CHAR(13)||ASCII_CHAR(10);
       FMENSAJE=FMENSAJE||'El Alumno tiene mas de '||FALTAS||' faltas'||ASCII_CHAR(13)||ASCII_CHAR(10);
       IF (FALTAS BETWEEN 14 AND 20) THEN
          FCOLOR=16744448; --3257348;
       ELSE IF (FALTAS>20) THEN
          FCOLOR=255;
    END

    IF (CANT>=5) THEN BEGIN
       DATOS=DATOS||'**El Alumno tiene mas de '||CANT||' sanciones '||ASCII_CHAR(13)||ASCII_CHAR(10);
       FMENSAJE=FMENSAJE||'El Alumno tiene mas de '||CANT||' sanciones'||ASCII_CHAR(13)||ASCII_CHAR(10);
       IF (CANT BETWEEN 5 AND 10) THEN
          FCOLOR=16744448;
       ELSE IF (CANT>10) THEN
          FCOLOR=255;
    END
  END
  SUSPEND;
end ^

SET TERM ; ^
