SET TERM ^ ;

ALTER PROCEDURE XXX_ADM_CTACTE_PAGOS (XALUMNO INTEGER,
XIDCUOTA INTEGER)
RETURNS (INDICE INTEGER,
COMCOD VARCHAR(5) CHARACTER SET NONE,
COMNUM VARCHAR(8) CHARACTER SET NONE,
FECHAING DATE,
FECHAPAG DATE,
ESTADO VARCHAR(10) CHARACTER SET NONE,
ESTCOD CHAR(1) CHARACTER SET NONE,
MONTO DOUBLE PRECISION)
AS 
begin
FOR SELECT INDICE, COMCOD, COMNUM, FECHAING, FECHAPAG, MONTO, ESTADO
FROM REC_DATO
WHERE ID_CUOTA=:XIDCUOTA AND ALUMNO=:XALUMNO
INTO :INDICE, :COMCOD, :COMNUM, :FECHAING, :FECHAPAG, :MONTO, :ESTCOD
DO BEGIN
  IF (ESTCOD='2') THEN
     ESTADO='Anulada';
  ELSE
     ESTADO='Aprobada';
  SUSPEND;
END
end ^

SET TERM ; ^
