SET TERM ^ ;

ALTER PROCEDURE XXX_ADM_IMP_RECIBOS_DET (COMCOD VARCHAR(5) CHARACTER SET NONE,
INDDDE VARCHAR(8) CHARACTER SET NONE,
INDHTA VARCHAR(8) CHARACTER SET NONE)
RETURNS (DESCRI VARCHAR(100) CHARACTER SET NONE,
MONTO DOUBLE PRECISION,
SALDO DOUBLE PRECISION,
INDICE INTEGER,
LINEAS VARCHAR(200) CHARACTER SET NONE,
ITM INTEGER)
AS 
declare variable XDESCRI varchar(100);
declare variable XMONTO double precision;
declare variable XSALDO double precision;
declare variable XINDICE integer;
declare variable INDICEAUX integer;
begin
  INDICEAUX=0;
  ITM=0;
  FOR
  SELECT COALESCE(I.DESCRI, C.DESCRI), I.MONTO, D.INDICE
  FROM REC_DATO D
  LEFT OUTER JOIN ADM_CUOT_ITEM I ON D.ID_CUOTA=I.INDICE
  LEFT OUTER JOIN TBL_ADM_CONC C ON C.CODIGO=I.CONCEP
  WHERE D.COMCOD=:COMCOD AND D.COMNUM BETWEEN :INDDDE AND :INDHTA
  ORDER BY D.COMNUM
  INTO :XDESCRI, :XMONTO, :XINDICE
  DO BEGIN
    IF (INDICEAUX=0) THEN
        INDICEAUX=XINDICE;
    ELSE IF (XINDICE<>INDICEAUX) THEN BEGIN
       LINEAS=LPAD('',200,'-');
       DESCRI=NULL;
       SALDO=NULL;
       MONTO=NULL;
       INDICE=INDICEAUX;
       ITM=ITM+1;
       SUSPEND;
       SELECT SUM(I.MONTO)
       FROM REC_DATO D
       LEFT OUTER JOIN ADM_CUOT_ITEM I ON D.ID_CUOTA=I.INDICE
       WHERE D.INDICE=:INDICE
       INTO :SALDO;
       LINEAS=NULL;
       DESCRI='SUBTOTAL';
       ITM=ITM+1;
       SUSPEND;
       LINEAS=LPAD('',200,'-');
       DESCRI=NULL;
       MONTO=NULL;
       SALDO=NULL;
       ITM=ITM+1;
       SUSPEND;
       LINEAS=NULL;
       DESCRI='PAGOS ANTERIORES........';
       SELECT SUM(D1.MONTO)
       FROM REC_DATO D
       LEFT OUTER JOIN REC_DATO D1 ON D1.ID_CUOTA=D.ID_CUOTA
       WHERE D.INDICE=:INDICE AND D1.INDICE<>D.INDICE
       INTO :MONTO;
       MONTO=COALESCE(MONTO,0);
       ITM=ITM+1;
       SUSPEND;
       LINEAS=LPAD('',200,'-');
       DESCRI=NULL;
       MONTO=NULL;
       SALDO=NULL;
       ITM=ITM+1;
       SUSPEND;
       LINEAS=NULL;
       DESCRI='PAGO ACTUAL.............';
       SELECT D.MONTO
       FROM REC_DATO D
       WHERE D.INDICE=:INDICE
       INTO :MONTO;
       SALDO=NULL;
       ITM=ITM+1;
       SUSPEND;
       SALDO=NULL;
       MONTO=NULL;
       DESCRI='DEBE DE ESTA CUOTA......';
       LINEAS=NULL;
       SELECT X.TOTAL-X.TOTPAG
       FROM REC_DATO D
       LEFT OUTER JOIN ADM_CUOT_DATO X ON X.INDICE=D.ID_CUOTA
       WHERE D.INDICE=:INDICE
       INTO :MONTO;
       MONTO=COALESCE(MONTO,0);
       SALDO=NULL;
       ITM=ITM+1;
       SUSPEND;
       SALDO=NULL;
       MONTO=NULL;
       INDICEAUX=XINDICE;
    END
    LINEAS=NULL;
    SALDO=NULL;
    MONTO=NULL;
    DESCRI=XDESCRI;
    MONTO=XMONTO;
    INDICE=XINDICE;
    ITM=ITM+1;
    SUSPEND;
  END

LINEAS=LPAD('',200,'-');
DESCRI=NULL;
SALDO=NULL;
MONTO=NULL;
INDICE=INDICEAUX;
ITM=ITM+1;
SUSPEND;
LINEAS=NULL;
SELECT SUM(I.MONTO)
FROM REC_DATO D
LEFT OUTER JOIN ADM_CUOT_ITEM I ON D.ID_CUOTA=I.INDICE
WHERE D.INDICE=:INDICE
INTO :SALDO;
LINEAS=NULL;
DESCRI='SUBTOTAL................';
ITM=ITM+1;
SUSPEND;
LINEAS=LPAD('',200,'-');
DESCRI=NULL;
MONTO=NULL;
SALDO=NULL;
ITM=ITM+1;
SUSPEND;
LINEAS=NULL;
DESCRI='PAGOS ANTERIORES........';
SELECT SUM(D1.MONTO)
FROM REC_DATO D
LEFT OUTER JOIN REC_DATO D1 ON D1.ID_CUOTA=D.ID_CUOTA
WHERE D.INDICE=:INDICE AND D1.INDICE<>D.INDICE
INTO :MONTO;
MONTO=COALESCE(MONTO,0);
ITM=ITM+1;
SUSPEND;
LINEAS=LPAD('',200,'-');
DESCRI=NULL;
MONTO=NULL;
SALDO=NULL;
ITM=ITM+1;
SUSPEND;
LINEAS=NULL;
DESCRI='PAGO ACTUAL.............';
SELECT D.MONTO
FROM REC_DATO D
WHERE D.INDICE=:INDICE
INTO :MONTO;
SALDO=NULL;
ITM=ITM+1;
SUSPEND;
SALDO=NULL;
MONTO=NULL;
LINEAS=NULL;
DESCRI='DEBE DE ESTA CUOTA......';
SELECT X.TOTAL-X.TOTPAG
FROM REC_DATO D
LEFT OUTER JOIN ADM_CUOT_DATO X ON X.INDICE=D.ID_CUOTA
WHERE D.INDICE=:INDICE
INTO :MONTO;
MONTO=COALESCE(MONTO,0);
SALDO=NULL;
ITM=ITM+1;
SUSPEND;
end ^

SET TERM ; ^
