SET TERM ^ ;

ALTER PROCEDURE XXX_ADM_COMP_ULTNUM (COMCOD VARCHAR(5) CHARACTER SET NONE)
RETURNS (NUMERO VARCHAR(5) CHARACTER SET NONE)
AS 
begin
  SELECT ULTNUM+1
  FROM TBL_COMP
  WHERE CODIGO=:COMCOD
  INTO :NUMERO;
  UPDATE TBL_COMP SET ULTNUM=:NUMERO WHERE CODIGO=:COMCOD;

  suspend;
end ^

SET TERM ; ^
