SET TERM ^ ;

ALTER PROCEDURE XXX_CONT_FALTAS (CODALU VARCHAR(13) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE,
CODMAT CHAR(2) CHARACTER SET NONE,
TRIMESTRE INTEGER)
RETURNS (FALTAS NUMERIC(5, 2),
JUSTI NUMERIC(5, 2))
AS 
DECLARE VARIABLE FDDEPRI DATE;
DECLARE VARIABLE FHTAPRI DATE;
DECLARE VARIABLE FDDESEG DATE;
DECLARE VARIABLE FHTASEG DATE;
DECLARE VARIABLE FDDETER DATE;
DECLARE VARIABLE FHTATER DATE;
DECLARE VARIABLE DDE DATE;
DECLARE VARIABLE HTA DATE;
begin

IF (CARRE IN ('333','650')) THEN BEGIN
    SELECT FDDEPRI, FHTAPRI, FDDESEG, FHTASEG, FDDETER, FHTATER
    FROM TBL_TRIM
    WHERE FANIO=EXTRACT(YEAR FROM CURRENT_DATE)
    INTO :FDDEPRI, :FHTAPRI, :FDDESEG, :FHTASEG, :FDDETER, :FHTATER;

    IF (TRIMESTRE=1) THEN BEGIN
       SELECT SUM(F.CANFAL)
       FROM FALTAS F
       WHERE F.CARRERA=:CARRE AND F.CODALU=:CODALU AND F.FECHA BETWEEN :FDDEPRI AND :FHTAPRI
       INTO :FALTAS;
    END
    ELSE IF (TRIMESTRE=2) THEN BEGIN
       SELECT SUM(F.CANFAL)
       FROM FALTAS F
       WHERE F.CARRERA=:CARRE AND F.CODALU=:CODALU AND F.FECHA BETWEEN :FDDESEG AND :FHTASEG
       INTO :FALTAS;
    END
    ELSE IF (TRIMESTRE=3) THEN BEGIN
       SELECT SUM(F.CANFAL)
       FROM FALTAS F
       WHERE F.CARRERA=:CARRE AND F.CODALU=:CODALU AND F.FECHA BETWEEN :FDDETER AND :FHTATER
       INTO :FALTAS;
    END
END
ELSE BEGIN
    SELECT T.FDDEPRI, T.FHTAPRI, T.FDDESEG, T.FHTASEG
    FROM TBL_CUAT T
    WHERE FANIO=(CAST(SUBSTRING(:TRIMESTRE FROM 2 FOR 2) AS INTEGER)+2000) --UNA BURRADA PERO BUE
    INTO :FDDEPRI, :FHTAPRI, :FDDESEG, :FHTASEG;

    IF (SUBSTRING(TRIMESTRE FROM 1 FOR 1)='1') THEN BEGIN
        DDE=FDDEPRI;
        HTA=FHTAPRI;
    END
    ELSE BEGIN
        DDE=FDDESEG;
        HTA=FHTASEG;
    END

    SELECT SUM(F.CANFAL)
    FROM FALTAS F
    LEFT OUTER JOIN TBL_FALTAS T ON T.FCODIGO=F.CODFAL
    WHERE F.CARRERA=:CARRE AND F.CODALU=:CODALU AND F.FECHA BETWEEN :DDE AND :HTA AND F.COD_MAT=:CODMAT AND T.FJUSTIF='N'
    INTO :FALTAS;

    SELECT SUM(F.CANFAL)
    FROM FALTAS F
    LEFT OUTER JOIN TBL_FALTAS T ON T.FCODIGO=F.CODFAL
    WHERE F.CARRERA=:CARRE AND F.CODALU=:CODALU AND F.FECHA BETWEEN :DDE AND :HTA  AND F.COD_MAT=:CODMAT AND T.FJUSTIF='S'
    INTO :JUSTI;

    FALTAS=COALESCE(FALTAS,0);
    JUSTI=COALESCE(JUSTI,0);

END
SUSPEND;
end ^

SET TERM ; ^
