SET TERM ^ ;

ALTER PROCEDURE XXX_GRABA_NUMEQUI (NUMERO INTEGER,
CARRE VARCHAR(6) CHARACTER SET NONE)
AS 
declare variable TIPO varchar(3);
begin
  SELECT TIPO FROM CARRERA WHERE CARRE=:carre INTO :TIPO;
  IF (TIPO IN ('BAC','BAD')) THEN BEGIN
     UPDATE TBLEQUIVA SET ULTNUM=:NUMERO WHERE CARRE=:CARRE;
  END
  ELSE BEGIN
     UPDATE TBLEQUIVA SET ULTNUM=:NUMERO WHERE CARRE='TER' AND ULTNUM<:NUMERO;
  END
end ^

SET TERM ; ^
