SET TERM ^ ;

ALTER PROCEDURE XXX_ADM_ANULA_CUOTA (INDICE INTEGER)
RETURNS (ERRCOD INTEGER,
ERRMSG VARCHAR(100) CHARACTER SET NONE)
AS 
DECLARE VARIABLE TOTPAG DOUBLE PRECISION;
DECLARE VARIABLE ESTADO CHAR(1);
begin

  SELECT A.TOTPAG, A.ESTADO
  FROM ADM_CUOT_DATO A
  WHERE A.INDICE=:INDICE
  INTO :TOTPAG, :ESTADO;

  IF (TOTPAG<>0) THEN BEGIN
    ERRCOD=2;
    ERRMSG='No se puede anular una cuota/matricula con pagos aplicados';
    SUSPEND;
    EXIT;
  END

  IF (ESTADO<>'0') THEN BEGIN
    ERRCOD=2;
    ERRMSG='No se puede anular una cuota/matricula anulada o con pagos aplicados';
    SUSPEND;
    EXIT;
  END

  UPDATE ADM_CUOT_DATO A SET A.ESTADO='2' WHERE INDICE=:INDICE;

end ^

SET TERM ; ^
