SET TERM ^ ;

ALTER PROCEDURE XXX_ADM_CTACTE_TOTCARRE (XALUMNO INTEGER)
RETURNS (CARRERA CHAR(3) CHARACTER SET NONE,
MONTO DOUBLE PRECISION)
AS 
begin


  FOR SELECT A.CARRE, SUM(C.TOTAL-C.TOTPAG)
  FROM ALUMNOS A
  LEFT OUTER JOIN ALUMNOS X ON X.COD_ALU=A.COD_ALU
  LEFT OUTER JOIN ADM_CUOT_DATO C ON C.ALUMNO=X.INDICE
  WHERE A.INDICE=:XALUMNO AND C.ESTADO='0'
  GROUP BY 1
  INTO :CARRERA, :MONTO
  DO
    SUSPEND;
end ^

SET TERM ; ^
