SET TERM ^ ;

ALTER PROCEDURE XXX_VAL_COMISION (CARRE VARCHAR(6) CHARACTER SET NONE,
CUTUCO INTEGER,
CODMAT VARCHAR(2) CHARACTER SET NONE,
CUAANIO INTEGER)
RETURNS (FERRCOD INTEGER,
FERRMSG VARCHAR(500) CHARACTER SET NONE)
AS 
DECLARE VARIABLE DIA1 VARCHAR(9);
DECLARE VARIABLE BLOQUE1 VARCHAR(7);
DECLARE VARIABLE DIA2 VARCHAR(9);
DECLARE VARIABLE BLOQUE2 VARCHAR(7);
DECLARE VARIABLE DIA3 VARCHAR(9);
DECLARE VARIABLE BLOQUE3 VARCHAR(7);
DECLARE VARIABLE BLOQUEAUX VARCHAR(7);
DECLARE VARIABLE DESCRI VARCHAR(60);
DECLARE VARIABLE CUATRIM SMALLINT;
begin
  FERRCOD=0;
  FERRMSG='';

  SELECT DIA1, BLOQUE1, DIA2, BLOQUE2, DIA3, BLOQUE3, T.CUATRIM
  FROM COMARM M
  LEFT OUTER JOIN MATERIAS T ON T.CODMATERI=M.COD_MAT AND T.CODCARRE=M.CARRE
  WHERE CARRE=:CARRE AND CUTUCO=:CUTUCO AND COD_MAT=:CODMAT  AND CUA_ANIO=:CUAANIO
  INTO :DIA1, :BLOQUE1, :DIA2, :BLOQUE2, :DIA3, :BLOQUE3, :CUATRIM;
  IF (CUATRIM<>SUBSTRING(CUTUCO FROM 1 FOR 1)) THEN BEGIN
     FERRCOD=2;
     FERRMSG='El cuatrimestre que cargo no es el de la materia';
     SUSPEND;
     EXIT;
  END
  IF (COALESCE(DIA1,'BLANCO')<>'BLANCO') THEN BEGIN
      FOR SELECT BLOQUE1, T.DESCRIPCI
      FROM COMARM M
      LEFT OUTER JOIN MATERIAS T ON T.CODMATERI=M.COD_MAT AND T.CODCARRE=M.CARRE
      WHERE CARRE=:CARRE AND CUTUCO=:CUTUCO AND CUA_ANIO=:CUAANIO AND DIA1=:DIA1 AND COD_MAT<>:CODMAT AND TRIM(BLOQUE1)<>'BLANCO'
      ORDER BY COD_MAT
      INTO :BLOQUEAUX, :DESCRI
      DO BEGIN
          IF (TRIM(BLOQUE1)='UNICO') THEN BEGIN
               FERRCOD=2;
               FERRMSG=FERRMSG||DESCRI||ASCII_CHAR(13);
          END
          ELSE IF (TRIM(BLOQUE1)='PRISEG' AND TRIM(BLOQUEAUX) IN ('PRISEG','PRITER','PRIMERO','SEGUNDO')) THEN BEGIN
               FERRCOD=2;
               FERRMSG=FERRMSG||DESCRI||ASCII_CHAR(13);
          END
          ELSE IF (TRIM(BLOQUE1)='PRITER' AND TRIM(BLOQUEAUX) IN ('PRISEG','PRITER','PRIMERO','TERCERO')) THEN BEGIN
               FERRCOD=2;
               FERRMSG=FERRMSG||DESCRI||ASCII_CHAR(13);
          END
          ELSE IF (TRIM(BLOQUE1)='PRIMERO' AND TRIM(BLOQUEAUX) IN ('PRISEG','PRITER','PRIMERO')) THEN BEGIN
               FERRCOD=2;
               FERRMSG=FERRMSG||DESCRI||ASCII_CHAR(13);
          END
          ELSE IF (TRIM(BLOQUE1)='SEGTER' AND TRIM(BLOQUEAUX) IN ('PRISEG','PRITER','SEGUNDO','TERCERO')) THEN BEGIN
               FERRCOD=2;
               FERRMSG=FERRMSG||DESCRI||ASCII_CHAR(13);
          END
          ELSE IF (TRIM(BLOQUE1)='SEGUNDO' AND TRIM(BLOQUEAUX) IN ('PRISEG','SEGUNDO','SEGTER')) THEN BEGIN
               FERRCOD=2;
               FERRMSG=FERRMSG||DESCRI||ASCII_CHAR(13);
          END
          ELSE IF (TRIM(BLOQUE1)='TERCERO' AND TRIM(BLOQUEAUX) IN ('PRITER','TERCERO','SEGTER')) THEN BEGIN
               FERRCOD=2;
               FERRMSG=FERRMSG||DESCRI||ASCII_CHAR(13);
          END
      END
  END
  IF (COALESCE(DIA2,'BLANCO')<>'BLANCO') THEN BEGIN
      FOR SELECT BLOQUE2, T.DESCRIPCI
      FROM COMARM M
      LEFT OUTER JOIN MATERIAS T ON T.CODMATERI=M.COD_MAT AND T.CODCARRE=M.CARRE
      WHERE CARRE=:CARRE AND CUTUCO=:CUTUCO AND CUA_ANIO=:CUAANIO AND DIA2=:DIA2 AND COD_MAT<>:CODMAT AND TRIM(BLOQUE2)<>'BLANCO'
      ORDER BY COD_MAT
      INTO :BLOQUEAUX, :DESCRI
      DO BEGIN
          IF (TRIM(BLOQUE2)='UNICO') THEN BEGIN
               FERRCOD=2;
               FERRMSG=FERRMSG||DESCRI||ASCII_CHAR(13);
          END
          ELSE IF (TRIM(BLOQUE2)='PRISEG' AND TRIM(BLOQUEAUX) IN ('PRISEG','PRITER','PRIMERO','SEGUNDO')) THEN BEGIN
               FERRCOD=2;
               FERRMSG=FERRMSG||DESCRI||ASCII_CHAR(13);
          END
          ELSE IF (TRIM(BLOQUE2)='PRITER' AND TRIM(BLOQUEAUX) IN ('PRISEG','PRITER','PRIMERO','TERCERO')) THEN BEGIN
               FERRCOD=2;
               FERRMSG=FERRMSG||DESCRI||ASCII_CHAR(13);
          END
          ELSE IF (TRIM(BLOQUE2)='PRIMERO' AND TRIM(BLOQUEAUX) IN ('PRISEG','PRITER','PRIMERO')) THEN BEGIN
               FERRCOD=2;
               FERRMSG=FERRMSG||DESCRI||ASCII_CHAR(13);
          END
          ELSE IF (TRIM(BLOQUE2)='SEGTER' AND TRIM(BLOQUEAUX) IN ('PRISEG','PRITER','SEGUNDO','TERCERO')) THEN BEGIN
               FERRCOD=2;
               FERRMSG=FERRMSG||DESCRI||ASCII_CHAR(13);
          END
          ELSE IF (TRIM(BLOQUE2)='SEGUNDO' AND TRIM(BLOQUEAUX) IN ('PRISEG','SEGUNDO','SEGTER')) THEN BEGIN
               FERRCOD=2;
               FERRMSG=FERRMSG||DESCRI||ASCII_CHAR(13);
          END
          ELSE IF (TRIM(BLOQUE2)='TERCERO' AND TRIM(BLOQUEAUX) IN ('PRITER','TERCERO','SEGTER')) THEN BEGIN
               FERRCOD=2;
               FERRMSG=FERRMSG||DESCRI||ASCII_CHAR(13);
          END
      END
  END
  IF (COALESCE(DIA3,'BLANCO')<>'BLANCO') THEN BEGIN
      FOR SELECT BLOQUE3, T.DESCRIPCI
      FROM COMARM M
      LEFT OUTER JOIN MATERIAS T ON T.CODMATERI=M.COD_MAT AND T.CODCARRE=M.CARRE
      WHERE CARRE=:CARRE AND CUTUCO=:CUTUCO AND CUA_ANIO=:CUAANIO AND DIA3=:DIA3 AND COD_MAT<>:CODMAT AND TRIM(BLOQUE3)<>'BLANCO'
      ORDER BY COD_MAT
      INTO :BLOQUEAUX, :DESCRI
      DO BEGIN
          IF (TRIM(BLOQUE3)='UNICO') THEN BEGIN
               FERRCOD=2;
               FERRMSG=FERRMSG||DESCRI||ASCII_CHAR(13);
          END
          ELSE IF (TRIM(BLOQUE3)='PRISEG' AND TRIM(BLOQUEAUX) IN ('PRISEG','PRITER','PRIMERO','SEGUNDO')) THEN BEGIN
               FERRCOD=2;
               FERRMSG=FERRMSG||DESCRI||ASCII_CHAR(13);
          END
          ELSE IF (TRIM(BLOQUE3)='PRITER' AND TRIM(BLOQUEAUX) IN ('PRISEG','PRITER','PRIMERO','TERCERO')) THEN BEGIN
               FERRCOD=2;
               FERRMSG=FERRMSG||DESCRI||ASCII_CHAR(13);
          END
          ELSE IF (TRIM(BLOQUE3)='PRIMERO' AND TRIM(BLOQUEAUX) IN ('PRISEG','PRITER','PRIMERO')) THEN BEGIN
               FERRCOD=2;
               FERRMSG=FERRMSG||DESCRI||ASCII_CHAR(13);
          END
          ELSE IF (TRIM(BLOQUE3)='SEGTER' AND TRIM(BLOQUEAUX) IN ('PRISEG','PRITER','SEGUNDO','TERCERO')) THEN BEGIN
               FERRCOD=2;
               FERRMSG=FERRMSG||DESCRI||ASCII_CHAR(13);
          END
          ELSE IF (TRIM(BLOQUE3)='SEGUNDO' AND TRIM(BLOQUEAUX) IN ('PRISEG','SEGUNDO','SEGTER')) THEN BEGIN
               FERRCOD=2;
               FERRMSG=FERRMSG||DESCRI||ASCII_CHAR(13);
          END
          ELSE IF (TRIM(BLOQUE3)='TERCERO' AND TRIM(BLOQUEAUX) IN ('PRITER','TERCERO','SEGTER')) THEN BEGIN
               FERRCOD=2;
               FERRMSG=FERRMSG||DESCRI||ASCII_CHAR(13);
          END
      END
  END
IF (FERRCOD=2) THEN
   FERRMSG='La materia cargada se superpone con las siguientes: '||ASCII_CHAR(13)||FERRMSG;
suspend;
end ^

SET TERM ; ^
