SET TERM ^ ;

ALTER PROCEDURE XXX_NUMERO_EQUIVALENCIA (CODALU VARCHAR(11) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE)
RETURNS (NUM_FORMA VARCHAR(40) CHARACTER SET NONE,
NUM_ENTERO VARCHAR(20) CHARACTER SET NONE,
FERRMSG VARCHAR(300) CHARACTER SET NONE,
FNUMNUE VARCHAR(1) CHARACTER SET NONE)
AS 
declare variable NUMERO varchar(20);
declare variable CANT integer;
declare variable ULTANIO integer;
declare variable TIPO varchar(3);
begin
  FNUMNUE='N';
  NUM_FORMA='';
  NUM_ENTERO=0;
  FERRMSG='';
  SELECT TIPO FROM CARRERA WHERE CARRE=:CARRE INTO :TIPO;
  IF (TIPO IN ('BAC','BAD')) THEN BEGIN
       SELECT ANIO FROM TBLEQUIVA WHERE CARRE=:CARRE INTO :ULTANIO;
       IF (ULTANIO<>EXTRACT(YEAR FROM CURRENT_DATE)) THEN
           UPDATE TBLEQUIVA SET ANIO=EXTRACT(YEAR FROM CURRENT_DATE), ULTNUM=0 WHERE CARRE=:CARRE;
       CANT=NULL;
       SELECT COUNT(DISTINCT C.ACTINT)
       FROM ANALITIC C
       WHERE C.COD_ALU=:CODALU AND C.CARRE=:CARRE AND C.CONDICION='EQUIVALENCIA' AND
             SUBSTRING(C.ACTINT FROM CHAR_LENGTH(C.ACTINT)-1 FOR 2)=SUBSTRING(:ULTANIO FROM 3 FOR 2)
       INTO :CANT;
       IF (COALESCE(CANT,0)>1) THEN BEGIN
          FERRMSG='El alumno tiene dos numeros de actuacion interna se tomara la mas reciente';
          SELECT MAX(SUBSTRING(C.ACTINT FROM 1 FOR CHAR_LENGTH(C.ACTINT)-2))
          FROM ANALITIC C
          WHERE C.COD_ALU=:CODALU AND C.CARRE=:CARRE AND C.CONDICION='EQUIVALENCIA' AND
                SUBSTRING(C.ACTINT FROM CHAR_LENGTH(C.ACTINT)-1 FOR 2)=SUBSTRING(:ULTANIO FROM 3 FOR 2)
          INTO :NUMERO;
       END
       ELSE IF (COALESCE(CANT,0)=1) THEN BEGIN
          SELECT MAX(SUBSTRING(TRIM(ACTINT) FROM 1 FOR CHAR_LENGTH(TRIM(ACTINT))-2))
          FROM ANALITIC C
          WHERE C.COD_ALU=:CODALU AND C.CARRE=:CARRE AND C.CONDICION='EQUIVALENCIA' AND
                SUBSTRING(C.ACTINT FROM CHAR_LENGTH(C.ACTINT)-1 FOR 2)=SUBSTRING(:ULTANIO FROM 3 FOR 2)
          INTO :NUMERO;
       END
       ELSE IF (COALESCE(CANT,0)=0) THEN BEGIN
          SELECT ULTNUM FROM TBLEQUIVA WHERE CARRE=:CARRE INTO :NUMERO;
          NUMERO=CAST(NUMERO AS INTEGER)+1;
          FNUMNUE='S';
       END
       NUM_ENTERO=LPAD(TRIM(NUMERO),13,'0')||LPAD(TRIM(SUBSTRING(:ULTANIO FROM 3 FOR 2)),2,'0');
       NUM_FORMA=LPAD(TRIM(NUMERO),13,'0')||'/'||LPAD(TRIM(SUBSTRING(:ULTANIO FROM 3 FOR 2)),2,'0');
  END
  ELSE BEGIN
       SELECT ANIO FROM TBLEQUIVA WHERE CARRE='TER' INTO :ULTANIO;
       IF (ULTANIO<>EXTRACT(YEAR FROM CURRENT_DATE)) THEN
           UPDATE TBLEQUIVA SET ANIO=EXTRACT(YEAR FROM CURRENT_DATE), ULTNUM=0 WHERE CARRE='TER';
       /*SELECT ULTNUM FROM TBLEQUIVA WHERE CARRE='TER' INTO :NUMERO;
       NUMERO=CAST(NUMERO AS INTEGER)+1;
       FNUMNUE='S';
       NUM_ENTERO=LPAD(TRIM(NUMERO),13,'0')||LPAD(TRIM(SUBSTRING(:ULTANIO FROM 3 FOR 2)),2,'0');
       NUM_FORMA=LPAD(TRIM(NUMERO),13,'0')||'/'||LPAD(TRIM(SUBSTRING(:ULTANIO FROM 3 FOR 2)),2,'0');*/
       CANT=NULL;
       SELECT COUNT(DISTINCT C.ACTINT)
       FROM ANALITIC C
       WHERE C.COD_ALU=:CODALU AND C.CARRE=:CARRE AND C.CONDICION='EQUIVALENCIA' AND
             SUBSTRING(C.ACTINT FROM CHAR_LENGTH(C.ACTINT)-1 FOR 2)=SUBSTRING(:ULTANIO FROM 3 FOR 2)
       INTO :CANT;
       IF (COALESCE(CANT,0)>1) THEN BEGIN
          FERRMSG='El alumno tiene dos numeros de actuacion interna se tomara la mas reciente';
          SELECT MAX(SUBSTRING(C.ACTINT FROM 1 FOR CHAR_LENGTH(C.ACTINT)-2))
          FROM ANALITIC C
          WHERE C.COD_ALU=:CODALU AND C.CARRE=:CARRE AND C.CONDICION='EQUIVALENCIA' AND
                SUBSTRING(C.ACTINT FROM CHAR_LENGTH(C.ACTINT)-1 FOR 2)=SUBSTRING(:ULTANIO FROM 3 FOR 2)
          INTO :NUMERO;
       END
       ELSE IF (COALESCE(CANT,0)=1) THEN BEGIN
          SELECT MAX(SUBSTRING(TRIM(ACTINT) FROM 1 FOR CHAR_LENGTH(TRIM(ACTINT))-2))
          FROM ANALITIC C
          WHERE C.COD_ALU=:CODALU AND C.CARRE=:CARRE AND C.CONDICION='EQUIVALENCIA' AND
                SUBSTRING(C.ACTINT FROM CHAR_LENGTH(C.ACTINT)-1 FOR 2)=SUBSTRING(:ULTANIO FROM 3 FOR 2)
          INTO :NUMERO;
       END
       ELSE IF (COALESCE(CANT,0)=0) THEN BEGIN
          SELECT ULTNUM FROM TBLEQUIVA WHERE CARRE='TER' INTO :NUMERO;
          NUMERO=CAST(NUMERO AS INTEGER)+1;
          FNUMNUE='S';
       END
       NUM_ENTERO=LPAD(TRIM(NUMERO),13,'0')||LPAD(TRIM(SUBSTRING(:ULTANIO FROM 3 FOR 2)),2,'0');
       NUM_FORMA=LPAD(TRIM(NUMERO),13,'0')||'/'||LPAD(TRIM(SUBSTRING(:ULTANIO FROM 3 FOR 2)),2,'0');
  END
  SUSPEND;
end ^

SET TERM ; ^
