SET TERM ^ ;

ALTER PROCEDURE XXX_COPIA_ALUMNO (CARDDE VARCHAR(6) CHARACTER SET NONE,
CARHTA VARCHAR(6) CHARACTER SET NONE,
COD_ALU VARCHAR(11) CHARACTER SET NONE,
CODUSU INTEGER)
RETURNS (FERRCOD INTEGER,
FERRMSG VARCHAR(300) CHARACTER SET NONE)
AS 
declare variable NOMBRE varchar(100);
begin
  SELECT TRIM(A.APELLIDO)||', '||TRIM(A.NOM_APE)
  FROM ALUMNOS A
  WHERE A.COD_ALU=:COD_ALU AND A.CARRE=:CARDDE
  INTO :NOMBRE;

  FERRCOD=1;
  FERRMSG='El Alumno '||NOMBRE||' fue copiado a la carrera '||CARHTA||', Confirma?';

  IF (EXISTS(SELECT 1 FROM ALUMNOS A WHERE A.COD_ALU=:COD_ALU AND A.CARRE=:CARHTA AND A.BAJA='N')) THEN BEGIN
     FERRCOD=2;
     FERRMSG='El alumno ya existe en Altas de la carrera: '||CARHTA;
     SUSPEND;
     EXIT;
  END
  ELSE IF (EXISTS(SELECT 1 FROM ALUMNOS A WHERE A.COD_ALU=:COD_ALU AND A.CARRE=:CARHTA AND A.BAJA='S')) THEN BEGIN
     FERRCOD=2;
     FERRMSG='El alumno ya existe en Bajas de la carrera: '||CARHTA;
     SUSPEND;
     EXIT;
  END
  INSERT INTO ALUMNOS (COD_ALU, CARRE, MATRIZ, APELLIDO, NOM_APE, EXT_POR,
                       SEXO, NACIONAL, EST_CIV, FEC_NAC, LUG_NAC, PCIA_NAC,
                       DOMI, LOCALI, COD_POS, CAR_TEL, TELE, FEC_ING, CPRIM,
                       APRIM, TPRIM, OPRIM, CSECU, ASECU, TSECU, OSECU,
                       TERCI, ATERCI, TTERCI, OTERCI, UNIVER, AUNIVER,
                       TUNIVER, OUNIVER, ESPEC, AESPEC, TESPEC, OESPEC,
                       EMPRE, RUBRO, CARGO, ANTI, DOMI_1, TELE_1, INTER,
                       MOROSO, MORO1, MORO2, MORO3, F_MORO, PN, CTT,
                       FECH_CTT, DNI, CD, CA, RESIDE, CR, BAJA, INDICE,
                       MAIL, OBSERV, USUARIO, CELULAR, FFOTO, FAPTFIS,
                       FAPTFEC, FUSUWEB, FOTO, FPARNAC, ULTMOD)
                SELECT COD_ALU, :CARHTA, NULL, APELLIDO, NOM_APE, EXT_POR,
                       SEXO, NACIONAL, EST_CIV, FEC_NAC, LUG_NAC, PCIA_NAC,
                       DOMI, LOCALI, COD_POS, CAR_TEL, TELE, FEC_ING, CPRIM,
                       APRIM, TPRIM, OPRIM, CSECU, ASECU, TSECU, OSECU,
                       TERCI, ATERCI, TTERCI, OTERCI, UNIVER, AUNIVER,
                       TUNIVER, OUNIVER, ESPEC, AESPEC, TESPEC, OESPEC,
                       EMPRE, RUBRO, CARGO, ANTI, DOMI_1, TELE_1, INTER,
                       MOROSO, MORO1, MORO2, MORO3, F_MORO, PN, NULL,
                       FECH_CTT, DNI, CD, CA, RESIDE, CR, BAJA, INDICE,
                       MAIL, OBSERV, :CODUSU, CELULAR, FFOTO, FAPTFIS,
                       FAPTFEC, NULL, FOTO, FPARNAC, ULTMOD
                FROM ALUMNOS A
                WHERE COD_ALU=:COD_ALU AND A.CARRE=:CARDDE;
   SUSPEND;
end ^

SET TERM ; ^
