SET TERM ^ ;

ALTER PROCEDURE XXX_VALIDO_MESA (MESA INTEGER,
CARRE VARCHAR(6) CHARACTER SET NONE)
RETURNS (ERRMSG VARCHAR(100) CHARACTER SET NONE,
ERRCOD INTEGER)
AS 
begin
  ERRMSG = '';
  ERRCOD = 0;
  IF (EXISTS (SELECT 1 FROM MESAS C WHERE C.MESA = :MESA AND C.CARRE = :CARRE)) THEN
    begin
       ERRMSG = 'La mesa ya existe para esa carrera.';
       ERRCOD = 2;
    end
  SUSPEND;
End ^

SET TERM ; ^
