SET TERM ^ ;

ALTER PROCEDURE XXX_FALTAS_IMPRESI (CARRE VARCHAR(6) CHARACTER SET NONE,
CUATRIM VARCHAR(3) CHARACTER SET NONE,
CUAANIO VARCHAR(3) CHARACTER SET NONE,
REINPRI VARCHAR(10) CHARACTER SET NONE,
REINSEG VARCHAR(10) CHARACTER SET NONE,
LIBRE VARCHAR(10) CHARACTER SET NONE)
RETURNS (COD_ALU VARCHAR(11) CHARACTER SET NONE,
NOMBRE VARCHAR(80) CHARACTER SET NONE,
CUTUCO INTEGER,
INAJUS NUMERIC(5, 2),
INAINJUS NUMERIC(5, 2),
INATAR NUMERIC(5, 2),
INAEDFIS NUMERIC(5, 2),
INATOT NUMERIC(5, 2),
PRISEG VARCHAR(20) CHARACTER SET NONE,
FECHA DATE,
ACTDISC INTEGER)
AS 
DECLARE VARIABLE DDEPRI DATE;
DECLARE VARIABLE HTATER DATE;
DECLARE VARIABLE CONT NUMERIC(5,2);
DECLARE VARIABLE CANTID NUMERIC(5,2);
begin
  REINPRI=REPLACE(REINPRI,',','.');
  REINSEG=REPLACE(REINSEG,',','.');
  LIBRE=REPLACE(LIBRE,',','.');
  SELECT FDDEPRI, FHTATER
  FROM TBL_TRIM
  WHERE FANIO=EXTRACT(YEAR FROM CAST('01/01/'||SUBSTRING(:CUAANIO FROM 2 FOR 2) AS DATE))
  INTO :DDEPRI, :HTATER;
  IF (CUATRIM='') THEN CUATRIM='0';
  FOR
     SELECT DISTINCT A.COD_ALU, SUBSTRING(TRIM(A.APELLIDO)||','||TRIM(A.NOM_APE) FROM 1 FOR 80), C.CUTUCO
     FROM CURSADA C
     LEFT OUTER JOIN ALUMNOS A ON C.COD_ALU=A.COD_ALU AND A.CARRE=C.CARRE
     WHERE C.CARRE=:CARRE AND (C.CUTUCO=:CUATRIM OR :CUATRIM=0) AND C.CUA_ANIO=:CUAANIO
           AND A.BAJA='N' AND CONDICION='CURSANDO'
     ORDER BY 3,1
     INTO :COD_ALU, :NOMBRE, :CUTUCO
     DO BEGIN
         INAJUS=NULL;
         INAINJUS=NULL;
         INATAR=NULL;
         INATOT=NULL;
         ACTDISC=NULL;
         INAEDFIS=NULL;
         SELECT SUM(F.CANFAL)
         FROM FALTAS F
         LEFT OUTER JOIN TBL_FALTAS T ON F.CODFAL=T.FCODIGO
         WHERE F.CARRERA=:CARRE AND F.CODALU=:COD_ALU AND F.CUTUCO=:CUTUCO AND F.FECHA BETWEEN :DDEPRI AND :HTATER
               AND T.FJUSTIF='S' --AND T.FTIPO='AA'
         INTO :INAJUS;
         SELECT SUM(F.CANFAL)
         FROM FALTAS F
         LEFT OUTER JOIN TBL_FALTAS T ON F.CODFAL=T.FCODIGO
         WHERE F.CARRERA=:CARRE AND F.CODALU=:COD_ALU AND F.CUTUCO=:CUTUCO AND F.FECHA BETWEEN :DDEPRI AND :HTATER
               AND T.FJUSTIF='N' AND T.FTIPO='AA'
         INTO :INAINJUS;
         SELECT SUM(F.CANFAL)
         FROM FALTAS F
         LEFT OUTER JOIN TBL_FALTAS T ON F.CODFAL=T.FCODIGO
         WHERE F.CARRERA=:CARRE AND F.CODALU=:COD_ALU AND F.CUTUCO=:CUTUCO AND F.FECHA BETWEEN :DDEPRI AND :HTATER
               AND T.FJUSTIF='N' AND T.FTIPO='TT'
         INTO :INATAR;

         SELECT SUM(F.CANFAL)
         FROM FALTAS F
         LEFT OUTER JOIN TBL_FALTAS T ON F.CODFAL=T.FCODIGO
         WHERE F.CARRERA=:CARRE AND F.CODALU=:COD_ALU AND F.CUTUCO=:CUTUCO AND F.FECHA BETWEEN :DDEPRI AND :HTATER
               AND T.FJUSTIF='N' AND T.FTIPO='EF'
         INTO :INAEDFIS;

         SELECT COUNT(*)
         FROM ACTAS_DISC D
         WHERE D.COD_ALU=:COD_ALU AND D.CARRE=:CARRE AND D.FECHA BETWEEN :DDEPRI AND :HTATER
         INTO :ACTDISC;

         ACTDISC=COALESCE(ACTDISC,0);
         INAJUS=COALESCE(INAJUS,0);
         INAINJUS=COALESCE(INAINJUS,0);
         INATAR=COALESCE(INATAR,0);
         INAEDFIS=COALESCE(INAEDFIS,0);
         INATOT=INAJUS+INAINJUS+INATAR+INAEDFIS;

         PRISEG='';
         CONT=0;
         CANTID=0;
         IF (INATOT>=REINPRI AND INATOT<REINSEG) THEN BEGIN
            PRISEG='por primera vez';
            FOR SELECT F.CANFAL,F.FECHA
                FROM FALTAS F
                LEFT OUTER JOIN TBL_FALTAS T ON F.CODFAL=T.FCODIGO
                WHERE F.CARRERA=:CARRE AND F.CODALU=:COD_ALU AND F.CUTUCO=:CUTUCO AND F.FECHA BETWEEN :DDEPRI AND :HTATER
                ORDER BY 2
                INTO :CANTID,:FECHA
                DO BEGIN
                   CONT=CONT+CANTID;
                   IF (CONT>=REINPRI) THEN
                      BREAK;
                END
         END
         ELSE IF (INATOT>=REINSEG AND INATOT<LIBRE) THEN BEGIN
            PRISEG='por segunda vez';
            FOR SELECT F.CANFAL,F.FECHA
                FROM FALTAS F
                LEFT OUTER JOIN TBL_FALTAS T ON F.CODFAL=T.FCODIGO
                WHERE F.CARRERA=:CARRE AND F.CODALU=:COD_ALU AND F.CUTUCO=:CUTUCO AND F.FECHA BETWEEN :DDEPRI AND :HTATER
                ORDER BY 2
                INTO :CANTID,:FECHA
                DO BEGIN
                   CONT=CONT+CANTID;
                   IF (CONT>=REINSEG) THEN
                      BREAK;
                END
         END
         ELSE IF (INATOT>=LIBRE) THEN BEGIN
            PRISEG='libre';
            FOR SELECT F.CANFAL,F.FECHA
                FROM FALTAS F
                LEFT OUTER JOIN TBL_FALTAS T ON F.CODFAL=T.FCODIGO
                WHERE F.CARRERA=:CARRE AND F.CODALU=:COD_ALU AND F.CUTUCO=:CUTUCO AND F.FECHA BETWEEN :DDEPRI AND :HTATER
                ORDER BY 2
                INTO :CANTID,:FECHA
                DO BEGIN
                   CONT=CONT+CANTID;
                   IF (CONT>=LIBRE) THEN
                      BREAK;
                END
         END
         IF (PRISEG<>'') THEN
             SUSPEND;
     END
end ^

SET TERM ; ^
