SET TERM ^ ;

ALTER PROCEDURE XXX_CAMBIA_DNI_LM (CODALU CHAR(11) CHARACTER SET NONE,
LM CHAR(5) CHARACTER SET NONE,
N_CODALU CHAR(11) CHARACTER SET NONE,
TIPO CHAR(1) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE)
RETURNS (FERRCOD INTEGER,
FERRMSG VARCHAR(100) CHARACTER SET NONE)
AS 
DECLARE VARIABLE ALUMNO VARCHAR(40);
begin
  FERRCOD=0;
  FERRMSG='';
  --TIPO: L: LIBRO MATRIZ D:CODIGO DE ALUMNO
  IF (TIPO='L') THEN
    BEGIN
      IF (EXISTS (SELECT 1 FROM ALUMNOS A WHERE CARRE=:CARRE AND TRIM(MATRIZ)=TRIM(:LM))) THEN
        BEGIN
          SELECT TRIM(APELLIDO)||','||TRIM(NOM_APE)||'-'||CASE BAJA WHEN 'S' THEN 'Baja' ELSE '' END FROM ALUMNOS WHERE CARRE=:CARRE AND TRIM(MATRIZ)=TRIM(:LM) INTO :ALUMNO;
          FERRCOD=2;
          FERRMSG='El libro matriz pertenece a otro alumno: '||ALUMNO;
        End
      ELSE BEGIN
         UPDATE ALUMNOS A SET A.MATRIZ=:LM WHERE A.COD_ALU=:CODALU AND A.CARRE=:CARRE;
         UPDATE ANALITIC A SET A.MATRIZ=:LM WHERE A.COD_ALU=:CODALU AND A.CARRE=:CARRE;
         UPDATE CURSADA A SET A.MATRIZ=:LM WHERE A.COD_ALU=:CODALU AND A.CARRE=:CARRE;
         UPDATE RECURSA A SET A.MATRIZ=:LM WHERE A.COD_ALU=:CODALU AND A.CARRE=:CARRE;
         FERRMSG='Se cambio el libro matriz';
      END
    END
  IF (TIPO='D') THEN
    BEGIN
      IF (EXISTS (SELECT 1 FROM ALUMNOS A WHERE A.COD_ALU=:N_CODALU AND CARRE=:CARRE)) THEN
        BEGIN
          SELECT TRIM(APELLIDO)||','||TRIM(NOM_APE)||'-'||CASE BAJA WHEN 'S' THEN 'Baja' ELSE '' END FROM ALUMNOS WHERE COD_ALU=:N_CODALU AND CARRE=:CARRE INTO :ALUMNO;
          FERRCOD=2;
          FERRMSG='El documento pertenece a otro alumno: '||ALUMNO;
        End
      ELSE BEGIN
         UPDATE ALUMNOS A SET A.COD_ALU=:N_CODALU WHERE A.COD_ALU=:CODALU AND A.CARRE=:CARRE;
         UPDATE ANALITIC A SET A.COD_ALU=:N_CODALU WHERE A.COD_ALU=:CODALU AND A.CARRE=:CARRE;
         UPDATE CURSADA A SET A.COD_ALU=:N_CODALU WHERE A.COD_ALU=:CODALU AND A.CARRE=:CARRE;
         UPDATE RECURSA A SET A.COD_ALU=:N_CODALU WHERE A.COD_ALU=:CODALU AND A.CARRE=:CARRE;
         FERRMSG='Se cambio el Codigo de alumno';
      END
    END
  suspend;
end ^

SET TERM ; ^
