SET TERM ^ ;

ALTER PROCEDURE XXX_ADM_IMP_CUOTA_DET (TIPO CHAR(1) CHARACTER SET NONE,
INDDDE INTEGER,
INDHTA INTEGER)
RETURNS (CONCEPTO VARCHAR(100) CHARACTER SET NONE,
MONTO DOUBLE PRECISION,
SUBTOT DOUBLE PRECISION,
INDICE INTEGER,
ITM INTEGER)
AS 
begin

  ITM=0;
  FOR
  SELECT COALESCE(I.DESCRI, C.DESCRI), I.MONTO, I.INDICE, I.ITEM
  FROM ADM_CUOT_DATO D
  LEFT OUTER JOIN ADM_CUOT_ITEM I ON D.INDICE=I.INDICE
  LEFT OUTER JOIN TBL_ADM_CONC C ON C.CODIGO=I.CONCEP
  WHERE D.INDICE BETWEEN :INDDDE AND :INDHTA AND D.TIPO=:TIPO
  INTO :CONCEPTO, :MONTO, :INDICE, :ITM
  DO BEGIN
    --ITM=ITM+1;
    SUSPEND;
  END


end ^

SET TERM ; ^
