SET TERM ^ ;

ALTER PROCEDURE XXX_EGRESADOS (CARRE VARCHAR(6) CHARACTER SET NONE,
DDE DATE,
HTA DATE)
RETURNS (COD_ALU VARCHAR(13) CHARACTER SET NONE,
NOMBRE VARCHAR(100) CHARACTER SET NONE,
FECHA DATE,
PROMEDIO NUMERIC(5, 2),
FECNAC DATE,
LUGARNAC VARCHAR(100) CHARACTER SET NONE,
MATRIZ VARCHAR(10) CHARACTER SET NONE,
TITULO VARCHAR(80) CHARACTER SET NONE)
AS 
DECLARE VARIABLE FERRCOD INTEGER;
DECLARE VARIABLE CUATRI SMALLINT;
DECLARE VARIABLE CUATRIM SMALLINT;
BEGIN
FOR
SELECT A.COD_ALU, TRIM(S.APELLIDO)||', '||TRIM(S.NOM_APE),
       S.FEC_NAC, S.MATRIZ, S.LUG_NAC, MAX(FEC_FINAL), M.CUATRIM
FROM ANALITIC A
LEFT OUTER JOIN ALUMNOS S ON S.COD_ALU=A.COD_ALU AND S.CARRE=A.CARRE
LEFT OUTER JOIN MATERIAS M ON M.CODCARRE=A.CARRE AND A.COD_MAT=M.CODMATERI
WHERE A.CARRE=:CARRE AND
      A.FEC_FINAL BETWEEN :DDE AND :HTA AND S.BAJA='N'
GROUP BY A.COD_ALU, TRIM(S.APELLIDO),TRIM(S.NOM_APE), A.CARRE,
       S.FEC_NAC, S.MATRIZ, S.LUG_NAC, M.CUATRIM
ORDER BY 2,M.CUATRIM
INTO :COD_ALU, :NOMBRE, :FECNAC, :MATRIZ, :LUGARNAC, :FECHA, :CUATRIM
DO BEGIN
   FERRCOD=NULL;
   PROMEDIO=NULL;
   SELECT Z.FERRCOD, FCUATRI FROM XXX_IMPRIME_CTT(:COD_ALU, :CARRE) Z INTO :FERRCOD, :CUATRI;
   IF (COALESCE(FERRCOD,0)<>2 AND CUATRIM<=CUATRI) THEN BEGIN
      TITULO=NULL;
      SELECT SUBSTRING(DESCARRE FROM 1 FOR 70) FROM CARRERA WHERE CARRE=:CARRE AND CUATRIM=:CUATRI INTO :TITULO;
      IF (TITULO IS NULL) THEN
         SELECT SUBSTRING(DESCARRE2 FROM 1 FOR 70) FROM CARRERA WHERE CARRE=:CARRE AND CUATRIM2=:CUATRI INTO :TITULO;
      --SELECT MAX(FEC_FINAL) FROM ANALITIC WHERE CARRE=:CARRE AND COD_ALU=:COD_ALU INTO :FECHA;
      SELECT PROMGRAL FROM XXX_PROMEDIO_GRAL(:COD_ALU, :CARRE) INTO :PROMEDIO;
      SUSPEND;
   END
END
END ^

SET TERM ; ^
