SET TERM ^ ;

ALTER PROCEDURE XXX_VALIDO_COMISION (CUAANIO VARCHAR(3) CHARACTER SET NONE,
CODMAT VARCHAR(2) CHARACTER SET NONE,
CUTUCO VARCHAR(3) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE)
RETURNS (ERRMSG VARCHAR(100) CHARACTER SET NONE,
ERRCOD INTEGER)
AS 
begin
  ERRMSG = '';
  ERRCOD = 0;
  IF (EXISTS (SELECT 1 FROM COMARM C WHERE C.CUA_ANIO = :CUAANIO AND C.CARRE = :CARRE AND C.COD_MAT = :CODMAT AND C.CUTUCO = :CUTUCO)) THEN
    begin
       ERRMSG = 'La comision ya existe para este cuatrimestre';
       ERRCOD = 2;
    end
  SUSPEND;
End ^

SET TERM ; ^
