SET TERM ^ ;

ALTER PROCEDURE XXX_FALTAS_FALTAS (CARRE VARCHAR(6) CHARACTER SET NONE,
CUTUCO INTEGER,
CUAANIO INTEGER,
CODALU VARCHAR(15) CHARACTER SET NONE,
CODMAT CHAR(2) CHARACTER SET NONE)
RETURNS (FECHA DATE,
CODFAL VARCHAR(2) CHARACTER SET NONE,
CANTID FLOAT,
DESCRI VARCHAR(30) CHARACTER SET NONE)
AS 
declare variable DDE date;
declare variable HTA date;
declare variable FDDEPRI date;
declare variable FHTAPRI date;
declare variable FDDESEG date;
declare variable FHTASEG date;
declare variable FDDETER date;
declare variable FHTATER date;
begin

  IF (CARRE IN ('333','650') ) THEN BEGIN
    SELECT FDDEPRI,FHTATER
    FROM TBL_TRIM
    WHERE FANIO='20'||SUBSTRING(:CUAANIO FROM 2)
    INTO :DDE, :HTA;

    FOR SELECT F.CODFAL, F.CANFAL, T.FDESCRI, F.FECHA
    FROM FALTAS F
    LEFT OUTER JOIN TBL_FALTAS T ON T.FCODIGO=F.CODFAL
    WHERE F.CARRERA=:CARRE AND F.CODALU=:CODALU AND (:cutuco is null or F.CUTUCO=:CUTUCO) AND F.FECHA BETWEEN :DDE AND :HTA AND F.COD_MAT IS NULL
    INTO :CODFAL,:CANTID, :DESCRI, :FECHA
    DO
      SUSPEND;
  END
  ELSE BEGIN
    SELECT FDDEPRI, FHTAPRI, FDDESEG, FHTASEG
    FROM TBL_CUAT
    WHERE FANIO='20'||SUBSTRING(:CUAANIO FROM 2)
    INTO :FDDEPRI, :FHTAPRI, :FDDESEG, :FHTASEG;

    IF (SUBSTRING(CUAANIO FROM 1 FOR 1)='1') THEN BEGIN
        DDE=FDDEPRI;
        HTA=FHTAPRI;
    END
    ELSE BEGIN
        DDE=FDDESEG;
        HTA=FHTASEG;
    END
    FOR SELECT F.CODFAL, F.CANFAL, T.FDESCRI, F.FECHA
    FROM FALTAS F
    LEFT OUTER JOIN TBL_FALTAS T ON T.FCODIGO=F.CODFAL
    WHERE F.CARRERA=:CARRE AND F.CODALU=:CODALU AND F.CUTUCO=:CUTUCO AND F.FECHA BETWEEN :DDE AND :HTA AND F.COD_MAT=:CODMAT
    INTO :CODFAL,:CANTID, :DESCRI, :FECHA
    DO
      SUSPEND;
  END


end ^

SET TERM ; ^
