SET TERM ^ ;

ALTER PROCEDURE XXX_ADM_OBSERV_PANTA (XINDICE INTEGER,
CARRE VARCHAR(3) CHARACTER SET NONE)
RETURNS (DATOS VARCHAR(1000) CHARACTER SET NONE,
INDICE INTEGER,
FMENSAJE VARCHAR(200) CHARACTER SET NONE,
FCOLOR INTEGER,
OBSERV BLOB CHARACTER SET NONE)
AS 
DECLARE VARIABLE CTT CHAR(1);
DECLARE VARIABLE CA CHAR(1);
DECLARE VARIABLE DNI CHAR(1);
DECLARE VARIABLE FECH_CTT DATE;
DECLARE VARIABLE FOTO CHAR(1);
DECLARE VARIABLE APTFIS CHAR(1);
DECLARE VARIABLE APTFEC DATE;
begin
  FMENSAJE='';
  FCOLOR=0;  --BLANCO

  INDICE=XINDICE;

  SELECT F.OBSERV
  FROM ALUMNOS A
  LEFT OUTER JOIN ADM_ALUMNOS_OBSERV F ON F.COD_ALU=A.COD_ALU AND F.CARRE=A.CARRE
  WHERE A.INDICE=:INDICE
  ORDER BY F.INDICE DESC
  ROWS 1 TO 1
  INTO :OBSERV;
  SUSPEND;
end ^

SET TERM ; ^
