SET TERM ^ ;

ALTER PROCEDURE XXX_FALTAS_PASLIBRE (CODALU VARCHAR(15) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE)
RETURNS (ERRCOD INTEGER,
ERRMSG VARCHAR(1000) CHARACTER SET NONE)
AS 
begin
  ERRCOD=1;
  ERRMSG='Esta seguro de pasar todas las materias del alumno a LIBRE?';--||CODALU||CARRE;

  UPDATE CURSADA SET CONDICION='LIBRES' WHERE COD_ALU=:CODALU AND CARRE=:CARRE AND CONDICION='CURSANDO';

  SUSPEND;
end ^

SET TERM ; ^
