SET TERM ^ ;

ALTER PROCEDURE XXX_INS_BUSCADOR_MATERIAS (CARRE VARCHAR(6) CHARACTER SET NONE,
CODALU VARCHAR(11) CHARACTER SET NONE)
RETURNS (CODMATERI VARCHAR(2) CHARACTER SET NONE,
DESCRIPCI VARCHAR(60) CHARACTER SET NONE)
AS 
begin
  FOR SELECT M.CODMATERI, M.DESCRIPCI
  FROM MATERIAS M
  WHERE M.CODCARRE=:CARRE AND M.ESTADO<>'B'
  INTO :CODMATERI, :DESCRIPCI
  DO BEGIN
     /*IF (NOT EXISTS(SELECT 1 FROM CURSADA C WHERE C.CARRE=:CARRE AND C.COD_ALU=:CODALU AND C.COD_MAT=:CODMATERI AND TRIM(C.CONDICION)<>'CURSANDO') AND
        NOT EXISTS(SELECT 1 FROM ANALITIC A WHERE A.CARRE=:CARRE AND A.COD_ALU=:CODALU AND A.COD_MAT=:CODMATERI)) THEN*/
       if (NOT EXISTS(SELECT 1 FROM ANALITIC A WHERE A.CARRE=:CARRE AND A.COD_ALU=:CODALU AND A.COD_MAT=:CODMATERI)) then
         SUSPEND;
  END
end ^

SET TERM ; ^
