SET TERM ^ ;

ALTER PROCEDURE XXX_PROMEDIO_GRAL (CODALU VARCHAR(11) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE)
RETURNS (PROMGRAL NUMERIC(5, 2))
AS 
begin
  SELECT AVG(COALESCE(A.NOTA_MAT,0))
  FROM ANALITIC A
  WHERE A.COD_ALU=:CODALU AND A.CARRE=:CARRE AND COALESCE(A.NOTA_MAT,0)<>0
  INTO :PROMGRAL;
  PROMGRAL=COALESCE(PROMGRAL,0);
  suspend;
end ^

SET TERM ; ^
