SET TERM ^ ;

ALTER PROCEDURE XXX_CARGA_SERTCERV (BLOQUE1 VARCHAR(20) CHARACTER SET NONE,
BLOQUE2 VARCHAR(20) CHARACTER SET NONE,
BLOQUE3 VARCHAR(20) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE)
RETURNS (HORAS INTEGER)
AS 
begin
  HORAS=0;
  IF (BLOQUE1 IN ('PRIMERO','SEGUNDO','TERCERO')) THEN
      HORAS=HORAS+2;
  ELSE IF (BLOQUE1='UNICO') THEN
         BEGIN
            IF (CARRE IN ('333','650')) THEN
               HORAS=HORAS+6;
            ELSE
               HORAS=HORAS+4;
         END
  ELSE IF (BLOQUE1 IN ('PRISEG','PRITER','TERSER')) THEN
             HORAS=HORAS+4;

  IF (BLOQUE2 IN ('PRIMERO','SEGUNDO','TERCERO')) THEN
        HORAS=HORAS+2;
  ELSE IF (BLOQUE2='UNICO') THEN
          BEGIN
            IF (CARRE IN ('333','650')) THEN
                HORAS=HORAS+6;
            ELSE
                HORAS=HORAS+4;
          END
  ELSE IF (BLOQUE2 IN ('PRISEG','PRITER','TERSER')) THEN
             HORAS=HORAS+4;

  IF (BLOQUE3 IN ('PRIMERO','SEGUNDO','TERCERO')) THEN
        HORAS=HORAS+2;
  ELSE IF (BLOQUE3='UNICO') THEN
         BEGIN
              IF (CARRE IN ('333','650')) THEN
                 HORAS=HORAS+6;
              ELSE
                 HORAS=HORAS+4;
            END
  ELSE IF (BLOQUE3 IN ('PRISEG','PRITER','TERSER')) THEN
            HORAS=HORAS+4;
SUSPEND;
end ^

SET TERM ; ^
