SET TERM ^ ;

ALTER PROCEDURE XXX_ADM_ADD_CUOTA (CUOTA CHAR(3) CHARACTER SET NONE,
VEN1FEC DATE,
VEN2FEC DATE,
VEN3FEC DATE,
VEN4FEC DATE,
ALUMNO INTEGER,
TIPO CHAR(1) CHARACTER SET NONE)
RETURNS (ERRCOD INTEGER,
ERRMSG VARCHAR(300) CHARACTER SET NONE)
AS 
DECLARE VARIABLE VEN1MON NUMERIC(9,2);
DECLARE VARIABLE VEN2MON NUMERIC(9,2);
DECLARE VARIABLE VEN3MON NUMERIC(9,2);
DECLARE VARIABLE VEN4MON NUMERIC(9,2);
DECLARE VARIABLE INDICE INTEGER;
DECLARE VARIABLE INDCTA INTEGER;
DECLARE VARIABLE TOTAL DOUBLE PRECISION;
DECLARE VARIABLE MAXITEM INTEGER;
DECLARE VARIABLE MONTO DOUBLE PRECISION;
DECLARE VARIABLE DR_CONCEP VARCHAR(80);
DECLARE VARIABLE DR_PORCEN DOUBLE PRECISION;
DECLARE VARIABLE DR_TIPO CHAR(1);
DECLARE VARIABLE TOTAPLDES DOUBLE PRECISION;
begin
   ERRCOD=0;
   ERRMSG='';

   SELECT INDICE, VENCIM1, VENCIM2, VENCIM3, VENCIM4
   FROM XXX_ADM_CUOT_POLITICA(:ALUMNO, :TIPO)
   INTO :INDCTA, :VEN1MON, :VEN2MON, :VEN3MON, :VEN4MON;

   IF (INDCTA IS NULL) THEN BEGIN
     ERRCOD=2;
     ERRMSG='No hay politica de cuota para la configuracion de este alumno' ;
     SUSPEND;
     EXIT;
   END

   INDICE=GEN_ID(G_ADM_CUOT_DATO,1);
   INSERT INTO ADM_CUOT_DATO (INDICE, ALUMNO, CUOTA, ANIO, FECHA, ESTADO, TIPO, VEN1FEC, VEN2FEC, VEN3FEC, VEN4FEC, VEN1MON, VEN2MON, VEN3MON, VEN4MON, TOTAL, TOTPAG)
   VALUES (:INDICE, :ALUMNO, :CUOTA, EXTRACT(YEAR FROM CURRENT_DATE), CURRENT_DATE, '0', :TIPO, :VEN1FEC, :VEN2FEC, :VEN3FEC, :VEN4FEC, :VEN1MON, :VEN2MON, :VEN3MON, :VEN4MON, 0, 0);

   INSERT INTO ADM_CUOT_ITEM (INDICE, ITEM, CONCEP, DESCRI, MONTO, VENCIM, CONDES, CONREC)
   SELECT :INDICE, I.ITEM, I.CONCEP, NULL, I.MONTO, 'N', I.APLDES, I.APLREC
   FROM TBL_ADM_ICUOT I
   WHERE I.INDICE=:INDCTA;

   -----TODO LO SIGUIENTE ES PARA CARGAR CONCEPTO S DESCUENTOS
   SELECT MAX(ITEM)
   FROM ADM_CUOT_ITEM
   WHERE INDICE=:INDICE
   INTO :MAXITEM;

   SELECT SUM(I.MONTO)
   FROM ADM_CUOT_ITEM I
   WHERE I.INDICE=:INDICE AND I.CONDES='S'
   INTO :TOTAPLDES;

   IF (COALESCE(TOTAPLDES,0)>0) THEN BEGIN
       FOR SELECT D.PORCEN, T.DESCRI
       FROM ALUMNOS A
       LEFT OUTER JOIN ADM_ALUMNOS_DERE D ON D.COD_ALU=A.COD_ALU AND D.CARRE=A.CARRE
       LEFT OUTER JOIN TBL_ADM_DERE T ON T.CODIGO=D.CONCEP
       WHERE A.INDICE=:ALUMNO AND :VEN1FEC BETWEEN D.DDE AND D.HTA AND D.TIPO='D'
       INTO :DR_PORCEN, :DR_CONCEP
       DO BEGIN
           MAXITEM=MAXITEM+1;
    
           MONTO=(TOTAPLDES*(DR_PORCEN/100))*(-1);

           IF (MONTO<>0) THEN
              INSERT INTO ADM_CUOT_ITEM (INDICE, ITEM, CONCEP, DESCRI, MONTO, VENCIM, CONDES)
              VALUES(:INDICE,:MAXITEM,-2,:DR_CONCEP,:MONTO,'N','N');
    
       END
    END
   --*********************************************************
   -----TODO LO SIGUIENTE ES PARA CARGAR CONCEPTO S /RECARGOS
   TOTAPLDES=0;

   SELECT MAX(ITEM)
   FROM ADM_CUOT_ITEM
   WHERE INDICE=:INDICE
   INTO :MAXITEM;

   SELECT SUM(I.MONTO)
   FROM ADM_CUOT_ITEM I
   WHERE I.INDICE=:INDICE AND I.CONREC='S'
   INTO :TOTAPLDES;

   IF (COALESCE(TOTAPLDES,0)>0) THEN BEGIN
       FOR SELECT  D.PORCEN, T.DESCRI
       FROM ALUMNOS A
       LEFT OUTER JOIN ADM_ALUMNOS_DERE D ON D.COD_ALU=A.COD_ALU AND D.CARRE=A.CARRE
       LEFT OUTER JOIN TBL_ADM_DERE T ON T.CODIGO=D.CONCEP
       WHERE A.INDICE=:ALUMNO AND :VEN1FEC BETWEEN D.DDE AND D.HTA AND D.TIPO='R'
       INTO :DR_PORCEN, :DR_CONCEP
       DO BEGIN
           MAXITEM=MAXITEM+1;
    
           MONTO=TOTAPLDES*(DR_PORCEN/100);

           IF (MONTO<>0) THEN
              INSERT INTO ADM_CUOT_ITEM (INDICE, ITEM, CONCEP, DESCRI, MONTO, VENCIM, CONDES)
              VALUES(:INDICE,:MAXITEM,-2,:DR_CONCEP,:MONTO,'N','N');
    
       END
    END
   --*********************************************************


   SELECT SUM(MONTO)
   FROM ADM_CUOT_ITEM
   WHERE INDICE=:INDICE
   INTO :TOTAL;

   UPDATE ADM_CUOT_DATO SET TOTAL=:TOTAL WHERE INDICE=:INDICE;

   SUSPEND;
end ^

SET TERM ; ^
