SET TERM ^ ;

ALTER PROCEDURE XXX_VENCIM_MAT (CUAANIO INTEGER)
RETURNS (VENCIM VARCHAR(20) CHARACTER SET NONE)
AS 
DECLARE VARIABLE ANIO INTEGER;
DECLARE VARIABLE CANIO INTEGER;
DECLARE VARIABLE CCUAT INTEGER;
DECLARE VARIABLE CONT INTEGER;
DECLARE VARIABLE ANIOS INTEGER;
begin
 CANIO=SUBSTRING(CUAANIO FROM 2 FOR 2); --SIEMPRE SE SUMA DOS ANIO
 CCUAT=SUBSTRING(CUAANIO FROM 1 FOR 1);

/* IF (CCUAT=1) THEN BEGIN
    CONT=2;
    VENCIM='DIC-';
 END
 ELSE BEGIN
    CONT=1;
    VENCIM='MAR-';
 END
 no importa si el alumno curso en 1/XX el llamado de julio/agosto o se cuenta
 */
 CONT=1;
 VENCIM='MAR-';
 ANIOS=TRUNC((8-CONT)/3,0);
 CANIO=CANIO+ANIOS;
 CONT=CONT+(ANIOS*3);
 IF (CONT=7) THEN
   CANIO=CANIO+1;
 VENCIM=VENCIM||CANIO;
 SUSPEND;
end ^

SET TERM ; ^
