SET TERM ^ ;

ALTER PROCEDURE XXX_FECHA_REGULARIZACION (CUAANIO VARCHAR(10) CHARACTER SET NONE)
RETURNS (FFECHA DATE)
AS 
begin

/*IF (EXTRACT(MONTH FROM CURRENT_DATE) BETWEEN 1 AND 7) THEN
     FFECHA='06/30/'||EXTRACT(YEAR FROM CURRENT_DATE);
ELSE
     FFECHA='11/30/'||EXTRACT(YEAR FROM CURRENT_DATE);
  */
SELECT IIF(SUBSTRING(:CUAANIO FROM 1 FOR 1)='1',T.FHTAPRI,T.FHTASEG)
FROM TBL_CUAT T
WHERE T.FANIO='20'||SUBSTRING(:CUAANIO FROM 2 FOR 2)
INTO :FFECHA;

SUSPEND;
end ^

SET TERM ; ^
