SET TERM ^ ;

ALTER PROCEDURE XXX_REGULARIZACION_MAT (CARRE VARCHAR(6) CHARACTER SET NONE,
CODALU VARCHAR(11) CHARACTER SET NONE,
CODMAT VARCHAR(2) CHARACTER SET NONE,
CONDICION VARCHAR(20) CHARACTER SET NONE,
USUARIO INTEGER)
RETURNS (FERRCOD INTEGER,
FERRMSG VARCHAR(3000) CHARACTER SET NONE)
AS 
declare variable TIPO varchar(3);
begin
SELECT TIPO FROM CARRERA  WHERE CARRE=:CARRE INTO :TIPO;
IF (TIPO='TER') THEN
   SELECT FERRCOD, FERRMSG FROM XXX_REGULARIZACION_MAT_TERC(:CARRE,:CODALU,:CODMAT,:CONDICION,:USUARIO) INTO :FERRCOD, :FERRMSG;
ELSE IF (CARRE IN ('333','650')) THEN
   SELECT FERRCOD, FERRMSG FROM XXX_REGULARIZACION_MAT_333(:CARRE,:CODALU,:CODMAT,:CONDICION,:USUARIO) INTO :FERRCOD, :FERRMSG;
ELSE IF (TIPO IN ('BAC','BAD')) THEN
   SELECT FERRCOD, FERRMSG FROM XXX_REGULARIZACION_MAT_BAC(:CARRE,:CODALU,:CODMAT,:CONDICION,:USUARIO) INTO :FERRCOD, :FERRMSG;
SUSPEND;
end ^

SET TERM ; ^
