SET TERM ^ ;

ALTER PROCEDURE XXX_ADM_CTACTE_CONCEP (XALUMNO INTEGER,
XINDICE INTEGER)
RETURNS (INDICE INTEGER,
ITEM INTEGER,
CONCEP INTEGER,
MONTO DOUBLE PRECISION,
DESCRIP VARCHAR(200) CHARACTER SET NONE,
VENCIM CHAR(1) CHARACTER SET NONE)
AS 
begin
FOR SELECT I.INDICE, I.ITEM, I.CONCEP, COALESCE(I.DESCRI, C.DESCRI), I.MONTO, I.VENCIM
FROM ADM_CUOT_ITEM I
LEFT OUTER JOIN TBL_ADM_CONC C ON C.CODIGO=I.CONCEP
WHERE I.INDICE=:XINDICE
INTO :INDICE, :ITEM, :CONCEP, :DESCRIP, :MONTO, :VENCIM
DO
  SUSPEND;
end ^

SET TERM ; ^
