SET TERM ^ ;

ALTER PROCEDURE XXX_ADM_IMP_RECIBOS_CAB (COMCOD VARCHAR(5) CHARACTER SET NONE,
INDDDE VARCHAR(8) CHARACTER SET NONE,
INDHTA VARCHAR(8) CHARACTER SET NONE)
RETURNS (NOMBRE VARCHAR(100) CHARACTER SET NONE,
DIRECCION VARCHAR(100) CHARACTER SET NONE,
RECIBO VARCHAR(20) CHARACTER SET NONE,
FECHA_EMI DATE,
FECHA_IMP DATE,
CURSO VARCHAR(150) CHARACTER SET NONE,
LETRAS VARCHAR(200) CHARACTER SET NONE,
CURSO2 VARCHAR(50) CHARACTER SET NONE,
CUOTA VARCHAR(50) CHARACTER SET NONE,
INDICE INTEGER,
TOTAL DOUBLE PRECISION,
COPIA VARCHAR(15) CHARACTER SET NONE)
AS 
DECLARE VARIABLE TEXTO VARCHAR(50);
DECLARE VARIABLE ANIO INTEGER;
begin
  FOR SELECT TRIM(A.APELLIDO)||','||TRIM(A.NOM_APE), A.DOMI||' '||A.LOCALI||' '||A.COD_POS,
             R.COMNUM, R.FECHAING, R.FECHAPAG,
             C.DESCRI,
             CA.DESCARRE,
             D.CUOTA,
             R.INDICE, R.MONTO, D.ANIO
  FROM REC_DATO R
  LEFT OUTER JOIN ADM_CUOT_DATO D ON R.ID_CUOTA=D.INDICE
  LEFT OUTER JOIN ALUMNOS A ON A.INDICE=R.ALUMNO
  LEFT OUTER JOIN TBL_ADM_CUR C ON C.CODIGO=A.ADMCURSO
  LEFT OUTER JOIN CARRERA CA ON CA.CARRE=C.CARRE
  WHERE R.COMCOD=:COMCOD AND R.COMNUM BETWEEN :INDDDE AND :INDHTA
  ORDER BY R.COMNUM
  INTO :NOMBRE, :DIRECCION, :RECIBO, :FECHA_EMI, :FECHA_IMP, :CURSO2, :CURSO, :CUOTA, :INDICE, :TOTAL, :ANIO
  DO BEGIN
    SELECT ' la cantidad en pesos '||LOWER(X.TEXTO)
    FROM ESCRIBE_MONEDA(0,:TOTAL) X
    INTO :LETRAS;

    IF (SUBSTRING(CUOTA FROM 1 FOR 1)='1') THEN
        TEXTO='Primer Semestre ';
    ELSE
        TEXTO='Segundo Semestre ';
    TEXTO=TEXTO||'Cuota '||SUBSTRING(CUOTA FROM 3 FOR 1)||' /'||ANIO;
    CUOTA=TEXTO;
    COPIA='Original';
    SUSPEND;
    COPIA='Duplicado';
    SUSPEND;
  END
end ^

SET TERM ; ^
