SET TERM ^ ;

ALTER PROCEDURE XXX_REGULARIZACION_MAT_TERC (CARRE VARCHAR(6) CHARACTER SET NONE,
CODALU VARCHAR(11) CHARACTER SET NONE,
CODMAT VARCHAR(2) CHARACTER SET NONE,
CONDIORG VARCHAR(20) CHARACTER SET NONE,
USUARIO INTEGER)
RETURNS (FERRCOD INTEGER,
FERRMSG VARCHAR(3000) CHARACTER SET NONE)
AS 
declare variable cutuco smallint;
declare variable cua_anio char(3);
declare variable condicion2 varchar(15);
declare variable condicion varchar(15);
declare variable tp_eva numeric(5,2);
declare variable recup numeric(5,2);
declare variable tp_eva2 numeric(5,2);
declare variable recup2 numeric(5,2);
declare variable regular numeric(5,2);
declare variable tot_horas smallint;
declare variable inasist smallint;
declare variable justif smallint;
declare variable final1 numeric(5,2);
declare variable fecha1 date;
declare variable final2 numeric(5,2);
declare variable fecha2 date;
declare variable apellido char(25);
declare variable matriz char(5);
declare variable nom_ape varchar(40);
declare variable tp_eva3 numeric(5,2);
declare variable prom numeric(5,2);
declare variable fec_eva1 date;
declare variable fec_eva2 date;
declare variable fec_eva3 date;
declare variable fal_eva1 numeric(5,2);
declare variable fal_eva2 numeric(5,2);
declare variable fal_eva3 numeric(5,2);
declare variable notadic numeric(5,2);
declare variable notamar numeric(5,2);
declare variable fechdic date;
declare variable fechmar date;
declare variable resulj numeric(5,2);
declare variable resuli numeric(5,2);
declare variable resul numeric(6,2);
declare variable promocion char(1);
declare variable notpromcion numeric(5,2);
declare variable aprsfinal varchar(1);
declare variable notaprsfinal numeric(5,2);
begin

SELECT TRIM(CONDICION)
FROM CURSADA
WHERE COD_ALU=:CODALU AND COD_MAT=:CODMAT AND CARRE=:CARRE
INTO :CONDICION2;

/*ESTA ASI PORQUE SI LO PONENE REINCORPORA PERO DESPUES LE QUITAN LAS FALTAS
Y TODAVIA NO LA APROBO PORQUE LE FALTA NOTAS LO PASABA A REGULAR*/
IF (CONDICION2='REINCORPORA') THEN
   CONDICION2='CURSANDO';

SELECT CUTUCO, CUA_ANIO, CONDICION, TP_EVA, RECUP, TP_EVA2,
       RECUP2, REGULAR, TOT_HORAS, INASIST, JUSTIF, FINAL1, FECHA1, FINAL2, FECHA2,
       APELLIDO, MATRIZ, NOM_APE, TP_EVA3, PROM, FEC_EVA1, FEC_EVA2, FEC_EVA3,
       FAL_EVA1, FAL_EVA2, FAL_EVA3, NOTADIC, NOTAMAR, FECHDIC, FECHMAR
FROM "$$$CURSADA" X
WHERE COD_ALU=:CODALU AND X.COD_MAT=:CODMAT AND X.USUARIO=:USUARIO
INTO :CUTUCO, :CUA_ANIO, :CONDICION, :TP_EVA, :RECUP, :TP_EVA2,
     :RECUP2, :REGULAR, :TOT_HORAS, :INASIST, :JUSTIF, :FINAL1, :FECHA1, :FINAL2, :FECHA2,
     :APELLIDO, :MATRIZ, :NOM_APE, :TP_EVA3, :PROM, :FEC_EVA1, :FEC_EVA2, :FEC_EVA3,
     :FAL_EVA1, :FAL_EVA2, :FAL_EVA3, :NOTADIC, :NOTAMAR, :FECHDIC, :FECHMAR;


IF (COALESCE(TP_EVA,0)=0 AND COALESCE(TP_EVA2,0)=0) THEN
   CONDICION=CONDICION2;--'CURSANDO';
IF (COALESCE(TP_EVA,0)<>0 AND COALESCE(TP_EVA2,0)=0) THEN
   CONDICION=CONDICION2;--'CURSANDO';
ELSE IF ((COALESCE(TP_EVA,0)=99 OR COALESCE(TP_EVA2,0)=99) AND COALESCE(RECUP,0)=0) THEN
   CONDICION=CONDICION2;--'CURSANDO';
ELSE IF ((COALESCE(TP_EVA,0)=99 OR COALESCE(TP_EVA2,0)=99) AND COALESCE(RECUP,0)=99) THEN
   CONDICION='RECURSA';
ELSE IF ((COALESCE(TP_EVA,0)=99 OR COALESCE(TP_EVA2,0)=99) AND COALESCE(RECUP,0) BETWEEN 4 AND 10) THEN
   CONDICION='REGULAR';
ELSE IF ((COALESCE(TP_EVA,0)=99 OR COALESCE(TP_EVA2,0)=99) AND COALESCE(RECUP,0)<4) THEN
   CONDICION='RECURSA';
ELSE IF ((COALESCE(TP_EVA,0) BETWEEN 0.1 AND 3.99 OR COALESCE(TP_EVA2,0) BETWEEN 0.1 AND 3.99) AND COALESCE(RECUP,0)=0) THEN
   CONDICION=CONDICION2;--'CURSANDO';
ELSE IF ((COALESCE(TP_EVA,0) BETWEEN 0.1 AND 3.99 OR COALESCE(TP_EVA2,0) BETWEEN 0.1 AND 3.99) AND COALESCE(RECUP,0)=99) THEN
   CONDICION='RECURSA';
ELSE IF ((COALESCE(TP_EVA,0) BETWEEN 0.1 AND 3.99 OR COALESCE(TP_EVA2,0) BETWEEN 0.1 AND 3.99) AND COALESCE(RECUP,0)<4) THEN
   CONDICION='RECURSA';   
ELSE IF ((COALESCE(TP_EVA,0) BETWEEN 0.1 AND 3.99 OR COALESCE(TP_EVA2,0) BETWEEN 0.1 AND 3.99) AND COALESCE(RECUP,0)>=4) THEN
   CONDICION='REGULAR';
ELSE IF (COALESCE(TP_EVA,0) BETWEEN 4 AND 10 AND COALESCE(TP_EVA2,0) BETWEEN 4 AND 10) THEN
   CONDICION='REGULAR';

    -- CALCULO DE FALTAS
    IF (TOT_HORAS > 0) THEN  BEGIN
         RESULJ= ROUND((JUSTIF * 100) / TOT_HORAS);
         RESULI= ROUND((INASIST * 100)/ TOT_HORAS);
         RESUL = RESULJ + RESULI;
    END
    ELSE IF (COALESCE(TOT_HORAS,0)=0) THEN BEGIN
       CONDICION=CONDICION2;--'CURSANDO';
    END
    IF (RESUL <= 25 AND CONDICION NOT IN ('RECURSA','RECURSANDO','CURSANDO')) THEN
         CONDICION = 'REGULAR';
    ELSE IF (RESUL BETWEEN 26 AND 50 AND CONDICION NOT IN ('RECURSA')) THEN BEGIN
          IF (RESULI <= 25 AND CONDICION NOT IN ('CURSANDO')) THEN
             CONDICION = 'REGULAR';
          ELSE
            IF (RESULI > 25) THEN
              CONDICION = 'REINCORPORA';
    END
    ELSE IF (RESUL > 40 AND RESUL <= 60 AND CONDICION NOT IN ('RECURSA')) THEN BEGIN
          IF (RESULI BETWEEN 25 AND 50) THEN
             CONDICION = 'REINCORPORA';
          ELSE BEGIN
             IF (RESULI > 50) THEN
               CONDICION = 'LIBRE';
             ELSE
               CONDICION = 'REINCORPORA';
          END
    END
    ELSE IF (RESUL > 60) THEN
          CONDICION = 'LIBRE';

/*IF (MATPROM='S' AND CONDICION='REGULAR' AND (COALESCE(TP_EVA,0) < 7 OR COALESCE(TP_EVA2,0) < 7)) THEN BEGIN
    IF (COALESCE(RECUP,0)<7) THEN BEGIN
        CONDICION='RECURSA';
    END
END*/

IF (CONDICION='REGULAR') THEN BEGIN
    SELECT PROMOCION, M.APRSFINAL FROM MATERIAS M WHERE M.CODMATERI=:CODMAT AND M.CODCARRE=:CARRE INTO :PROMOCION, :APRSFINAL;
    SELECT COALESCE(VALOR,0) FROM XXX_CONF WHERE PARAME='Regula_NotPromocion' INTO :NOTPROMCION;
    SELECT COALESCE(VALOR,0) FROM XXX_CONF WHERE PARAME='Regula_NotSinFinal' INTO :NOTAPRSFINAL;

    IF (COALESCE(PROMOCION,'N')='S') THEN BEGIN
       IF (TP_EVA<>99 AND TP_EVA >= NOTPROMCION AND
           TP_EVA2<>99 and TP_EVA2 >= NOTPROMCION) THEN BEGIN
          CONDICION='PROMOCIONA';
       END
    END
    IF (COALESCE(APRSFINAL,'N')='S') THEN BEGIN
       IF (CONDICION='REGULAR') THEN BEGIN
          CONDICION='FINAL';
       END
    END
END
FERRCOD=1;
FERRMSG='La meteria queda en condicion de '||CONDICION;
UPDATE "$$$CURSADA" X SET X.CONDICION=:CONDICION WHERE COD_ALU=:CODALU AND X.COD_MAT=:CODMAT AND X.USUARIO=:USUARIO;
SUSPEND;
END ^

SET TERM ; ^
