SET TERM ^ ;

ALTER PROCEDURE XXX_NUMCUATANIO (CARRE VARCHAR(6) CHARACTER SET NONE)
RETURNS (FCUATRIM VARCHAR(5) CHARACTER SET NONE)
AS 
DECLARE VARIABLE FDDEPRI DATE;
DECLARE VARIABLE FHTAPRI DATE;
DECLARE VARIABLE FDDESEG DATE;
DECLARE VARIABLE FHTASEG DATE;
DECLARE VARIABLE DDETER DATE;
DECLARE VARIABLE HTATER DATE;
begin
  IF (CARRE='') THEN
     FCUATRIM='';
  ELSE IF (CARRE NOT IN ('333','650')) THEN BEGIN
      SELECT FDDEPRI, FHTAPRI, FDDESEG, FHTASEG
      FROM TBL_CUAT
      WHERE FANIO=EXTRACT(YEAR FROM CURRENT_DATE)
      INTO  :FDDEPRI, :FHTAPRI, :FDDESEG, :FHTASEG;
      IF (CURRENT_DATE BETWEEN FDDEPRI AND FHTAPRI) THEN
         FCUATRIM='1'||SUBSTRING(EXTRACT(YEAR FROM FDDEPRI) FROM 3 FOR 2);
      ELSE IF (CURRENT_DATE BETWEEN FDDESEG AND FHTASEG) THEN
         FCUATRIM='2'||SUBSTRING(EXTRACT(YEAR FROM FDDESEG) FROM 3 FOR 2);
      IF (FCUATRIM IS NULL) THEN BEGIN
         FCUATRIM=IIF(EXTRACT(MONTH FROM CURRENT_DATE) IN (1,2,3,4,5,6,7),'1','2')||SUBSTRING(EXTRACT(YEAR FROM FDDESEG) FROM 3 FOR 2);
--         EXCEPTION E_CUSTOM_ERR 'No hay cuat. cargado u hoy no esta incluido en los periodos';
      END
      SUSPEND;
  END
  ELSE BEGIN
      SELECT FDDEPRI, FHTAPRI, FDDESEG, FHTASEG, FDDETER, FHTATER
      FROM TBL_TRIM
      WHERE FANIO=EXTRACT(YEAR FROM CURRENT_DATE)
      INTO  :FDDEPRI, :FHTAPRI, :FDDESEG, :FHTASEG, :DDETER, :HTATER;
      IF (CURRENT_DATE BETWEEN FDDEPRI AND FHTAPRI) THEN
         FCUATRIM='1'||SUBSTRING(EXTRACT(YEAR FROM FDDEPRI) FROM 3 FOR 2);
      ELSE IF (CURRENT_DATE BETWEEN FDDESEG AND FHTASEG) THEN
         FCUATRIM='1'||SUBSTRING(EXTRACT(YEAR FROM FDDESEG) FROM 3 FOR 2);
      ELSE IF (CURRENT_DATE BETWEEN DDETER AND HTATER) THEN
         FCUATRIM='1'||SUBSTRING(EXTRACT(YEAR FROM DDETER) FROM 3 FOR 2);
      IF (FCUATRIM IS NULL) THEN
         EXCEPTION E_CUSTOM_ERR 'No hay cuat. cargado u hoy no esta incluido en los periodos';
      SUSPEND;
  END
end ^

SET TERM ; ^
