SET TERM ^ ;

ALTER PROCEDURE XXX_INSC_CUAT_16032023 (CODALU VARCHAR(11) CHARACTER SET NONE,
CURSO INTEGER,
CARRE VARCHAR(6) CHARACTER SET NONE,
CUAANIO INTEGER,
INSTITUTO VARCHAR(40) CHARACTER SET NONE,
CARAC VARCHAR(10) CHARACTER SET NONE,
USUARIO INTEGER)
RETURNS (FERRCOD INTEGER,
FERRMSG VARCHAR(10000) CHARACTER SET NONE)
AS 
declare variable CUAT integer;
declare variable TURNO integer;
declare variable COMI integer;
declare variable CODMAT varchar(2);
declare variable DESMAT varchar(60);
declare variable ERRCOD integer;
declare variable ERRMSG varchar(1000);
declare variable CONDI varchar(20);
declare variable CONDICION varchar(20);
declare variable SW boolean;
declare variable SUPERV char(1);
declare variable CUATGRABA boolean;
begin
  FERRMSG='';
  FERRCOD=0;
  sw=false;
  IF (CHAR_LENGTH(CURSO)>3) THEN BEGIN
     FERRMSG='Mete bien los dedos tenemos comisiones de 3 digitos.';
     FERRCOD=2;
     SUSPEND;
     EXIT;
  END

  SELECT U.superv
  FROM USUARIOS U
  WHERE U.codusu=:USUARIO
  INTO :SUPERV;

  SUPERV= COALESCE(SUPERV, 'N');

  BEGIN
      CUAT=SUBSTRING(CURSO FROM 1 FOR 1);
      TURNO=SUBSTRING(CURSO FROM 2 FOR 1);
      COMI=SUBSTRING(CURSO FROM 3 FOR 1);
      WHEN ANY DO BEGIN
        SUSPEND;
        EXIT;
      END
  END
  FOR SELECT M.CODMATERI, M.DESCRIPCI
  FROM MATERIAS M
  WHERE M.CODCARRE=:CARRE AND M.CUATRIM=:CUAT AND ESTADO<>'B'
  INTO :CODMAT, :DESMAT
  DO BEGIN
      ERRCOD=0; ERRMSG=''; CONDI='';
      SELECT FERRCOD, FERRMSG, CONDICION, CUATGRABA FROM XXX_INSC_VALMAT(:CODALU,:CARRE,:CODMAT,'I') INTO :ERRCOD, :ERRMSG, :CONDI, :CUATGRABA;


      IF (ERRCOD=0) THEN BEGIN
         IF (COALESCE(CONDI,'')='') THEN CONDICION='CURSANDO'; ELSE CONDICION='RECURSANDO';
         INSERT INTO CURSADA(COD_ALU,CARRE,CUTUCO,CUA_ANIO,INSTITUT,CARAC,CONDICION,COD_MAT,NREG,USUARIO)
                      VALUES(:CODALU,:CARRE,:CURSO,:CUAANIO,:INSTITUTO,:CARAC,:CONDICION,:CODMAT,0,:USUARIO);
         FERRCOD=0;
         FERRMSG=FERRMSG||'Se inscribio: '||TRIM(DESMAT)||', Condicion:'||CONDICION||ASCII_CHAR(13);
      END
      ELSE IF (ERRCOD=2 AND SUPERV='S' AND CUATGRABA) THEN BEGIN
        FERRCOD=1;
        IF (COALESCE(CONDI,'')='') THEN CONDICION='CURSANDO'; ELSE CONDICION='RECURSANDO';
        INSERT INTO CURSADA(COD_ALU,CARRE,CUTUCO,CUA_ANIO,INSTITUT,CARAC,CONDICION,COD_MAT,NREG,USUARIO)
                      VALUES(:CODALU,:CARRE,:CURSO,:CUAANIO,:INSTITUTO,:CARAC,:CONDICION,:CODMAT,0,:USUARIO);
        FERRMSG=FERRMSG||'ERROR!!!!:'||ERRMSG||ASCII_CHAR(13)||' '||TRIM(DESMAT)||', Condicion:'||CONDICION||ASCII_CHAR(13);
        sw=true;
      END
      ELSE BEGIN
         /*IF (FERRCOD=0) THEN
            FERRCOD=ERRCOD;*/
         FERRMSG=FERRMSG||ERRMSG||ASCII_CHAR(13);
      END
  END
if (superv='S' and sw) then begin
     FERRMSG=FERRMSG||ERRMSG||ASCII_CHAR(13)||'HUBO ERRORES EN LA INSCRIPCION COMO ES SUPERVISOR PUEDE HACER LA INCRIPCION IGUAL SI ACEPTA';
end
SUSPEND;
end ^

SET TERM ; ^
