SET TERM ^ ;

ALTER PROCEDURE XXX_ADM_CUOT_POLITICA (ALUMNO INTEGER,
TIPO CHAR(1) CHARACTER SET NONE)
RETURNS (INDICE INTEGER,
VENCIM1 NUMERIC(9, 2),
VENCIM2 NUMERIC(9, 2),
VENCIM3 NUMERIC(9, 2),
VENCIM4 NUMERIC(9, 2))
AS 
DECLARE VARIABLE ADMEST INTEGER;
DECLARE VARIABLE ADMCURSO INTEGER;
DECLARE VARIABLE CARRE VARCHAR(6);
begin
  SELECT A.ADMEST, A.ADMCURSO, A.CARRE
  FROM ALUMNOS A
  WHERE A.INDICE=:ALUMNO
  INTO :ADMEST, :ADMCURSO, :CARRE;

  SELECT T.INDICE, T.VENCIM1, T.VENCIM2, T.VENCIM3, T.VENCIM4
  FROM TBL_ADM_CCUOT T
  WHERE CURRENT_DATE BETWEEN COALESCE(T.DESDE,CURRENT_DATE) AND COALESCE(T.HASTA,CURRENT_DATE) AND
        (T.CARRE IS NULL OR T.CARRE=:CARRE) AND
        (T.CURSO IS NULL OR T.CURSO=:ADMCURSO) AND
        T.TIPO=:TIPO AND T.DESACT='N'
  ORDER BY T.CARRE NULLS LAST, T.CURSO NULLS LAST, T.HASTA DESC
  ROWS 1 TO 1
  INTO :INDICE, :VENCIM1, :VENCIM2, :VENCIM3, :VENCIM4;

  SUSPEND;
end ^

SET TERM ; ^
