SET TERM ^ ;

ALTER PROCEDURE XXX_ADM_IMP_CUOTA_CAB (TIPO CHAR(1) CHARACTER SET NONE,
DDE INTEGER,
HTA INTEGER,
SALDOAL DATE)
RETURNS (NOMBRE VARCHAR(200) CHARACTER SET NONE,
DIRECC VARCHAR(200) CHARACTER SET NONE,
INDICE INTEGER,
CURSO VARCHAR(100) CHARACTER SET NONE,
CARRERA VARCHAR(200) CHARACTER SET NONE,
FECEMI DATE,
VENCI1 DATE,
VENCI2 DATE,
VENCIPROX DATE,
ALUMNO INTEGER,
INSTITUTO VARCHAR(200) CHARACTER SET NONE,
COMNUM VARCHAR(20) CHARACTER SET NONE,
RESPONS VARCHAR(100) CHARACTER SET NONE,
LETRAS VARCHAR(300) CHARACTER SET NONE,
MONTO DOUBLE PRECISION,
SALDO DOUBLE PRECISION,
TOTAL DOUBLE PRECISION,
TOTVEN2 DOUBLE PRECISION,
CODBAR VARCHAR(50) CHARACTER SET NONE,
CUOTA VARCHAR(50) CHARACTER SET NONE)
AS 
declare variable TEXTO varchar(50);
declare variable ANIO integer;
declare variable RESPDIRE varchar(200);
begin
INSTITUTO='INST. ESTUDIOS SUPERIORES DE BUENOS AIRES';
CODBAR='0937006114320015156001150070145500151611';
  FOR
  SELECT A.INDICE, D.INDICE, TRIM(A.APELLIDO)||', '||TRIM(A.NOM_APE), COALESCE(TRIM(A.DOMI),'')||' '||COALESCE(TRIM(A.LOCALI),'')||' '||COALESCE(A.COD_POS,''),
         D.TOTAL-D.TOTPAG, D.CUOTA, C.DESCRI, CA.DESCARRE,
         D.FECHA, D.VEN1FEC, D.VEN2FEC,
         LPAD(D.INDICE,8,'0'), D.ANIO, D.VEN1MON
  FROM ADM_CUOT_DATO D
  LEFT OUTER JOIN ALUMNOS A ON A.INDICE=D.ALUMNO
  LEFT OUTER JOIN TBL_ADM_CUR C ON C.CODIGO=A.ADMCURSO
  LEFT OUTER JOIN CARRERA CA ON CA.CARRE=C.CARRE
  WHERE D.INDICE BETWEEN :DDE AND :HTA AND D.TIPO=:TIPO
  ORDER BY D.INDICE
  INTO :ALUMNO, :INDICE, :NOMBRE, :DIRECC, :MONTO, :CUOTA, :CURSO, :CARRERA, :FECEMI, :VENCI1, :VENCI2, :COMNUM, :ANIO, :TOTVEN2
  DO BEGIN
  
    TOTAL=COALESCE(MONTO,0)+COALESCE(SALDO,0); --CALCULAR SALDO
    TOTVEN2=TOTVEN2+TOTAL;
    SELECT ' la cantidad en pesos '||LOWER(X.TEXTO)
    FROM ESCRIBE_MONEDA(0,:TOTAL) X
    INTO :LETRAS;

    IF (SUBSTRING(CUOTA FROM 1 FOR 1)='1') THEN
        TEXTO='Primer Semestre ';
    ELSE
        TEXTO='Segundo Semestre ';
    TEXTO=TEXTO||'Cuota '||SUBSTRING(CUOTA FROM 3 FOR 1)||' /'||ANIO;
    CUOTA=TEXTO;
    
    SELECT T.FNOMBRE, COALESCE(T.FDIRECC,'')||' '||COALESCE(T.FLOCALI,'')||' '||COALESCE(T.FCODPOS,'')
    FROM ALUMNOS A
    LEFT OUTER JOIN TUTORES T ON T.CARRE=A.CARRE AND T.COD_ALU=A.COD_ALU
    WHERE A.INDICE=:ALUMNO AND T.FRESPON='S'
    ROWS 1 TO 1
    INTO :RESPONS, :RESPDIRE;
    
    IF (RESPONS IS NOT NULL) THEN 
        DIRECC=RESPDIRE;
    ELSE
        RESPONS=NOMBRE;
        
    SUSPEND;
  END
end ^

SET TERM ; ^
