SET TERM ^ ;

ALTER PROCEDURE XXX_CUENTA_LLAMADOS (CUAANIO INTEGER)
RETURNS (LLAMADOS INTEGER)
AS 
DECLARE VARIABLE ANIO INTEGER;
DECLARE VARIABLE CANIO INTEGER;
DECLARE VARIABLE CCUAT INTEGER;
DECLARE VARIABLE CONT INTEGER;
begin
 ANIO=SUBSTRING(EXTRACT(YEAR FROM CURRENT_DATE) FROM 3 FOR 2);
 CANIO=SUBSTRING(CUAANIO FROM 2 FOR 2); --SIEMPRE SE SUMA DOS ANIO
 CCUAT=SUBSTRING(CUAANIO FROM 1 FOR 1);
 IF (CCUAT=1) THEN CONT=1;--2;
 ELSE IF (CCUAT=2) THEN CONT=1;
 CANIO=CANIO+1; --SUMO UNO AL ANIO PORQUE YA SUME LOS LLAMADOS ANTES
 WHILE (CANIO<ANIO) DO BEGIN
   CANIO=CANIO+1;
   CONT=CONT+3;
 END
 IF (EXTRACT(MONTH FROM CURRENT_DATE) IN (1,2,3)) THEN
     CONT=CONT+1;
 ELSE IF (EXTRACT(MONTH FROM CURRENT_DATE) IN (6,7,8)) THEN
     CONT=CONT+2;
 ELSE
     CONT=CONT+3;
 LLAMADOS=CONT;
 SUSPEND;
end ^

SET TERM ; ^
