SET TERM ^ ;

ALTER PROCEDURE XXX_MESAS_ALUMNOS (XMESA INTEGER,
XCARRE VARCHAR(6) CHARACTER SET NONE,
CONDICION VARCHAR(30) CHARACTER SET NONE)
RETURNS (PERM_EXA VARCHAR(10) CHARACTER SET NONE,
COD_ALU VARCHAR(11) CHARACTER SET NONE,
APELLIDO VARCHAR(40) CHARACTER SET NONE,
NOM_APE VARCHAR(40) CHARACTER SET NONE,
CODMAT CHAR(2) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE,
MESA INTEGER,
LLAMADO INTEGER,
CUTUCO INTEGER,
FECH_EXA DATE,
FECH_EMI DATE)
AS 
declare variable tipo varchar(3);
begin

CARRE=XCARRE;
MESA=XMESA;
SELECT C.tipo
FROM carrera C
WHERE C.carre=:xcarre
INTO :TIPO;

IF (TIPO NOT IN ('TER')) THEN BEGIN
   FOR
   SELECT DISTINCT P.PERM_EXA, A.COD_ALU, TRIM(A.APELLIDO) AS APELLIDO, TRIM(A.NOM_APE) AS NOM_APE,
          P.COD_MAT, P.LLAMADO, P.CUTUCO, P.FECH_EXA, P.FECH_EMI
   FROM  PERMEXA P
   INNER JOIN mesas M ON M.carre=P.carre AND M.mesa=P.mesa AND P.fech_exa=M.fech_exa
   LEFT OUTER JOIN ALUMNOS A  ON P.CARRE=A.CARRE AND P.COD_ALU=A.COD_ALU
   WHERE P.MESA=:XMESA AND P.CARRE=:XCARRE AND A.BAJA='N'
   ORDER BY A.APELLIDO, A.NOM_APE
   INTO :PERM_EXA, :COD_ALU, :APELLIDO, :NOM_APE, :CODMAT, :LLAMADO, :CUTUCO, :FECH_EXA, :FECH_EMI
   DO
      SUSPEND;
END
ELSE BEGIN
   FOR
   SELECT DISTINCT P.PERM_EXA, A.COD_ALU, TRIM(A.APELLIDO) AS APELLIDO, TRIM(A.NOM_APE) AS NOM_APE,
          P.COD_MAT, P.LLAMADO, P.CUTUCO, P.FECH_EXA, P.FECH_EMI
   FROM  PERMEXA P
   INNER JOIN mesas M ON M.carre=P.carre AND M.mesa=P.mesa AND P.fech_exa=M.fech_exa
   LEFT OUTER JOIN CURSADA C ON C.cod_alu=P.cod_alu AND C.carre=P.carre AND C.cod_mat=P.cod_mat
   LEFT OUTER JOIN ALUMNOS A  ON P.CARRE=A.CARRE AND P.COD_ALU=A.COD_ALU
   WHERE P.MESA=:XMESA AND P.CARRE=:XCARRE AND A.BAJA='N' AND
         C.condicion IN ('REGULAR')
   ORDER BY A.APELLIDO, A.NOM_APE
   INTO :PERM_EXA, :COD_ALU, :APELLIDO, :NOM_APE, :CODMAT, :LLAMADO, :CUTUCO, :FECH_EXA, :FECH_EMI
   DO
      SUSPEND;

END
/*$$IBE$$ 
END ELSE BEGIN
   IF (CONDICION='PREVIOS') THEN CONDICION='PREVIA';
   --IF (CONDICION='LIBRES') THEN CONDICION='LIBRES';
   SELECT M.COD_MAT, M.LLAMADO, M.FECH_EXA
   FROM MESAS M
   WHERE M.MESA=:XMESA AND M.CARRE=:XCARRE
   INTO :CODMAT, :LLAMADO, :FECH_EXA;
   IF (CONDICION IN ('PREVIA')) THEN BEGIN
     
     INSERT INTO TMP_EGRE(COD_ALU, CUTUCO)
     SELECT DISTINCT A.COD_ALU, C.CUTUCO
     FROM CURSADA C
     LEFT OUTER JOIN ALUMNOS A  ON C.CARRE=A.CARRE AND C.COD_ALU=A.COD_ALU
     WHERE C.COD_MAT=:CODMAT AND C.CONDICION='PREVIA' AND C.CARRE=:XCARRE AND A.BAJA='N' AND
           EXISTS(SELECT 1 FROM CURSADA H WHERE H.COD_ALU=A.COD_ALU AND H.CARRE=A.CARRE AND H.CUA_ANIO='1'||SUBSTRING(EXTRACT(YEAR FROM CURRENT_DATE) FROM 3 FOR 2) AND H.CONDICION='CURSANDO')
             $$IBE$$*/ /*AND
           (EXISTS(SELECT 1 FROM CURSADA H WHERE H.COD_ALU=A.COD_ALU AND H.CARRE=A.CARRE AND H.CUA_ANIO='1'||SUBSTRING(EXTRACT(YEAR FROM CURRENT_DATE) FROM 3 FOR 2)) OR
            EXISTS(SELECT 1 FROM CURSADA_HST H WHERE H.COD_ALU=A.COD_ALU AND H.CARRE=A.CARRE AND H.CUA_ANIO='1'||SUBSTRING(EXTRACT(YEAR FROM CURRENT_DATE) FROM 3 FOR 2)))*/ /*$$IBE$$ ;

      $$IBE$$*/ /*ESTE QUERY ES PARA TRAER A LOS ALUMNOS QUE TIENEN MATERIAS PREVIAS QUE HAYAN CURSADO AL MENOS
       EL AñO ANTERIOR EN EL COLEGIO
       TENGO QUE VALIDAR QUE EL MES EN DONDE LA IMPRIMO SEA 2 Y 3 PORQUE EN JULIO/AGOSTO NO DEBERIAN DE APARECER
       ALUMNOS QUE NO ESTEN CURSANDO EN EL AñO EN CURSO PERO QUE HAYAN CURSADO ALGO EL AñO ANTERIOR
       ESTOS ULTIMOS DEBERIAN DE SACAR PERMISOS
     */ /*$$IBE$$ 
     IF (EXTRACT(MONTH FROM CURRENT_DATE) IN (2,3)) THEN BEGIN
       INSERT INTO TMP_EGRE(COD_ALU, CUTUCO)
       SELECT DISTINCT A.COD_ALU, C.CUTUCO
       FROM CURSADA C
       LEFT OUTER JOIN ALUMNOS A  ON C.CARRE=A.CARRE AND C.COD_ALU=A.COD_ALU
       WHERE C.COD_MAT=:CODMAT AND C.CONDICION='PREVIA'
             AND C.CARRE=:XCARRE AND A.BAJA='N' AND
             NOT EXISTS(SELECT 1 FROM CURSADA H WHERE H.COD_ALU=A.COD_ALU AND H.CARRE=A.CARRE AND H.CUA_ANIO='1'||SUBSTRING(EXTRACT(YEAR FROM CURRENT_DATE) FROM 3 FOR 2) AND H.CONDICION='CURSANDO') AND
             EXISTS(SELECT 1 FROM CURSADA_HST X WHERE X.COD_ALU=A.COD_ALU AND X.CARRE=A.CARRE AND X.CUA_ANIO='1'||SUBSTRING((EXTRACT(YEAR FROM CURRENT_DATE)-1) FROM 3 FOR 2)) AND
             NOT EXISTS(SELECT 1 FROM TMP_EGRE T WHERE T.COD_ALU=C.COD_ALU);
      END
      $$IBE$$*/ /*
       ESTE ULTIMO ES PARA INCLUIR A LOS ALUMNOS QUE RINDEN EN DICIEMBRE Y NO TENGAN MATERIAS
       CURSANDO EN EL AÅO EN CURSO
       Y HAYAN APROBADO ALGO EN EL AñO EN CURSO
     */ /*$$IBE$$ 
     IF (EXTRACT(MONTH FROM CURRENT_DATE) IN (12,11)) THEN BEGIN
        INSERT INTO TMP_EGRE(COD_ALU, CUTUCO)
        SELECT DISTINCT A.COD_ALU, C.CUTUCO
        FROM CURSADA C
        LEFT OUTER JOIN ALUMNOS A  ON C.CARRE=A.CARRE AND C.COD_ALU=A.COD_ALU
        WHERE C.COD_MAT=:CODMAT AND C.CONDICION='PREVIA'
              AND C.CARRE=:XCARRE AND A.BAJA='N' AND
              NOT EXISTS(SELECT 1 FROM CURSADA H WHERE H.COD_ALU=A.COD_ALU AND H.CARRE=A.CARRE AND H.CUA_ANIO='1'||SUBSTRING(EXTRACT(YEAR FROM CURRENT_DATE) FROM 3 FOR 2) AND H.CONDICION='CURSANDO') AND
              EXISTS(SELECT 1 FROM CURSADA_HST X WHERE X.COD_ALU=A.COD_ALU AND X.CARRE=A.CARRE AND X.CUA_ANIO='1'||SUBSTRING(EXTRACT(YEAR FROM CURRENT_DATE) FROM 3 FOR 2)) AND
              NOT EXISTS(SELECT 1 FROM TMP_EGRE T WHERE T.COD_ALU=C.COD_ALU);

         $$IBE$$*/ /* EL SIGUIENTE QUERY ES PARA INCLUIR A LOS ALUMNOS QUE TENGAN PREVIAS Y EN EL ANO EN CURSO NO HAYA APROBADO NADA
           QUE ESTEN TODAS LAS METERIAS EN LIBRE, DICIEMBRE O MARZO*/ /*$$IBE$$ 
        INSERT INTO TMP_EGRE(COD_ALU, CUTUCO)
        SELECT DISTINCT A.COD_ALU, C.CUTUCO
        FROM CURSADA C
        LEFT OUTER JOIN ALUMNOS A  ON C.CARRE=A.CARRE AND C.COD_ALU=A.COD_ALU
        WHERE C.COD_MAT=:CODMAT AND C.CONDICION='PREVIA'
              AND C.CARRE=:XCARRE AND A.BAJA='N' AND
              NOT EXISTS(SELECT 1 FROM CURSADA H WHERE H.COD_ALU=A.COD_ALU AND H.CARRE=A.CARRE AND H.CUA_ANIO='1'||SUBSTRING(EXTRACT(YEAR FROM CURRENT_DATE) FROM 3 FOR 2) AND H.CONDICION='CURSANDO') AND
              NOT EXISTS(SELECT 1 FROM CURSADA_HST X WHERE X.COD_ALU=A.COD_ALU AND X.CARRE=A.CARRE AND X.CUA_ANIO='1'||SUBSTRING(EXTRACT(YEAR FROM CURRENT_DATE) FROM 3 FOR 2)) AND
              NOT EXISTS(SELECT 1 FROM TMP_EGRE T WHERE T.COD_ALU=C.COD_ALU);
     END

     FOR
       SELECT DISTINCT P.PERM_EXA, A.COD_ALU, TRIM(A.APELLIDO) AS APELLIDO, TRIM(A.NOM_APE) AS NOM_APE, P.CUTUCO, P.FECH_EMI
       FROM PERMEXA P
       LEFT OUTER JOIN ALUMNOS A ON P.CARRE=A.CARRE AND P.COD_ALU=A.COD_ALU
       LEFT OUTER JOIN CURSADA C ON C.COD_ALU=P.COD_ALU AND C.CARRE=P.CARRE AND C.COD_MAT=P.COD_MAT
       WHERE P.MESA=:XMESA AND P.CARRE=:XCARRE AND A.BAJA='N' AND C.CONDICION IN (:CONDICION)
       UNION
       SELECT DISTINCT 0, A.COD_ALU, TRIM(A.APELLIDO) AS APELLIDO, TRIM(A.NOM_APE) AS NOM_APE, P.CUTUCO, CURRENT_DATE
       FROM TMP_EGRE P
       LEFT OUTER JOIN ALUMNOS A ON P.COD_ALU=A.COD_ALU AND A.CARRE=:XCARRE
       ORDER BY 3,4
       INTO :PERM_EXA, :COD_ALU, :APELLIDO, :NOM_APE, :CUTUCO, :FECH_EMI
       DO begin
          SUSPEND;
       end
   END ELSE IF (CONDICION IN ('LIBRES','DICIEMBRE','MARZO')) THEN  BEGIN
     FOR
       SELECT DISTINCT 0, A.COD_ALU, TRIM(A.APELLIDO) AS APELLIDO, TRIM(A.NOM_APE) AS NOM_APE, C.CUTUCO, CURRENT_DATE
       FROM CURSADA C
       LEFT OUTER JOIN ALUMNOS A  ON C.CARRE=A.CARRE AND C.COD_ALU=A.COD_ALU
       WHERE C.COD_MAT=:CODMAT AND C.CARRE=:XCARRE AND A.BAJA='N' AND C.CONDICION IN (:CONDICION) AND
             C.CUA_ANIO IN ('1'||SUBSTRING(EXTRACT(YEAR FROM CURRENT_DATE) FROM 3 FOR 2),'1'||SUBSTRING((EXTRACT(YEAR FROM CURRENT_DATE)-1) FROM 3 FOR 2))
       ORDER BY 3,4
       INTO :PERM_EXA, :COD_ALU, :APELLIDO, :NOM_APE, :CUTUCO, :FECH_EMI
       DO
          SUSPEND;
   END
   ELSE IF (CONDICION IN ('P/EQUIVALEN')) THEN  BEGIN
     FOR
       SELECT DISTINCT 0, A.COD_ALU, TRIM(A.APELLIDO) AS APELLIDO, TRIM(A.NOM_APE) AS NOM_APE, C.CUTUCO, CURRENT_DATE
       FROM CURSADA C
       LEFT OUTER JOIN ALUMNOS A  ON C.CARRE=A.CARRE AND C.COD_ALU=A.COD_ALU
       WHERE C.COD_MAT=:CODMAT AND C.CARRE=:XCARRE AND A.BAJA='N' AND C.CONDICION IN (:CONDICION)
       ORDER BY 3,4
       INTO :PERM_EXA, :COD_ALU, :APELLIDO, :NOM_APE, :CUTUCO, :FECH_EMI
       DO
          SUSPEND;
   END
END
 $$IBE$$*/
end ^

SET TERM ; ^
