SET TERM ^ ;

ALTER PROCEDURE XXX_IMPRESION_EQ_BAC (CODALU VARCHAR(11) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE)
RETURNS (COLUMNA1 VARCHAR(70) CHARACTER SET NONE,
COLUMNA2 VARCHAR(70) CHARACTER SET NONE)
AS 
DECLARE VARIABLE CONDICION VARCHAR(20);
DECLARE VARIABLE DESMAT VARCHAR(60);
DECLARE VARIABLE CONTLINE INTEGER;
DECLARE VARIABLE CODMAT CHAR(2);
DECLARE VARIABLE EQ VARCHAR(2);
DECLARE VARIABLE CUATRIM SMALLINT;
DECLARE VARIABLE CUATAUX SMALLINT;
DECLARE VARIABLE LINEAS INTEGER;
BEGIN
  LINEAS=20;
  CUATAUX=0;
  FOR SELECT M.DESCRIPCI, M.CODMATERI, M.CUATRIM
  FROM MATERIAS M
  WHERE M.CODCARRE=:CARRE AND M.ESTADO<>'B'
  ORDER BY 3,2
  INTO :DESMAT, :CODMAT, :CUATRIM
  DO BEGIN
     IF (CUATAUX=0) THEN BEGIN
        CUATAUX=CUATRIM;
        INSERT INTO TMP_EQUI (FCOLUMN) VALUES('---------------- CUATRIMESTRE '||:CUATRIM||' ----------------');
     END
     IF (EXISTS(SELECT 1 FROM ANALITIC A WHERE A.CARRE=:CARRE AND A.COD_ALU=:CODALU AND A.COD_MAT=:CODMAT AND A.CONDICION='EQUIVALENCIA')) THEN
       EQ='SI';
     ELSE
       EQ='--';
     IF (CUATRIM<>CUATAUX) THEN BEGIN
          INSERT INTO TMP_EQUI (FCOLUMN) VALUES('---------------- CUATRIMESTRE '||:CUATRIM||' ----------------');
          CUATAUX=CUATRIM;
     END
     INSERT INTO TMP_EQUI (FCOLUMN) VALUES(:EQ||' >> '||:DESMAT);
  END
  CONTLINE=LINEAS;
  FOR SELECT FCOLUMN
  FROM TMP_EQUI
  ROWS 1 TO :LINEAS
  INTO :COLUMNA1
  DO BEGIN
       CONTLINE=CONTLINE+1;
       COLUMNA2=NULL;
       SELECT FCOLUMN
       FROM TMP_EQUI
       ROWS :CONTLINE TO :CONTLINE
       INTO :COLUMNA2;
       COLUMNA2=COALESCE(COLUMNA2,RPAD('******',60,'*'));
       SUSPEND;
  END
end ^

SET TERM ; ^
