SET TERM ^ ;

ALTER PROCEDURE XXX_IMPRIME_CTT (CODALU VARCHAR(11) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE)
RETURNS (FERRCOD INTEGER,
FERRMSG VARCHAR(200) CHARACTER SET NONE,
FCUATRI SMALLINT)
AS 
DECLARE VARIABLE CODMAT VARCHAR(2);
DECLARE VARIABLE CODANUAL VARCHAR(2);
DECLARE VARIABLE EQUIVALE VARCHAR(2);
DECLARE VARIABLE SW INTEGER;
DECLARE VARIABLE ANUAL CHAR(1);
DECLARE VARIABLE DESCRIPCI VARCHAR(60);
DECLARE VARIABLE DESCARRE2 VARCHAR(80);
DECLARE VARIABLE CODMAT2 VARCHAR(2);
DECLARE VARIABLE BAJA CHAR(1);
DECLARE VARIABLE CUATRIM SMALLINT;
DECLARE VARIABLE CUATRIM2 SMALLINT;
BEGIN
  FERRCOD=0;
  FERRMSG='';
  SELECT CUATRIM,CUATRIM2, DESCARRE2 FROM CARRERA C WHERE C.CARRE=:CARRE INTO :FCUATRI, :CUATRIM2, :DESCARRE2;
  FOR SELECT CODMATERI, EQUIVALE, M.ANUAL, TRIM(M.DESCRIPCI), M.ESTADO,
             M.CODANUAL
      FROM MATERIAS M
      WHERE CODCARRE=:CARRE AND (ESTADO='Y' OR COALESCE(EQUIVALE, '')<>'')
      ORDER BY CUATRIM, CODMATERI
      INTO :CODMAT, :EQUIVALE, :ANUAL, :DESCRIPCI, :BAJA, :CODANUAL
      DO BEGIN
         SW=0;
         IF (NOT EXISTS(SELECT 1 FROM ANALITIC A WHERE A.COD_ALU=:CODALU AND A.CARRE=:CARRE AND A.COD_MAT=:CODMAT)) THEN
            SW=1;
         IF (CODANUAL IS NOT NULL AND SW=1) THEN BEGIN
            CODMAT2='';
            SELECT CODMATERI FROM MATERIAS WHERE CODCARRE=:CARRE AND TRIM(DESCRIPCI)=:DESCRIPCI AND CODMATERI<>:CODMAT INTO :CODMAT2;
            SW=0;
            IF (NOT EXISTS(SELECT 1 FROM ANALITIC A WHERE A.COD_ALU=:CODALU AND A.CARRE=:CARRE AND A.COD_MAT=:CODMAT2)) THEN
               SW=1;
         END
         IF (COALESCE(EQUIVALE,'')<>'' AND SW=1) THEN BEGIN
               SW=0;
               IF (NOT EXISTS(SELECT 1 FROM ANALITIC A WHERE A.COD_ALU=:CODALU AND A.CARRE=:CARRE AND A.COD_MAT=:EQUIVALE)) THEN
                   SW=1;
         END
         IF (SW=1) THEN BEGIN
              FERRCOD=2;
              FERRMSG='No se puede imprimir, al alumnos le faltan aprobar materias';
              FCUATRI=0;
              BREAK;
         END
      END
 IF (CUATRIM2 IS NOT NULL AND FERRCOD=2) THEN BEGIN
     SW=0; FERRCOD=0; FERRMSG='';
     FOR SELECT CODMATERI, EQUIVALE, M.ANUAL, TRIM(M.DESCRIPCI), M.ESTADO,
                M.CODANUAL
         FROM MATERIAS M
         WHERE CODCARRE=:CARRE AND (ESTADO='Y' OR COALESCE(EQUIVALE, '')<>'') AND M.CUATRIM<=:CUATRIM2
         ORDER BY CUATRIM, CODMATERI
         INTO :CODMAT, :EQUIVALE, :ANUAL, :DESCRIPCI, :BAJA, :CODANUAL
         DO BEGIN
            SW=0;
            IF (NOT EXISTS(SELECT 1 FROM ANALITIC A WHERE A.COD_ALU=:CODALU AND A.CARRE=:CARRE AND A.COD_MAT=:CODMAT)) THEN
               SW=1;
            IF (CODANUAL IS NOT NULL AND SW=1) THEN BEGIN
               CODMAT2='';
               SELECT CODMATERI FROM MATERIAS WHERE CODCARRE=:CARRE AND TRIM(DESCRIPCI)=:DESCRIPCI AND CODMATERI<>:CODMAT INTO :CODMAT2;
               SW=0;
               IF (NOT EXISTS(SELECT 1 FROM ANALITIC A WHERE A.COD_ALU=:CODALU AND A.CARRE=:CARRE AND A.COD_MAT=:CODMAT2)) THEN
                  SW=1;
            END
            IF (COALESCE(EQUIVALE,'')<>'' AND SW=1) THEN BEGIN
                  SW=0;
                  IF (NOT EXISTS(SELECT 1 FROM ANALITIC A WHERE A.COD_ALU=:CODALU AND A.CARRE=:CARRE AND A.COD_MAT=:EQUIVALE)) THEN
                      SW=1;
            END
            IF (SW=1) THEN BEGIN
                 FERRCOD=2;
                 FERRMSG='No se puede imprimir, al alumnos le faltan aprobar materias';
                 FCUATRI=0;
                 BREAK;
            END
         END
     IF (FERRCOD=0) THEN BEGIN
        FERRMSG='La carrera posee titulo intermedio de '||TRIM(DESCARRE2)||', se puede imprimir hasta este cerficado';
        FERRCOD=1;
        FCUATRI=CUATRIM2;
     END
 END
 SUSPEND;
end ^

SET TERM ; ^
