SET TERM ^ ;

ALTER PROCEDURE XXX_ADM_CTACTE_CUOTAS (XALUMNO INTEGER,
XTIPO CHAR(1) CHARACTER SET NONE)
RETURNS (INDICE INTEGER,
ALUMNO INTEGER,
CUOTA CHAR(3) CHARACTER SET NONE,
ANIO INTEGER,
FECHA DATE,
ESTADO CHAR(1) CHARACTER SET NONE,
VEN1FEC DATE,
VEN2FEC DATE,
VEN3FEC DATE,
VEN4FEC DATE,
VEN1MON DOUBLE PRECISION,
VEN2MON DOUBLE PRECISION,
VEN3MON DOUBLE PRECISION,
VEN4MON DOUBLE PRECISION,
TOTAL DOUBLE PRECISION,
MONPAG DOUBLE PRECISION,
PENDIE DOUBLE PRECISION)
AS 
begin

FOR SELECT INDICE, ALUMNO, CUOTA, ANIO, FECHA, ESTADO, VEN1FEC, VEN2FEC, VEN3FEC,
       VEN4FEC, VEN1MON, VEN2MON, VEN3MON, VEN4MON, TOTAL, TOTPAG
FROM ADM_CUOT_DATO
WHERE ALUMNO=:XALUMNO AND TIPO=:XTIPO
INTO :INDICE, :ALUMNO, :CUOTA, :ANIO, :FECHA, :ESTADO, :VEN1FEC, :VEN2FEC,
     :VEN3FEC, :VEN4FEC, :VEN1MON, :VEN2MON, :VEN3MON, :VEN4MON, :TOTAL, :MONPAG
DO BEGIN
  PENDIE=TOTAL-MONPAG;
  SUSPEND;
END
end ^

SET TERM ; ^
