SET TERM ^ ;

ALTER PROCEDURE XXX_INSC_CUAT (CODALU VARCHAR(11) CHARACTER SET NONE,
CURSO INTEGER,
CARRE VARCHAR(6) CHARACTER SET NONE,
CUAANIO INTEGER,
INSTITUTO VARCHAR(40) CHARACTER SET NONE,
CARAC VARCHAR(10) CHARACTER SET NONE)
RETURNS (FERRCOD INTEGER,
FERRMSG VARCHAR(10000) CHARACTER SET NONE)
AS 
declare variable CUAT integer;
declare variable TURNO integer;
declare variable COMI integer;
declare variable CODMAT varchar(2);
declare variable DESMAT varchar(60);
declare variable ERRCOD integer;
declare variable ERRMSG varchar(1000);
declare variable CONDI varchar(20);
declare variable CONDICION varchar(20);
begin
  FERRMSG='';
  FERRCOD=0;
  IF (CHAR_LENGTH(CURSO)>3) THEN BEGIN
     FERRMSG='Mete bien los dedos tenemos comisiones de 3 digitos.';
     FERRCOD=2;
     SUSPEND;
     EXIT;
  END
  BEGIN
  CUAT=SUBSTRING(CURSO FROM 1 FOR 1);
  TURNO=SUBSTRING(CURSO FROM 2 FOR 1);
  COMI=SUBSTRING(CURSO FROM 3 FOR 1);
  WHEN ANY DO BEGIN
    SUSPEND;
    EXIT;
  END
  END
  FOR SELECT M.CODMATERI, M.DESCRIPCI
  FROM MATERIAS M
  WHERE M.CODCARRE=:CARRE AND M.CUATRIM=:CUAT AND ESTADO<>'B'
  INTO :CODMAT, :DESMAT
  DO BEGIN
      ERRCOD=0; ERRMSG=''; CONDI='';
      SELECT FERRCOD, FERRMSG, CONDICION FROM XXX_INSC_VALMAT(:CODALU,:CARRE,:CODMAT,'I') INTO :ERRCOD, :ERRMSG, :CONDI;
      IF (ERRCOD=0) THEN BEGIN
         IF (COALESCE(CONDI,'')='') THEN CONDICION='CURSANDO'; ELSE CONDICION='RECURSANDO';
         INSERT INTO CURSADA(COD_ALU,CARRE,CUTUCO,CUA_ANIO,INSTITUT,CARAC,CONDICION,COD_MAT,NREG)
                      VALUES(:CODALU,:CARRE,:CURSO,:CUAANIO,:INSTITUTO,:CARAC,:CONDICION,:CODMAT,0);
         FERRCOD=1;
         FERRMSG=FERRMSG||'Se inscribio: '||TRIM(DESMAT)||', Condicion:'||CONDICION||ASCII_CHAR(13);
      END
      ELSE BEGIN
         IF (FERRCOD=0) THEN
            FERRCOD=ERRCOD;
         FERRMSG=FERRMSG||ERRMSG||ASCII_CHAR(13);
      END
  END
SUSPEND;
end ^

SET TERM ; ^
