SET TERM ^ ;

ALTER PROCEDURE YYY_IMP_CALIFICADOR_ALUMNOS (CUTUCO INTEGER,
CUAANIO VARCHAR(3) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE,
ESTADO CHAR(1) CHARACTER SET NONE)
RETURNS (CODALU VARCHAR(13) CHARACTER SET NONE,
ALUMNO VARCHAR(100) CHARACTER SET NONE,
MATRIZ VARCHAR(10) CHARACTER SET NONE)
AS 
DECLARE VARIABLE CONDICION VARCHAR(50);
DECLARE VARIABLE TABLA VARCHAR(20);
begin
   TABLA='CURSADA';
   IF (ESTADO='T') THEN
      EXCEPTION E_CUSTOM_ERR 'LA OPCION DE TODOS NO ESTA SOPORTADA';
   ELSE IF (ESTADO='R') THEN BEGIN
      CONDICION=' AND D.CONDICION=''RECURSANDO''';
      TABLA='RECURSA';
      EXECUTE STATEMENT 'INSERT INTO TMP_BOLE (COD_ALU, CUTUCO)
       SELECT DISTINCT D.COD_ALU, D.CUTUCO
       FROM '||TABLA||' D
       WHERE CARRE='''||CARRE||''' AND ('''||CUTUCO||'''=''0'' OR D.CUTUCO='''||CUTUCO||''') AND D.CUA_ANIO='''||CUAANIO||'''
             '||CONDICION;
   END
   ELSE IF (ESTADO='N') THEN BEGIN
      CONDICION=' AND D.CONDICION<>''RECURSANDO''';
      EXECUTE STATEMENT 'INSERT INTO TMP_BOLE (COD_ALU, CUTUCO)
       SELECT DISTINCT D.COD_ALU, D.CUTUCO
       FROM '||TABLA||' D
       WHERE CARRE='''||CARRE||''' AND ('''||CUTUCO||'''=''0'' OR D.CUTUCO='''||CUTUCO||''') AND D.CUA_ANIO='''||CUAANIO||'''
             '||CONDICION||' AND NOT EXISTS(SELECT 1 FROM RECURSA R WHERE R.COD_ALU=D.COD_ALU AND R.CARRE=D.CARRE AND D.CUTUCO=R.CUTUCO AND D.CUA_ANIO=R.CUA_ANIO)';
      --SI IMPRIMO LOS RECURSANTES LOS TENGO QUE TOMAR SOLO DE RECURSA
      EXECUTE STATEMENT 'INSERT INTO TMP_BOLE (COD_ALU, CUTUCO)
       SELECT DISTINCT D.COD_ALU, D.CUTUCO
       FROM CURSADA_HST D
       WHERE CARRE='''||CARRE||''' AND ('''||CUTUCO||'''=''0'' OR D.CUTUCO='''||CUTUCO||''') AND D.CUA_ANIO='''||CUAANIO||''' AND
              NOT EXISTS(SELECT 1 FROM TMP_BOLE T WHERE T.COD_ALU=D.COD_ALU) '||CONDICION||' AND NOT EXISTS(SELECT 1 FROM RECURSA R WHERE R.COD_ALU=D.COD_ALU AND R.CARRE=D.CARRE AND D.CUTUCO=R.CUTUCO AND D.CUA_ANIO=R.CUA_ANIO)';
   END

   FOR SELECT A.COD_ALU, TRIM(A.APELLIDO)||', '||TRIM(A.NOM_APE), A.MATRIZ
   FROM TMP_BOLE T
   LEFT OUTER JOIN ALUMNOS A ON T.COD_ALU=A.COD_ALU AND A.CARRE=:CARRE
   WHERE A.BAJA='N'
   ORDER BY 2
   INTO :CODALU, :ALUMNO, :MATRIZ
   DO
      SUSPEND;
end ^

SET TERM ; ^
