SET TERM ^ ;

ALTER PROCEDURE YYY_IMP_BOLETIN_FALTAS (CODALU VARCHAR(11) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE,
ANIO INTEGER)
RETURNS (FTOTAL NUMERIC(5, 2),
FESPACI NUMERIC(5, 2))
AS 
DECLARE VARIABLE DDE DATE;
DECLARE VARIABLE HTA DATE;
DECLARE VARIABLE TOTAL NUMERIC(5,2);
begin
   SELECT T.FDDEPRI, T.FHTATER
   FROM TBL_TRIM T
   WHERE T.FANIO=:ANIO
   INTO :DDE, :HTA;

   SELECT SUM(F.CANFAL)
   FROM FALTAS F
   LEFT OUTER JOIN TBL_FALTAS T ON F.CODFAL=T.FCODIGO
   WHERE F.CARRERA=:CARRE AND F.CODALU=:CODALU AND  F.FECHA BETWEEN :DDE AND :HTA AND T.FJUSTIF='S'
   INTO :FTOTAL;

   FESPACI=0.7;
   TOTAL=COALESCE(FTOTAL,0);
   SUSPEND;

   SELECT SUM(F.CANFAL)
   FROM FALTAS F
   LEFT OUTER JOIN TBL_FALTAS T ON F.CODFAL=T.FCODIGO
   WHERE F.CARRERA=:CARRE AND F.CODALU=:CODALU AND  F.FECHA BETWEEN :DDE AND :HTA AND T.FJUSTIF='N'
   INTO :FTOTAL;

   TOTAL=TOTAL+FTOTAL;
   SUSPEND;

   FTOTAL=TOTAL;
   SUSPEND;
end ^

SET TERM ; ^
