SET TERM ^ ;

ALTER PROCEDURE YYY_IMP_BOLETIN_PENDI (CODALU VARCHAR(11) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE,
ANIO INTEGER)
RETURNS (FMATERIA VARCHAR(50) CHARACTER SET NONE,
FDIC NUMERIC(5, 2),
FMAR NUMERIC(5, 2),
FESPACI NUMERIC(5, 2),
FLINEA VARCHAR(200) CHARACTER SET NONE)
AS 
declare variable CODMAT varchar(2);
declare variable CONT smallint;
declare variable CONDICION varchar(15);
begin
  FESPACI=0.5;
  CONT=0;
  FOR SELECT CODMATERI, SIGLA
  FROM MATERIAS
  WHERE CODCARRE=:CARRE AND CUATRIM=:ANIO
  ORDER BY ORDEN
  INTO :CODMAT, :FMATERIA
  DO BEGIN
      FLINEA=NULL;
      FDIC=NULL;
      FMAR=NULL;
      CONDICION=NULL;
      SELECT C.FINAL1, C.FINAL2, C.CONDICION
      FROM CURSADA C
      WHERE COD_ALU=:CODALU AND  CARRE=:CARRE AND COD_MAT=:CODMAT --AND (COALESCE(C.FINAL1,0)<>0 OR COALESCE(C.FINAL2,0)<>0)
      INTO :FDIC, :FMAR, :CONDICION;
      IF (FDIC IS NULL AND FMAR IS NULL) THEN BEGIN
         SELECT C.FINAL1, C.FINAL2, C.CONDICION
         FROM CURSADA_HST C
         WHERE COD_ALU=:CODALU AND  CARRE=:CARRE AND COD_MAT=:CODMAT --AND (COALESCE(C.FINAL1,0)<>0 OR COALESCE(C.FINAL2,0)<>0)
         ORDER BY C.INDICE DESC
         ROWS 1 TO 1
         INTO :FDIC, :FMAR, :CONDICION;
         when ANY DO
            EXCEPTION E_CUSTOM_ERR CODALU||'-'||CARRE||'-'||CODMAT;
      END
      IF (FDIC IS NULL AND FMAR IS NULL AND TRIM(CONDICION) IN ('REGULAR','CURSANDO')) THEN
         FLINEA=LPAD('',130,'-');
      SUSPEND;
      CONT=CONT+1;
  END

  FLINEA=LPAD('',130,'-');
  FDIC=NULL;
  FMAR=NULL;
  FMATERIA=NULL;

  WHILE (CONT<10) DO BEGIN
    SUSPEND;
    CONT=CONT+1;
  END
  FESPACI=0.9;
  FLINEA=NULL;
  FDIC=NULL;
  FMAR=NULL;
  FMATERIA=NULL;
  SUSPEND;

  FESPACI=0.5;
  FLINEA=NULL;
  CONT=0;
  FOR SELECT /*C.NOTADIC, C.NOTAMAR,*/ M.SIGLA
  FROM CURSADA C
  LEFT OUTER JOIN MATERIAS M ON M.CODMATERI=C.COD_MAT AND M.CODCARRE=C.CARRE
  WHERE COD_ALU=:CODALU AND  CARRE=:CARRE AND C.CONDICION='PREVIA'
        AND M.CUATRIM<:ANIO
  INTO /*:FDIC, :FMAR,*/ :FMATERIA
  DO BEGIN
     SUSPEND;
     CONT=CONT+1;
  END

  /*FOR SELECT  M.SIGLA
  FROM CURSADA_HST C
  LEFT OUTER JOIN MATERIAS M ON M.CODMATERI=C.COD_MAT AND M.CODCARRE=C.CARRE
  LEFT OUTER JOIN ANALITIC A ON A.COD_ALU=C.COD_ALU AND A.CARRE=C.CARRE AND A.COD_MAT=C.COD_MAT
  WHERE C.COD_ALU=:CODALU AND C.CARRE=:CARRE AND C.CONDANT='PREVIA'
       AND M.CUATRIM<:ANIO
  INTO  :FMATERIA
  DO BEGIN
     SUSPEND;
     CONT=CONT+1;
  END   */
  FDIC=NULL;
  FMAR=NULL;
  FMATERIA=NULL;
  FLINEA=LPAD('',130,'-');
  WHILE (CONT<2) DO BEGIN
     SUSPEND;
     CONT=CONT+1;
  END
  /*--**
  FLINEA=NULL;
  SUSPEND;
  SUSPEND;
  --***
    */
  -- PENDIENTES DE EQUIVALENCIA
  FESPACI=0.9;
  FLINEA=NULL;
  FDIC=NULL;
  FMAR=NULL;
  FMATERIA=NULL;
  CONT=0;
  SUSPEND;

  FESPACI=0.5;
  FLINEA='';--LPAD('',130,'-');
  FOR SELECT C.FINAL1, C.FINAL2, M.SIGLA
  FROM CURSADA C
  LEFT OUTER JOIN MATERIAS M ON M.CODMATERI=C.COD_MAT AND M.CODCARRE=C.CARRE
  WHERE COD_ALU=:CODALU AND CARRE=:CARRE /*AND COALESCE(C.FINAL2,0) BETWEEN 0.1 AND 5.99*/ AND C.CONDICION='P/EQUIVALEN'
        AND M.CUATRIM<:ANIO
  INTO :FDIC, :FMAR, :FMATERIA
  DO BEGIN
     SUSPEND;
     CONT=CONT+1;
  END

  FOR SELECT C.FINAL1, C.FINAL2, M.SIGLA
  FROM CURSADA_HST C
  LEFT OUTER JOIN MATERIAS M ON M.CODMATERI=C.COD_MAT AND M.CODCARRE=C.CARRE
  LEFT OUTER JOIN ANALITIC A ON A.COD_ALU=C.COD_ALU AND A.CARRE=C.CARRE AND A.COD_MAT=C.COD_MAT
  WHERE C.COD_ALU=:CODALU AND  C.CARRE=:CARRE /*AND COALESCE(C.FINAL2,0) BETWEEN 0.1 AND 5.99*/ AND C.CONDANT='P/EQUIVALEN'
        AND M.CUATRIM<:ANIO AND A.FEC_FINAL>CURRENT_DATE
  INTO :FDIC, :FMAR, :FMATERIA
  DO BEGIN
     SUSPEND;
     CONT=CONT+1;
  END
  FDIC=NULL;
  FMAR=NULL;
  FMATERIA=NULL;
  FLINEA=LPAD('',130,'-');
  WHILE (CONT<4) DO BEGIN
     SUSPEND;
     CONT=CONT+1;
  END
end ^

SET TERM ; ^
