SET TERM ^ ;

ALTER PROCEDURE YYY_CARRE_SEGU (CODUSU INTEGER)
RETURNS (DESACT CHAR(1) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE,
DESCARRE VARCHAR(150) CHARACTER SET NONE)
AS 
begin
   FOR SELECT DESCARRE, CARRE, C.desact
   FROM BARRA_SEGU S
   INNER JOIN CARRERA C ON C.CARRE=S.BAROPC
   WHERE S.CODUSU=:CODUSU
   UNION
   SELECT DESCARRE, CARRE, DESACT
   FROM CARRERA
   WHERE EXISTS(SELECT 1 FROM USUARIOS WHERE CODUSU=:CODUSU AND SUPERV='S')
   INTO :DESCARRE, :CARRE, :DESACT
   DO
     SUSPEND;
end ^

SET TERM ; ^
