SET TERM ^ ;

ALTER PROCEDURE YYY_SEGU_OPCIONES (CODUSU INTEGER)
RETURNS (CADENA VARCHAR(200) CHARACTER SET NONE,
HABILITA CHAR(1) CHARACTER SET NONE)
AS 
begin
  FOR SELECT COALESCE(C.CARRE||'-'||C.DESCARRE,O.CODIGO||'-'||O.DESCRI),
             'S'
  FROM BARRA_SEGU B
  LEFT OUTER JOIN CARRERA C ON C.CARRE=B.BAROPC
  LEFT OUTER JOIN BARRA_OPC O ON O.CODIGO=B.BAROPC
  WHERE B.CODUSU=:CODUSU
  ORDER BY 1
  INTO :CADENA, :HABILITA
  DO
    SUSPEND;

  FOR SELECT C.CARRE||'-'||C.DESCARRE, 'N'
  FROM CARRERA C
  WHERE NOT EXISTS(SELECT 1 FROM BARRA_SEGU B WHERE B.CODUSU=:CODUSU AND C.CARRE=B.BAROPC)
  ORDER BY 1
  INTO :CADENA, :HABILITA
  DO
    SUSPEND;
  FOR SELECT O.CODIGO||'-'||O.DESCRI, 'N'
  FROM BARRA_OPC O
  WHERE NOT EXISTS(SELECT 1 FROM BARRA_SEGU B WHERE B.CODUSU=:CODUSU AND O.CODIGO=B.BAROPC)
  ORDER BY 1
  INTO :CADENA, :HABILITA
  DO
    SUSPEND;
end ^

SET TERM ; ^
