SET TERM ^ ;

ALTER PROCEDURE YYY_IMP_BOLETIN_INA_DETALLE (CODALU VARCHAR(11) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE,
ANIO VARCHAR(10) CHARACTER SET NONE)
RETURNS (FFECHACOL1 VARCHAR(12) CHARACTER SET NONE,
FDESCRICOL1 VARCHAR(100) CHARACTER SET NONE,
FCANTIDCOL1 VARCHAR(10) CHARACTER SET NONE,
FJUSTIFCOL1 VARCHAR(10) CHARACTER SET NONE,
FFECHACOL2 VARCHAR(12) CHARACTER SET NONE,
FDESCRICOL2 VARCHAR(100) CHARACTER SET NONE,
FCANTIDCOL2 VARCHAR(10) CHARACTER SET NONE,
FJUSTIFCOL2 VARCHAR(10) CHARACTER SET NONE,
FESPACI FLOAT)
AS 
declare variable FDDEPRI date;
declare variable FHTAPRI date;
declare variable FDDESEG date;
declare variable FHTASEG date;
declare variable FDDETER date;
declare variable FHTATER date;
declare variable DDE date;
declare variable HTA date;
declare variable CONT integer;
begin

SELECT FDDEPRI, FHTAPRI, FDDESEG, FHTASEG, FDDETER, FHTATER
FROM TBL_TRIM
WHERE FANIO=CAST(:ANIO AS INTEGER)
INTO :FDDEPRI, :FHTAPRI, :FDDESEG, :FHTASEG, :FDDETER, :FHTATER;

DDE= FDDEPRI;
/*if (CURRENT_DATE BETWEEN FDDEPRI AND FHTAPRI) then BEGIN
   HTA= FHTAPRI;
END
ELSE if (CURRENT_DATE BETWEEN FDDESEG AND FHTASEG) then BEGIN
   HTA= FHTASEG;
END
ELSE if (CURRENT_DATE BETWEEN FDDETER AND FHTATER) then BEGIN
*/
HTA= FHTATER;
--END

CONT=31;
FESPACI=0.595;

INSERT INTO TMP_INAS (FFECHA, FDESCRI, FCANTID, FJUSTIF)
SELECT F.FECHA,T.FDESCRI, REPLACE(CAST(F.CANFAL AS VARCHAR(5)),'.',','), IIF(T.FJUSTIF='S','SI','NO')
FROM FALTAS F
LEFT OUTER JOIN TBL_FALTAS T ON F.CODFAL=T.FCODIGO
WHERE F.CARRERA=:CARRE AND F.CODALU=:CODALU AND  F.FECHA BETWEEN :DDE AND :HTA
      AND F.CANFAL>0;

FOR SELECT LPAD(EXTRACT(DAY FROM FFECHA),2,'0')||'/'||LPAD(EXTRACT(MONTH FROM FFECHA),2,'0')||'/'||LPAD(EXTRACT(YEAR FROM FFECHA),4,'0'),
           FDESCRI, FCANTID, FJUSTIF
FROM TMP_INAS
ORDER BY FFECHA
ROWS 1 TO 30
INTO :FFECHACOL1, :FDESCRICOL1, :FCANTIDCOL1, :FJUSTIFCOL1
DO BEGIN
    FFECHACOL2=NULL;
    FDESCRICOL2=NULL;
    FCANTIDCOL2=NULL;
    FJUSTIFCOL2=NULL;
    SELECT LPAD(EXTRACT(DAY FROM FFECHA),2,'0')||'/'||LPAD(EXTRACT(MONTH FROM FFECHA),2,'0')||'/'||LPAD(EXTRACT(YEAR FROM FFECHA),4,'0'),
           FDESCRI, FCANTID, FJUSTIF
    FROM TMP_INAS
    ORDER BY FFECHA
    ROWS :CONT TO :CONT
    INTO :FFECHACOL2, :FDESCRICOL2, :FCANTIDCOL2, :FJUSTIFCOL2;
    SUSPEND;
    CONT=CONT+1;
END
DELETE FROM TMP_INAS;
/*
BORRO AUNQUE SEA TENPORAL PORQUE CUANDO IMPRIMO MAS DE UN ALUMNO ESTA TODO ATADO A LA MISMA TRANSACCION
*/
end ^

SET TERM ; ^
