SET TERM ^ ;

ALTER PROCEDURE YYY_IMP_BOLETIN_SANCI_DETA (CODALU VARCHAR(11) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE,
ANIO INTEGER)
RETURNS (FECHA DATE,
CARPOR VARCHAR(30) CHARACTER SET NONE,
FTEXTO BLOB CHARACTER SET NONE)
AS 
DECLARE VARIABLE DDE DATE;
DECLARE VARIABLE HTA DATE;
begin
   SELECT T.FDDEPRI, T.FHTATER
   FROM TBL_TRIM T
   WHERE T.FANIO=:ANIO
   INTO :DDE, :HTA;


   FOR SELECT D.FECHA, D.CARPOR, REPLACE(OBSERV,ASCII_CHAR(13)||ASCII_CHAR(10),' ')
   FROM ACTAS_DISC D
   WHERE COD_ALU=:CODALU AND CARRE=:CARRE AND  FECHA BETWEEN :DDE AND :HTA
   ORDER BY D.FECHA
   INTO :FECHA, :CARPOR, :FTEXTO
   DO
     SUSPEND;
end ^

SET TERM ; ^
