SET TERM ^ ;

ALTER PROCEDURE YYY_FALTAS_REGULA (CODALU VARCHAR(11) CHARACTER SET NONE,
CARRERA VARCHAR(6) CHARACTER SET NONE,
CODMAT VARCHAR(2) CHARACTER SET NONE,
CUAANIO VARCHAR(3) CHARACTER SET NONE,
CUTUCO INTEGER)
RETURNS (COD_ALU VARCHAR(11) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE,
FAL_EVA1 NUMERIC(5, 2),
FAL_EVA2 NUMERIC(5, 2),
FAL_EVA3 NUMERIC(5, 2))
AS 
DECLARE VARIABLE DDE_PRI DATE;
DECLARE VARIABLE HTA_PRI DATE;
DECLARE VARIABLE DDE_SEG DATE;
DECLARE VARIABLE HTA_SEG DATE;
DECLARE VARIABLE DDE_TER DATE;
DECLARE VARIABLE HTA_TER DATE;
BEGIN
  COD_ALU=CODALU;
  CARRE=CARRERA;
  IF (COALESCE(CUAANIO,'')='') THEN
     EXIT;
  IF (NOT EXISTS(SELECT 1 FROM TBL_TRIM WHERE FANIO=EXTRACT(YEAR FROM CAST('01/01/'||SUBSTRING(:CUAANIO FROM 2 FOR 2) AS DATE)))) THEN
      EXIT;
      --EXCEPTION E_CUSTOM_ERR 'Falta fecha de los trimestres para el año de cursada '||CUAANIO;

  SELECT FDDEPRI, FHTAPRI, FDDESEG, FHTASEG, FDDETER, FHTATER
  FROM TBL_TRIM
  WHERE FANIO=EXTRACT(YEAR FROM CAST('01/01/'||SUBSTRING(:CUAANIO FROM 2 FOR 2) AS DATE))
  INTO :DDE_PRI, :HTA_PRI, :DDE_SEG, :HTA_SEG, :DDE_TER, :HTA_TER;

  SELECT SUM(CANFAL)
  FROM FALTAS F
  WHERE F.CARRERA=:CARRE AND F.CODALU=:CODALU AND F.CUTUCO=:CUTUCO AND F.FECHA BETWEEN :DDE_PRI AND :HTA_PRI
  INTO :FAL_EVA1;

  SELECT SUM(CANFAL)
  FROM FALTAS F
  WHERE F.CARRERA=:CARRE AND F.CODALU=:CODALU AND F.CUTUCO=:CUTUCO AND F.FECHA BETWEEN :DDE_SEG AND :HTA_SEG
  INTO :FAL_EVA2;

  SELECT SUM(CANFAL)
  FROM FALTAS F
  WHERE F.CARRERA=:CARRE AND F.CODALU=:CODALU AND F.CUTUCO=:CUTUCO AND F.FECHA BETWEEN :DDE_TER AND :HTA_TER
  INTO :FAL_EVA3;

  FAL_EVA1=COALESCE(FAL_EVA1,0);
  FAL_EVA2=COALESCE(FAL_EVA2,0);
  FAL_EVA3=COALESCE(FAL_EVA3,0);

  SUSPEND;
end ^

SET TERM ; ^
