SET TERM ^ ;

ALTER PROCEDURE YYY_BARRA_SEGU (CODUSU INTEGER,
PROGRAM VARCHAR(15) CHARACTER SET NONE)
RETURNS (IMAGEN INTEGER,
BAJA CHAR(1) CHARACTER SET NONE,
ORDEN INTEGER,
DESCARRE VARCHAR(150) CHARACTER SET NONE,
CUATRIM SMALLINT,
RESOLUCION VARCHAR(20) CHARACTER SET NONE,
CAMINO VARCHAR(30) CHARACTER SET NONE,
DESCARRE2 VARCHAR(40) CHARACTER SET NONE,
CUATRIM2 VARCHAR(1) CHARACTER SET NONE,
RESOLU2 VARCHAR(15) CHARACTER SET NONE,
RECTOR VARCHAR(50) CHARACTER SET NONE,
DNIRECTOR VARCHAR(10) CHARACTER SET NONE,
SECRETARIA VARCHAR(50) CHARACTER SET NONE,
DNISECRET VARCHAR(10) CHARACTER SET NONE,
USUARIO SMALLINT,
CASO VARCHAR(2) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE,
INSTITUT VARCHAR(30) CHARACTER SET NONE,
CARACT VARCHAR(6) CHARACTER SET NONE,
DIRESTU VARCHAR(30) CHARACTER SET NONE,
DNIDIRESTU VARCHAR(15) CHARACTER SET NONE,
GRUPO VARCHAR(40) CHARACTER SET NONE,
ESCARRE VARCHAR(1) CHARACTER SET NONE,
TIPO VARCHAR(3) CHARACTER SET NONE,
DISTANCIA VARCHAR(1) CHARACTER SET NONE,
REGSOLAPA INTEGER,
MNUOPC VARCHAR(40) CHARACTER SET NONE)
AS 
declare variable SUPERV varchar(1);
begin
  ESCARRE='S';
  SELECT SUPERV FROM USUARIOS WHERE CODUSU=:CODUSU INTO :SUPERV;
  IF (SUPERV='N') THEN BEGIN
      FOR SELECT TIPO, DESCARRE, CUATRIM, RESOLUCION, CAMINO, DESCARRE2, CUATRIM2,
                 RESOLU2, RECTOR, DNIRECTOR, SECRETARIA, DNISECRET, USUARIO, CASO,
                 CARRE, INSTITUT, CARACT, DIRESTU, DNIDIRESTU, G.FDESCRI, C.ORDEN,
                 C.IMAGEN, C.TIPO, C.DISTANCIA, C.REGSOLAPA
      FROM BARRA_SEGU S
      INNER JOIN CARRERA C ON C.CARRE=S.BAROPC
      LEFT OUTER JOIN CARRE_GRP G ON C.GRUPO=G.FCODIGO
      WHERE S.CODUSU=:CODUSU
      ORDER BY C.GRUPO
      INTO :TIPO, :DESCARRE, :CUATRIM, :RESOLUCION, :CAMINO, :DESCARRE2, :CUATRIM2,
           :RESOLU2, :RECTOR, :DNIRECTOR, :SECRETARIA, :DNISECRET, :USUARIO, :CASO,
           :CARRE, :INSTITUT, :CARACT, :DIRESTU, :DNIDIRESTU, :GRUPO, :ORDEN, :IMAGEN,
           :TIPO, :DISTANCIA, :REGSOLAPA
      DO BEGIN
         BAJA='N';
         SUSPEND;
         /*GRUPO=GRUPO||' - Bajas';
         BAJA='S';
         SUSPEND;*/
      END
      IMAGEN=NULL;
      BAJA=NULL;
      ORDEN=NULL;
      TIPO=NULL;
      DESCARRE=NULL;
      CUATRIM=NULL;
      RESOLUCION=NULL;
      CAMINO=NULL;
      DESCARRE2=NULL;
      CUATRIM2=NULL;
      RESOLU2=NULL;
      RECTOR=NULL;
      DNIRECTOR=NULL;
      SECRETARIA=NULL;
      DNISECRET=NULL;
      USUARIO=NULL;
      CASO=NULL;
      CARRE=NULL;
      INSTITUT=NULL;
      CARACT=NULL;
      DIRESTU=NULL;
      DNIDIRESTU=NULL;
      GRUPO=NULL;
      ESCARRE='N';
    
      FOR SELECT C.CODIGO, C.DESCRI, C.IMAGEN, G.FDESCRI, C.ORDEN, C.mnuopc
      FROM BARRA_SEGU S
      INNER JOIN BARRA_OPC C ON C.CODIGO=S.BAROPC
      LEFT OUTER JOIN CARRE_GRP G ON C.GRUPO=G.FCODIGO
      WHERE S.CODUSU=:CODUSU AND (C.PROGRAM IS NULL OR C.PROGRAM=:PROGRAM)
      ORDER BY C.GRUPO
      INTO :CARRE, :DESCARRE, :IMAGEN, :GRUPO, :ORDEN, :mnuopc
      DO BEGIN
         SUSPEND;
      END
  END
  ELSE IF (SUPERV='S') THEN BEGIN
      FOR SELECT TIPO, DESCARRE, CUATRIM, RESOLUCION, CAMINO, DESCARRE2, CUATRIM2,
                 RESOLU2, RECTOR, DNIRECTOR, SECRETARIA, DNISECRET, USUARIO, CASO,
                 CARRE, INSTITUT, CARACT, DIRESTU, DNIDIRESTU, G.FDESCRI, C.ORDEN,
                 C.IMAGEN, C.TIPO, C.DISTANCIA, C.REGSOLAPA
      FROM CARRERA C
      LEFT OUTER JOIN CARRE_GRP G ON C.GRUPO=G.FCODIGO
      ORDER BY C.GRUPO
      INTO :TIPO, :DESCARRE, :CUATRIM, :RESOLUCION, :CAMINO, :DESCARRE2, :CUATRIM2,
           :RESOLU2, :RECTOR, :DNIRECTOR, :SECRETARIA, :DNISECRET, :USUARIO, :CASO,
           :CARRE, :INSTITUT, :CARACT, :DIRESTU, :DNIDIRESTU, :GRUPO, :ORDEN, :IMAGEN,
           :TIPO, :DISTANCIA, :REGSOLAPA
      DO BEGIN
         BAJA='N';
         SUSPEND;
         /*GRUPO=GRUPO||' - Bajas';
         BAJA='S';
         SUSPEND;*/
      END
      IMAGEN=NULL;
      BAJA=NULL;
      ORDEN=NULL;
      TIPO=NULL;
      DESCARRE=NULL;
      CUATRIM=NULL;
      RESOLUCION=NULL;
      CAMINO=NULL;
      DESCARRE2=NULL;
      CUATRIM2=NULL;
      RESOLU2=NULL;
      RECTOR=NULL;
      DNIRECTOR=NULL;
      SECRETARIA=NULL;
      DNISECRET=NULL;
      USUARIO=NULL;
      CASO=NULL;
      CARRE=NULL;
      INSTITUT=NULL;
      CARACT=NULL;
      DIRESTU=NULL;
      DNIDIRESTU=NULL;
      GRUPO=NULL;
      ESCARRE='N';
    
      FOR SELECT C.CODIGO, C.DESCRI, C.IMAGEN, G.FDESCRI, C.ORDEN, C.mnuopc
      FROM BARRA_OPC C
      LEFT OUTER JOIN CARRE_GRP G ON C.GRUPO=G.FCODIGO
      WHERE (C.PROGRAM IS NULL OR C.PROGRAM=:PROGRAM)
      ORDER BY C.GRUPO
      INTO :CARRE, :DESCARRE, :IMAGEN, :GRUPO, :ORDEN, :mnuopc
      DO BEGIN
         SUSPEND;
      END

  END
end ^

SET TERM ; ^
