SET TERM ^ ;

ALTER PROCEDURE YYY_SEGU_GRABA (CODUSU INTEGER,
OPCIONES BLOB CHARACTER SET NONE)
RETURNS (FERRCOD INTEGER,
FERRMSG VARCHAR(200) CHARACTER SET NONE)
AS 
declare variable opcion varchar(200);
begin

DELETE FROM BARRA_SEGU WHERE CODUSU = :CODUSU;

FOR SELECT FVALOR
FROM YYY_SEGU_EXTRAEOPC(:OPCIONES,'&')
WHERE FVALOR<>''
INTO :OPCION
DO BEGIN
    INSERT INTO BARRA_SEGU (CODUSU, BAROPC)
    VALUES (:CODUSU, SUBSTRING(:OPCION FROM 1 FOR POSITION('-',:OPCION)-1));
END
FERRCOD=0;
FERRMSG='';
SUSPEND;
end ^

SET TERM ; ^
