SET TERM ^ ;

ALTER PROCEDURE YYY_IMP_BOLETIN_SANCI (CODALU VARCHAR(11) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE,
ANIO INTEGER)
RETURNS (FTOTAL SMALLINT,
FTEXTO BLOB CHARACTER SET NONE)
AS 
DECLARE VARIABLE DDE DATE;
DECLARE VARIABLE HTA DATE;
begin
   SELECT T.FDDEPRI, T.FHTATER
   FROM TBL_TRIM T
   WHERE T.FANIO=:ANIO
   INTO :DDE, :HTA;

   SELECT COUNT(*)
   FROM ACTAS_DISC D
   WHERE COD_ALU=:CODALU AND CARRE=:CARRE AND  FECHA BETWEEN :DDE AND :HTA
   INTO :FTOTAL;
   SELECT FIRST 1 REPLACE(OBSERV,ASCII_CHAR(13)||ASCII_CHAR(10),' ')
   FROM ACTAS_DISC D
   WHERE COD_ALU=:CODALU AND CARRE=:CARRE AND  FECHA BETWEEN :DDE AND :HTA
   ORDER BY D.FECHA DESC
   INTO :FTEXTO;
   if (CHAR_LENGTH(FTEXTO)>680) then
      FTEXTO=SUBSTRING(FTEXTO FROM 1 FOR 680)||' //...';
   SUSPEND;
end ^

SET TERM ; ^
