SET TERM ^ ;

ALTER PROCEDURE YYY_IMP_CALIFICADOR_MATERIAS (CUTUCO INTEGER,
CUAANIO VARCHAR(3) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE,
CODALU VARCHAR(13) CHARACTER SET NONE,
ESTADO CHAR(1) CHARACTER SET NONE)
RETURNS (MATERIA VARCHAR(50) CHARACTER SET NONE,
NOTA1 NUMERIC(6, 2),
NOTA2 NUMERIC(6, 2),
PROM NUMERIC(6, 2),
RECUP NUMERIC(6, 2),
FINAL NUMERIC(6, 2),
TEXTO VARCHAR(200) CHARACTER SET NONE,
FINALTEXT VARCHAR(20) CHARACTER SET NONE,
FESPACI FLOAT)
AS 
DECLARE VARIABLE CUAT INTEGER;
DECLARE VARIABLE CODMAT VARCHAR(2);
DECLARE VARIABLE FECFINAL DATE;
DECLARE VARIABLE CONDICION VARCHAR(15);
DECLARE VARIABLE ACTINT VARCHAR(20);
DECLARE VARIABLE ACTDGE VARCHAR(20);
DECLARE VARIABLE CONT INTEGER;
DECLARE VARIABLE FILTRO VARCHAR(50);
DECLARE VARIABLE TABLA VARCHAR(20);
begin
   --SI SE IMPRIMEN LOS RECURSANTES DEBEN IMPRIMIRSE TODAS LAS QUE RECURSA
   -- EN UN MISMO BLOQUE SIN IMPORTAR EL CUATRIMESTRE
   -- LAS DEMAS MATEIAS DEL CUATRIMESTRE NO DEBEN MOSTRARSE
   IF (ESTADO='T') THEN
      EXCEPTION E_CUSTOM_ERR 'LA OPCION DE TODOS NO ESTA SOPORTADA';
   ELSE IF (ESTADO='R') THEN BEGIN
      FILTRO=' AND C.CONDICION=''RECURSANDO''';
      TABLA='RECURSA';
   END
   ELSE IF (ESTADO='N') THEN BEGIN
      FILTRO=' AND C.CONDICION<>''RECURSANDO''';
      TABLA='CURSADA';
   END

   FESPACI=0.65;
   CONT=0;
   CUAT=SUBSTRING(CUTUCO FROM 1 FOR 1);


   FOR SELECT M.CODMATERI, M.SIGLA
   FROM MATERIAS M
   WHERE M.CODCARRE=:CARRE AND (M.CUATRIM=:CUAT OR :ESTADO='R')  AND M.ESTADO<>'B'
   ORDER BY M.ORDEN
   INTO :CODMAT, :MATERIA
   DO BEGIN
       NOTA1=NULL;
       NOTA2=NULL;
       RECUP=NULL;
       FINAL=NULL;
       PROM=NULL;
       TEXTO=NULL;
       FINALTEXT=NULL;
       CONDICION=null;

       EXECUTE STATEMENT 'SELECT C.TP_EVA, C.TP_EVA2, C.RECUP,  C.FINAL1, (C.TP_EVA+C.TP_EVA2)/2, C.CONDICION
       FROM '||TABLA||' C
       WHERE C.COD_ALU='''||:CODALU||''' AND C.CARRE='''||:CARRE||''' AND C.CUA_ANIO='''||:CUAANIO||''' AND C.COD_MAT='''||:CODMAT||'''
             AND ('''||CUTUCO||'''=''0'' OR C.CUTUCO='''||:CUTUCO||''') '||FILTRO
       INTO :NOTA1, :NOTA2, :RECUP, :FINAL, :PROM, :CONDICION;

       IF (CONDICION IS NOT NULL) THEN
          FINALTEXT=CONDICION;

       IF (ESTADO='N' AND NOTA1 IS NULL) THEN BEGIN
          EXECUTE STATEMENT 'SELECT C.TP_EVA, C.TP_EVA2, C.RECUP,  C.FINAL1, (C.TP_EVA+C.TP_EVA2)/2, C.CONDANT
          FROM CURSADA_HST C
          WHERE C.COD_ALU='''||:CODALU||''' AND C.CARRE='''||:CARRE||''' AND C.CUA_ANIO='''||:CUAANIO||'''
                AND C.COD_MAT='''||:CODMAT||''' AND ('''||CUTUCO||'''=''0'' OR C.CUTUCO='''||:CUTUCO||''') '||FILTRO||'
          ORDER BY C.INDICE DESC
          ROWS 1 TO 1 '
          INTO :NOTA1, :NOTA2, :RECUP, :FINAL, :PROM, :CONDICION;
          IF (COALESCE(CONDICION,'CURSANDO')<>'CURSANDO') THEN
             FINALTEXT=CONDICION;
       END

       IF (ESTADO='N' AND NOTA1 IS NULL AND ESTADO<>'R' AND EXISTS(SELECT 1
                                                                   FROM ANALITIC A
                                                                   WHERE A.COD_ALU=:CODALU AND A.CARRE=:CARRE AND A.COD_MAT=:CODMAT)) THEN BEGIN
          SELECT A.CONDICION, A.ACTINT, A.ACTDGE, A.FEC_FINAL
          FROM ANALITIC A
          WHERE A.COD_ALU=:CODALU AND A.CARRE=:CARRE AND A.COD_MAT=:CODMAT
          INTO :CONDICION, :ACTINT, :ACTDGE, :FECFINAL;

          IF (CONDICION = 'EQUIVALENCIA') THEN BEGIN
            TEXTO='APROBADA POR EQUIVALENCIA ';
            IF (COALESCE(ACTINT,'')<>'') THEN
               TEXTO=TEXTO||'ACTA INTERNA NUMERO '||ACTINT;
            ELSE IF (COALESCE(ACTDGE,'')<>'') THEN
               TEXTO=TEXTO||'ACTA DGEGP NUMERO '||ACTDGE;
          END
          ELSE IF (COALESCE(CONDICION,'') <> 'EQUIVALENCIA') THEN BEGIN
            TEXTO='REGULAR DIA '||EXTRACT(DAY FROM FECFINAL)||'/'||EXTRACT(MONTH FROM FECFINAL)||'/'||EXTRACT(YEAR FROM FECFINAL);
          END
       END
       IF ((ESTADO<>'R') OR (ESTADO='R' AND CONDICION='RECURSANDO'))THEN BEGIN
         SUSPEND;
         CONT=CONT+1;
       END
   END
   MATERIA=NULL;
   NOTA1=NULL;
   NOTA2=NULL;
   RECUP=NULL;
   FINAL=NULL;
   PROM=NULL;
   TEXTO=NULL;
   FINALTEXT=NULL;
   WHILE (CONT<6) DO BEGIN
     SUSPEND;
     CONT=CONT+1;
   END
end ^

SET TERM ; ^
