SET TERM ^ ;

ALTER PROCEDURE YYY_IMP_LEGAJO (CUTUCO INTEGER,
CUANIO INTEGER,
CARRERA VARCHAR(6) CHARACTER SET NONE)
RETURNS (NOMBRE VARCHAR(100) CHARACTER SET NONE,
CARRE VARCHAR(100) CHARACTER SET NONE,
COMISI VARCHAR(100) CHARACTER SET NONE,
MATRIZ VARCHAR(100) CHARACTER SET NONE,
DNI VARCHAR(100) CHARACTER SET NONE,
EQUIVAL VARCHAR(200) CHARACTER SET NONE,
OBSERV VARCHAR(2000) CHARACTER SET NONE,
FDNI VARCHAR(100) CHARACTER SET NONE,
XDNI CHAR(1) CHARACTER SET NONE,
FPARNAC VARCHAR(100) CHARACTER SET NONE,
XPARNAC CHAR(1) CHARACTER SET NONE,
CTT VARCHAR(100) CHARACTER SET NONE,
XCTT CHAR(1) CHARACTER SET NONE,
TITSECU VARCHAR(100) CHARACTER SET NONE,
XTITSECU CHAR(1) CHARACTER SET NONE,
TITPRIM VARCHAR(100) CHARACTER SET NONE,
XTITPRIM CHAR(1) CHARACTER SET NONE,
CPT VARCHAR(100) CHARACTER SET NONE,
XCPT CHAR(1) CHARACTER SET NONE,
PASE VARCHAR(100) CHARACTER SET NONE,
XPASE CHAR(1) CHARACTER SET NONE,
FOTO VARCHAR(100) CHARACTER SET NONE,
XFOTO CHAR(1) CHARACTER SET NONE,
APTFIS VARCHAR(100) CHARACTER SET NONE,
XAPTFIS CHAR(1) CHARACTER SET NONE)
AS 
declare variable aptfec date;
declare variable fech_ctt date;
declare variable lstequi varchar(300);
begin

SELECT C.resoluCION
FROM CARRERA C
WHERE C.carre=:CARRERA
INTO :CARRE;
--CARRE=:CARRERA;

FOR
SELECT DISTINCT TRIM(A.APELLIDO)||', '||A.NOM_APE, C.CUTUCO,
       A.MATRIZ,
       A.COD_ALU, A.OBSERV,
       A.DNI,
       COALESCE(A.FPARNAC,'N'),
       COALESCE(A.FFOTO,'N'), A.CTT, A.FECH_CTT,
       COALESCE(A.FAPTFIS,'N'), A.FAPTFEC, A.CA
FROM CURSADA C
LEFT OUTER JOIN ALUMNOS A ON A.COD_ALU=C.COD_ALU AND C.CARRE=A.CARRE
WHERE C.CARRE=:CARRERA AND C.CUA_ANIO=:CUANIO AND C.CUTUCO=:CUTUCO AND C.CONDICION='CURSANDO'
--GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13
INTO :NOMBRE, :COMISI, :MATRIZ, :DNI, :OBSERV, :XDNI, :XPARNAC, :XFOTO, :XCTT, :FECH_CTT,
     :XAPTFIS, :APTFEC, :XTITSECU
DO BEGIN
   MATRIZ='LIBRO MATRIZ '||SUBSTRING(MATRIZ FROM 1 FOR 2)||'/'||SUBSTRING(MATRIZ FROM 3 FOR 3);
   XDNI=IIF(COALESCE(XDNI,'3')='3','N','S');
   XCTT=IIF(COALESCE(XCTT,'N')='N','N','S');
   XTITSECU=IIF(COALESCE(XTITSECU,'N')='N','N','S');
   OBSERV='OBSERVACIONES: '||COALESCE(OBSERV,'');

   EQUIVAL='EQUIVALENCIAS: ';
   LSTEQUI='';
   BEGIN
     SELECT LIST(DISTINCT CAST(SUBSTRING(TRIM(X.ACTINT) FROM 1 FOR CHAR_LENGTH(TRIM(X.ACTINT))-2) AS INTEGER)||'/'||SUBSTRING(TRIM(X.ACTINT) FROM CHAR_LENGTH(TRIM(X.ACTINT))-1))
     FROM ANALITIC X
     WHERE CARRE=:CARRERA AND COD_ALU=:DNI AND X.CONDICION='EQUIVALENCIA' AND X.ACTINT IS NOT NULL AND X.ACTINT<>''
     INTO :LSTEQUI;
     WHEN ANY DO
        LSTEQUI='ERROR AL CASTEARLAS';
   END
   IF (COALESCE(LSTEQUI,'')<>'') THEN
       EQUIVAL=EQUIVAL||' INTERNAS '||LSTEQUI;
   SELECT LIST(DISTINCT X.ACTDGE)
   FROM ANALITIC X
   WHERE CARRE=:CARRERA AND COD_ALU=:DNI AND X.CONDICION='EQUIVALENCIA'
   INTO :LSTEQUI;
   IF (COALESCE(LSTEQUI,'')<>'') THEN
       EQUIVAL=EQUIVAL||' DGEGP NRO.: '||LSTEQUI;

   IF (EQUIVAL='EQUIVALENCIAS: ') THEN
     EQUIVAL='EQUIVALENCIAS: NO POSEE';

   OBSERV=EQUIVAL||ASCII_CHAR(13)||ASCII_CHAR(10)||OBSERV;
   EQUIVAL='';
   FDNI='FOTOCOPIA DNI';
   FPARNAC='FOTOCOPIA PARTIDA DE NACIMIENTO';

   IF (XCTT='S') THEN
      CTT='CTT - '||EXTRACT(DAY FROM FECH_CTT)||'/'||EXTRACT(MONTH FROM FECH_CTT)||'/'||EXTRACT(YEAR FROM FECH_CTT);
   ELSE IF (XTITSECU='N' AND XCTT='N') THEN BEGIN
      IF (FECH_CTT IS NULL) THEN
         CTT='CTT - SIN FECHA';
      ELSE
         CTT='CTT - '||EXTRACT(DAY FROM FECH_CTT)||'/'||EXTRACT(MONTH FROM FECH_CTT)||'/'||EXTRACT(YEAR FROM FECH_CTT);
   END

   TITSECU='CERTIFICADO ANALITICO';
   TITPRIM='';
   XTITPRIM='';
   XCPT='' ;
   CPT='';

   PASE='';
   XPASE='';
   FOTO='FOTO 4X4';
   IF (CARRE='333') THEN BEGIN
     APTFIS='';
     IF (XAPTFIS='S') THEN
       APTFIS='APTO FISICO - '||EXTRACT(DAY FROM APTFEC)||'/'||EXTRACT(MONTH FROM APTFEC)||'/'||EXTRACT(YEAR FROM APTFEC);
   END ELSE BEGIN
      APTFIS='';
      XAPTFIS='';
   END

   IF (XTITSECU='S') THEN BEGIN
      XCTT='';
      CTT='';
   END
   SUSPEND;
END
END ^

SET TERM ; ^
