SET TERM ^ ;

ALTER PROCEDURE YYY_IMP_BOLETIN_MATE (CODALU VARCHAR(11) CHARACTER SET NONE,
CARRE VARCHAR(6) CHARACTER SET NONE,
ANIO INTEGER)
RETURNS (FMATERIA VARCHAR(50) CHARACTER SET NONE,
FTRIM1 NUMERIC(5, 2),
FTRIM2 NUMERIC(5, 2),
FTRIM3 NUMERIC(5, 2),
FLIN1 VARCHAR(5) CHARACTER SET NONE,
FLIN2 VARCHAR(5) CHARACTER SET NONE,
FLIN3 VARCHAR(5) CHARACTER SET NONE,
FPROM NUMERIC(5, 2),
FLINPRO VARCHAR(5) CHARACTER SET NONE,
FRECUP NUMERIC(5, 2),
FNOTDEF NUMERIC(5, 2),
FCONDI VARCHAR(20) CHARACTER SET NONE,
FESPACI NUMERIC(5, 2))
AS 
declare variable CODMAT varchar(2);
declare variable TOTNOTDEF numeric(5,2);
declare variable CONTMATE smallint;
begin
  FRECUP=0;
  FESPACI=0.5;
  TOTNOTDEF=0;
  CONTMATE=0;
  FOR SELECT CODMATERI, SUBSTRING(DESCRIPCI FROM 1 FOR 33)
  FROM MATERIAS
  WHERE CODCARRE=:CARRE AND CUATRIM=:ANIO
  ORDER BY ORDEN
  INTO :CODMAT, :FMATERIA
  DO BEGIN
      FTRIM1=NULL;
      FTRIM2=NULL;
      FTRIM3=NULL;
      FPROM=NULL;
      FCONDI=NULL;
      SELECT TP_EVA, TP_EVA2, TP_EVA3, IIF(COALESCE(TP_EVA2,0) BETWEEN 6 AND 10,TP_EVA2,NULL),
             CASE WHEN COALESCE(TP_EVA2,0) BETWEEN 6 AND 10 THEN CONDICION
                  WHEN COALESCE(TP_EVA2,0) < 6 or COALESCE(TP_EVA2,0) = 99  THEN 'EN PROCESO'
             END
      FROM CURSADA
      WHERE COD_ALU=:CODALU AND  CARRE=:CARRE AND COD_MAT=:CODMAT
      INTO :FTRIM1, :FTRIM2, :FTRIM3, :FPROM, :FCONDI;

      IF (FTRIM1 IS NULL AND EXISTS(SELECT 1 FROM ANALITIC WHERE COD_ALU=:CODALU AND  CARRE=:CARRE AND COD_MAT=:CODMAT AND CONDICION='EQUIVALENCIA')) THEN BEGIN
         FCONDI='EQUIVALENCIA';
      END
      ELSE IF (FTRIM1 IS NULL) THEN BEGIN
         SELECT TP_EVA, TP_EVA2, TP_EVA3, IIF(COALESCE(TP_EVA2,0) BETWEEN 6 AND 10,TP_EVA2,NULL),
             CASE WHEN COALESCE(TP_EVA2,0) BETWEEN 6 AND 10 THEN CONDICION
                  WHEN COALESCE(TP_EVA2,0) < 6 or COALESCE(TP_EVA2,0) = 99  THEN 'EN PROCESO'
             END
         FROM CURSADA_HST H
         WHERE COD_ALU=:CODALU AND  CARRE=:CARRE AND COD_MAT=:CODMAT
         ORDER BY H.INDICE DESC
         ROWS 1 TO 1
         INTO :FTRIM1, :FTRIM2, :FTRIM3, :FPROM, :FCONDI;
         /* ESTE ULTIMO QUERY ESTA HECHO ASI PORQUE SI LE CARGAN MAS DE UNA VEZ ESTA MATERIA
            QUE VAYA AL ANALITICO DESPUES LA BORRAN Y LA VUELVEN A CARGAR PUEDE
            QUEDAR MAS DE UN REGISTRO IGUAL EN ESTA TABLA. POR ESO TOMO EL ULTIMO QUE INGRESARON*/
      END
      FTRIM1=COALESCE(FTRIM1,0);
      FTRIM2=COALESCE(FTRIM2,0);
      FTRIM3=COALESCE(FTRIM3,0);
      FPROM=COALESCE(FPROM,0);
      FLIN1=IIF(FTRIM1=0,'-----','');
      FLIN2=IIF(FTRIM2=0,'-----','');
      FLIN3=IIF(FTRIM3=0,'-----','');

      IF (FTRIM1=99) THEN BEGIN
         FLIN1='AUS.';
         FTRIM1=NULL;
      END
      IF (FTRIM2=99) THEN BEGIN
         FLIN2='AUS.';
         FTRIM2=NULL;
      END
      IF (FTRIM3=99) THEN BEGIN
         FLIN3='AUS.';
         FTRIM3=NULL;
      END


      FLINPRO=IIF(FPROM=0,'-----','');
      FCONDI=COALESCE(FCONDI,'');
      FNOTDEF=FPROM;
      TOTNOTDEF=TOTNOTDEF+FNOTDEF;
      CONTMATE=CONTMATE+1;
      SUSPEND;
  END
  FMATERIA=NULL;
  FTRIM1=NULL;
  FTRIM2=NULL;
  FTRIM3=NULL;
  FPROM=NULL;
  FRECUP=NULL;
  FNOTDEF=NULL;
  FCONDI=NULL;
  FLIN1=NULL;
  FLIN2=NULL;
  FLIN3=NULL;
  FLINPRO=NULL;

  FESPACI=(12-CONTMATE)*0.5;
  SUSPEND;
  IF (COALESCE(CONTMATE,0)<>0) THEN
     FPROM=TOTNOTDEF/CONTMATE;
  FLINPRO=IIF(FPROM=0,'-----','');
  SUSPEND;
end ^

SET TERM ; ^
