SET TERM ^ ;

ALTER PROCEDURE YYY_MESAS_CARTELERA (DDE DATE,
HTA DATE,
CARRE VARCHAR(6) CHARACTER SET NONE)
RETURNS (FDESMAT VARCHAR(80) CHARACTER SET NONE,
FMESA VARCHAR(5) CHARACTER SET NONE,
FFECHA DATE,
FHORA VARCHAR(10) CHARACTER SET NONE,
FVENCIM DATE,
FTITULAR VARCHAR(50) CHARACTER SET NONE,
FVOCAL1 VARCHAR(50) CHARACTER SET NONE,
FVOCAL2 VARCHAR(50) CHARACTER SET NONE)
AS 
DECLARE VARIABLE DESMAT VARCHAR(80);
DECLARE VARIABLE MESA INTEGER;
DECLARE VARIABLE FECHA DATE;
DECLARE VARIABLE HORA VARCHAR(10);
DECLARE VARIABLE VENCIM DATE;
DECLARE VARIABLE TITULAR VARCHAR(50);
DECLARE VARIABLE VOCAL1 VARCHAR(50);
DECLARE VARIABLE VOCAL2 VARCHAR(50);
DECLARE VARIABLE CUATAUX INTEGER;
DECLARE VARIABLE CUATRIM INTEGER;
DECLARE VARIABLE DAYWEEK INTEGER;
BEGIN
CUATAUX=0;

FOR SELECT M.MESA, M.FECH_EXA, M.HORA, T.DOCENTE, V1.DOCENTE, V2.DOCENTE,
           MA.CUATRIM, MA.DESCRIPCI
FROM MESAS M
LEFT OUTER JOIN MATERIAS MA ON MA.CODMATERI=M.COD_MAT AND MA.CODCARRE=M.CARRE
LEFT OUTER JOIN DOCENTES T ON T.CODPROFES=M.TITULAR
LEFT OUTER JOIN DOCENTES V1 ON V1.CODPROFES=M.VOCAL1
LEFT OUTER JOIN DOCENTES V2 ON V2.CODPROFES=M.VOCAL2
WHERE M.FECH_EXA BETWEEN :DDE AND :HTA AND (M.CARRE=:CARRE OR :CARRE='')
      AND M.MESA BETWEEN 200 AND 299
ORDER BY M.LLAMADO, M.HORA, MA.CUATRIM, M.MESA
INTO :MESA, :FECHA, :HORA, :TITULAR, :VOCAL1, :VOCAL2, :CUATRIM, :DESMAT
DO BEGIN
  FVENCIM=NULL;
  IF (CUATRIM<>CUATAUX) THEN BEGIN
     FDESMAT=CUATRIM||' Cuatrimestre';
     FMESA=NULL;
     FFECHA=NULL;
     FHORA=NULL;
     FTITULAR=NULL;
     FVOCAL1=NULL;
     FVOCAL2=NULL;
     SUSPEND;
     CUATAUX=CUATRIM;
  END

  FVENCIM=FECHA-2;
  IF (FVENCIM='12/08/2013' OR FVENCIM='12/24/2013' OR FVENCIM='12/30/2013') THEN
       FVENCIM=FVENCIM-1;
  IF (FVENCIM='12/31/2013' OR FVENCIM='12/25/2013') THEN
       FVENCIM=FVENCIM-2;
  DAYWEEK=EXTRACT(WEEKDAY FROM FVENCIM);
  IF (DAYWEEK  NOT BETWEEN 1 AND 5) THEN BEGIN
     IF (DAYWEEK=6) THEN
       FVENCIM=FVENCIM-1;
     IF (DAYWEEK=0) THEN
       FVENCIM=FVENCIM-2;
  END
  FMESA=MESA;
  FFECHA=FECHA;
  FHORA=HORA;
  FTITULAR=TITULAR;
  FVOCAL1=VOCAL1;
  FVOCAL2=VOCAL2;
  FDESMAT=DESMAT;
  SUSPEND;
END
END ^

SET TERM ; ^
