SET TERM ^ ;

ALTER PROCEDURE YYY_SEGU_EXTRAEOPC (LINEA BLOB CHARACTER SET NONE,
SEPARADOR CHAR(1) CHARACTER SET NONE)
RETURNS (FCAMPO INTEGER,
FVALOR BLOB CHARACTER SET NONE)
AS 
DECLARE VARIABLE X INTEGER;
DECLARE VARIABLE Y INTEGER;
BEGIN

FCAMPO=1;
FVALOR='';
X=1;
Y=1;
WHILE (POSITION(SEPARADOR,LINEA,X)>0) DO BEGIN
   X=POSITION(SEPARADOR,LINEA,X);
   FVALOR=SUBSTRING(LINEA FROM Y FOR X-Y);
   SUSPEND;
   FCAMPO=FCAMPO+1;
   X=X+1;
   Y=X;
END
X=CHAR_LENGTH(LINEA)+1;
FVALOR=SUBSTRING(LINEA FROM Y FOR X-Y);
SUSPEND;
END ^

SET TERM ; ^
