SET TERM ^ ;

ALTER PROCEDURE YYY_IMP_BOLETIN_ALUMNOS (CARRE VARCHAR(6) CHARACTER SET NONE,
CODALU VARCHAR(11) CHARACTER SET NONE,
ANIO INTEGER,
BAJAS CHAR(1) CHARACTER SET NONE,
CUTUCO INTEGER)
RETURNS (FCODALU VARCHAR(11) CHARACTER SET NONE,
FANIO INTEGER,
FTURNO VARCHAR(5) CHARACTER SET NONE,
FDIVI VARCHAR(5) CHARACTER SET NONE,
FCICLO INTEGER,
FDOCUMENTO VARCHAR(11) CHARACTER SET NONE,
FNOMBRE VARCHAR(80) CHARACTER SET NONE,
FCUTUCO INTEGER)
AS 
DECLARE VARIABLE CUAANIO VARCHAR(5);
begin
/*h.cutuco<>'999' and
esta porque tuve que insertar registros a mano porque me mande un moco grande*/
  IF (COALESCE(CODALU,'')='') THEN BEGIN
     INSERT INTO TMP_BOLE(COD_ALU, CUTUCO)
     SELECT C.COD_ALU, CUTUCO
     FROM CURSADA C
     LEFT OUTER JOIN ALUMNOS A ON A.COD_ALU=C.COD_ALU AND A.CARRE=:CARRE
     WHERE C.CARRE=:CARRE AND C.CUA_ANIO='1'||SUBSTRING(:ANIO FROM 3 FOR 2) AND A.BAJA=:BAJAS AND (CUTUCO=:CUTUCO OR COALESCE(:CUTUCO,0)=0)
     UNION
     SELECT H.COD_ALU, CUTUCO
     FROM CURSADA_HST H
     LEFT OUTER JOIN ALUMNOS A ON A.COD_ALU=H.COD_ALU AND A.CARRE=:CARRE
     WHERE /*h.cutuco<>'999' and*/ H.CARRE=:CARRE AND H.CUA_ANIO='1'||SUBSTRING(:ANIO FROM 3 FOR 2) AND A.BAJA=:BAJAS AND (CUTUCO=:CUTUCO OR COALESCE(:CUTUCO,0)=0);
     FCICLO=ANIO;
  END ELSE BEGIN
     INSERT INTO TMP_BOLE(COD_ALU, CUTUCO)
     SELECT C.COD_ALU, CUTUCO
     FROM CURSADA C
     LEFT OUTER JOIN MATERIAS M ON M.CODMATERI=C.COD_MAT AND M.CODCARRE=C.CARRE
     LEFT OUTER JOIN ALUMNOS A ON A.COD_ALU=C.COD_ALU AND A.CARRE=:CARRE
     WHERE C.COD_ALU=:CODALU AND C.CARRE=:CARRE AND M.CUATRIM=:ANIO AND A.BAJA=:BAJAS
     UNION
     SELECT H.COD_ALU, CUTUCO
     FROM CURSADA_HST H
     LEFT OUTER JOIN MATERIAS M ON M.CODMATERI=H.COD_MAT AND M.CODCARRE=H.CARRE
     LEFT OUTER JOIN ALUMNOS A ON A.COD_ALU=H.COD_ALU AND A.CARRE=:CARRE
     WHERE /*h.cutuco<>'999' and */H.COD_ALU=:CODALU AND H.CARRE=:CARRE AND M.CUATRIM=:ANIO AND A.BAJA=:BAJAS;

     SELECT FIRST 1 C.CUA_ANIO
     FROM CURSADA C
     LEFT OUTER JOIN MATERIAS M ON M.CODMATERI=C.COD_MAT AND M.CODCARRE=C.CARRE
     LEFT OUTER JOIN ALUMNOS A ON A.COD_ALU=C.COD_ALU AND A.CARRE=:CARRE
     WHERE C.COD_ALU=:CODALU AND C.CARRE=:CARRE AND M.CUATRIM=:ANIO AND A.BAJA=:BAJAS
     INTO :CUAANIO;
     if (CUAANIO IS NULL) then
        SELECT FIRST 1 H.CUA_ANIO
        FROM CURSADA_HST H
        LEFT OUTER JOIN MATERIAS M ON M.CODMATERI=H.COD_MAT AND M.CODCARRE=H.CARRE
        LEFT OUTER JOIN ALUMNOS A ON A.COD_ALU=H.COD_ALU AND A.CARRE=:CARRE
        WHERE H.COD_ALU=:CODALU AND H.CARRE=:CARRE AND M.CUATRIM=:ANIO AND A.BAJA=:BAJAS
        INTO :CUAANIO;
        FCICLO=EXTRACT(YEAR FROM CAST('01/01/'||SUBSTRING(CUAANIO FROM 2 FOR 2) AS DATE));
  END


  FOR SELECT DISTINCT T.COD_ALU, T.CUTUCO, TRIM(A.APELLIDO)||', '||TRIM(A.NOM_APE)
  FROM TMP_BOLE T
  LEFT OUTER JOIN ALUMNOS A ON A.COD_ALU=T.COD_ALU AND A.CARRE=:CARRE
  ORDER BY 2,3
  INTO :FCODALU, :FCUTUCO, :FNOMBRE
  DO BEGIN
     FTURNO=CASE SUBSTRING(FCUTUCO FROM 2 FOR 1) WHEN '1' THEN 'Man.' WHEN '2' THEN 'Tar.' ELSE '' END;
     FDIVI =ASCII_CHAR(64+CAST(SUBSTRING(FCUTUCO FROM 3 FOR 1) AS INTEGER));
     FANIO= SUBSTRING(FCUTUCO FROM 1 FOR 1);
     FDOCUMENTO=SUBSTRING(FCODALU FROM 4 FOR 2)||'.'||SUBSTRING(FCODALU FROM 6 FOR 3)||'.'||SUBSTRING(FCODALU FROM 9 FOR 3);
     SUSPEND;
  END
end ^

SET TERM ; ^
