SET TERM ^ ;

ALTER PROCEDURE ZZZZ_PALOS (CARRE VARCHAR(6) CHARACTER SET NONE,
CUTUCO INTEGER,
CUANTOS INTEGER,
ALMENOS INTEGER,
DDE CHAR(2) CHARACTER SET NONE,
HTA CHAR(2) CHARACTER SET NONE)
RETURNS (CODALU VARCHAR(13) CHARACTER SET NONE,
NOMBRE VARCHAR(80) CHARACTER SET NONE,
APELLIDO VARCHAR(80) CHARACTER SET NONE)
AS 
declare variable sw integer;
declare variable codmateri varchar(2);
declare variable errcod integer;
declare variable cuatrim integer;
declare variable cua_anio char(3);
declare variable matriz varchar(6);
declare variable orden smallint;
declare variable canmatapr integer;
declare variable canmattot integer;
BEGIN

  CUATRIM=SUBSTRING(cutuco FROM 1 FOR 1);
  SELECT FCUATRIM FROM XXX_NUMCUATANIO(:CARRE)INTO :CUA_ANIO;

  FOR SELECT DISTINCT A.COD_ALU, TRIM(A.APELLIDO), TRIM(A.NOM_APE), A.MATRIZ, 2
  FROM ALUMNOS A
  LEFT OUTER JOIN CURSADA X1 ON X1.COD_ALU=A.COD_ALU AND X1.CARRE=A.CARRE AND X1.CONDICION='REGULAR'
  LEFT OUTER JOIN ANALITIC X2 ON X2.COD_ALU=A.COD_ALU AND X2.CARRE=A.CARRE
  WHERE /*COALESCE(SUBSTRING(A.MATRIZ FROM 1 FOR 2),'')<='40' AND*/ A.COD_ALU<>'DNI33072591' AND A.CARRE=:CARRE AND A.BAJA='S'
        AND (EXISTS(SELECT 1 FROM CURSADA C WHERE C.COD_ALU=A.COD_ALU AND C.CARRE=A.CARRE AND
                  SUBSTRING(C.CUA_ANIO FROM 2 FOR 2) BETWEEN :DDE AND :HTA AND C.CONDICION='REGULAR') OR
           EXISTS(SELECT 1 FROM ANALITIC N WHERE N.CONDICION<>'EQUIVALENCIA' AND N.COD_ALU=A.COD_ALU AND N.CARRE=A.CARRE
                  AND N.FEC_FINAL BETWEEN CAST('01/01/'||:DDE AS DATE) AND CAST('12/31/'||:HTA AS DATE))
           )
       AND NOT EXISTS(SELECT 1 FROM CURSADA C WHERE C.COD_ALU=A.COD_ALU AND C.CARRE=A.CARRE AND
                       SUBSTRING(C.CUA_ANIO FROM 2 FOR 2) BETWEEN :DDE AND :HTA AND C.CONDICION='CURSANDO')

  UNION
  SELECT A.COD_ALU, TRIM(A.APELLIDO), TRIM(A.NOM_APE), A.MATRIZ, 1
  FROM ALUMNOS A
  WHERE /*COALESCE(SUBSTRING(A.MATRIZ FROM 1 FOR 2),'')<='40' AND*/ A.COD_ALU<>'DNI33072591' AND A.CARRE=:CARRE AND A.BAJA='N'
         AND NOT EXISTS(SELECT 1 FROM CURSADA C WHERE C.COD_ALU=A.COD_ALU AND C.CARRE=A.CARRE AND
                       SUBSTRING(C.CUA_ANIO FROM 2 FOR 2) BETWEEN :DDE AND :HTA AND C.CONDICION IN ('CURSANDO'))

  ORDER BY 5,4 DESC
  INTO :CODALU, :APELLIDO, :NOMBRE, :MATRIZ, :ORDEN
  DO BEGIN
      SW=0;
      IF (CARRE<>'BAC' AND NOT EXISTS(SELECT 1 FROM CURSADA C
              LEFT OUTER JOIN MATERIAS M ON M.CODMATERI=C.COD_MAT AND M.CODCARRE=C.CARRE
              WHERE C.COD_ALU=:CODALU AND C.CARRE=:CARRE AND C.CONDICION='REGULAR' AND M.CUATRIM=:ALMENOS)) THEN
          SW=2;
      ELSE IF (CARRE<>'BAC' AND EXISTS(SELECT 1 FROM CURSADA C
              LEFT OUTER JOIN MATERIAS M ON M.CODMATERI=C.COD_MAT AND M.CODCARRE=C.CARRE
              WHERE C.COD_ALU=:CODALU AND C.CARRE=:CARRE AND C.CONDICION='REGULAR' AND M.CUATRIM>=:ALMENOS)) THEN
          SW=0;
      /*ELSE IF (NOT EXISTS(SELECT 1 FROM ANALITIC C
              LEFT OUTER JOIN MATERIAS M ON M.CODMATERI=C.COD_MAT AND M.CODCARRE=C.CARRE
              WHERE C.COD_ALU=:CODALU AND C.CARRE=:CARRE AND M.CUATRIM=:ALMENOS AND C.CONDICION<>'EQUIVALENCIA')) THEN
          SW=2;*/

      IF (CARRE='BAC') THEN BEGIN
          CANMATAPR=0;
          CANMATTOT=0;
          SELECT COUNT(*)
          FROM ANALITIC C
          LEFT OUTER JOIN MATERIAS M ON M.CODMATERI=C.COD_MAT AND M.CODCARRE=C.CARRE
          WHERE C.COD_ALU=:CODALU AND C.CARRE=:CARRE AND M.CUATRIM<=:ALMENOS
          INTO :CANMATAPR;
          
          SELECT COUNT(*)
          FROM MATERIAS M
          WHERE M.CODCARRE =:CARRE AND M.CUATRIM<=:ALMENOS AND ESTADO<>'B'
          INTO :CANMATTOT;

          SW=2;
          IF (CANMATAPR>=(CANMATTOT-2)) THEN
             SW=0;
      END

      FOR SELECT M.CODMATERI
      FROM MATERIAS M
      LEFT OUTER JOIN XXX_INS_BUSCADOR_MATERIAS(:CARRE, :CODALU) X ON M.CODMATERI=X.CODMATERI
      WHERE M.CUATRIM=:CUATRIM AND :SW=0 AND M.CODCARRE=:CARRE AND M.ESTADO<>'B'
      INTO :CODMATERI
      DO
      BEGIN
         ERRCOD=NULL;
         SELECT FERRCOD
         FROM XXX_INSC_VALMAT(:CODALU,:CARRE,:CODMATERI,'I')
         INTO :ERRCOD;
         IF (ERRCOD=0) THEN BEGIN
             SW=1;
             UPDATE ALUMNOS SET BAJA='N' WHERE COD_ALU=:CODALU AND CARRE=:CARRE;
             INSERT INTO CURSADA (COD_ALU, APELLIDO, CARRE, CUTUCO, COD_MAT, CUA_ANIO,
                                  TP_EVA, RECUP, TP_EVA2, RECUP2, REGULAR, TOT_HORAS,
                                  INASIST, JUSTIF, CONDICION, FINAL1, FECHA1, FINAL2,
                                  FECHA2, FINAL3, FECHA3, FINAL4, FECHA4, MATRIZ,
                                  INSTITUT, CARAC, ACTINT, ACTDGE, ACTSNE, NREG,
                                  COLEGIO, "PLAN", A_C, DEFINE, INDICE, TP_EVA3, PROM,
                                  USUARIO, FEC_EVA1, FEC_EVA2, FEC_EVA3, FAL_EVA1,
                                  FAL_EVA2, FAL_EVA3, NOTADIC, NOTAMAR, FECHDIC, FECHMAR,
                                  ULTMOD, FACTFIN1, FACTFIN2, FACTFIN3)
             VALUES (:CODALU, :APELLIDO, :CARRE, :CUTUCO, :CODMATERI, :CUA_ANIO,
                    null, null, null, null, null, null, null,
                    null, 'CURSANDO', null, null, null, null, null,
                    null, null, null, :MATRIZ, null, null, null,
                    null, null, null, null, null, null, null, null,
                    null, null, 0, null, null, null, null,
                    null, null, null, null, null, null, current_timestamp,
                    null, null, null);
         END
      END
      IF (SW=1) THEN BEGIN
         SUSPEND;
         CUANTOS=CUANTOS-1;
         IF (CUANTOS=0) THEN
            BREAK;
      END
  END
END ^

SET TERM ; ^
